#if UNITY_EDITOR
using System;
using System.IO;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEditor;
using UnityEditor.SceneManagement;
using Doppel6.Probe;
public static class FootballSetup {
    // Writes FootballSoleContour.cs: the lower boot (within 5 cm of the
    // standing sole) of football-v130 and its WorldPlayer copy as bind-pose
    // vertices in the space of each skinning bone with their weights, so the
    // runtime rebuilds those vertices exactly (linear blend skinning) without
    // a readable mesh. The lowest vertex per 1 cm ground cell and the outermost
    // per 1 cm height band and 2 cm side strip are kept.
    public static string GenerateSoleContour(string repository){
        const string asset="Assets/Doppel6EngineProbe/Art/football-v130.fbx";
        var scene=EditorSceneManager.NewPreviewScene();var graph=UnityEngine.Playables.PlayableGraph.Create("D6 sole contour");
        try{
            var actor=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(asset));UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(actor,scene);actor.transform.localScale=Vector3.one*1.45f;
            var animator=actor.GetComponent<Animator>();if(animator==null)animator=actor.AddComponent<Animator>();animator.applyRootMotion=false;graph.SetTimeUpdateMode(UnityEngine.Playables.DirectorUpdateMode.Manual);
            var stand=Array.Find(AssetDatabase.LoadAllAssetsAtPath(asset),a=>a is AnimationClip&&a.name==FootballGround.ReferenceClip) as AnimationClip??throw new InvalidOperationException("Missing "+FootballGround.ReferenceClip);
            var playable=UnityEngine.Animations.AnimationClipPlayable.Create(graph,stand);playable.SetApplyFootIK(false);UnityEngine.Animations.AnimationPlayableOutput.Create(graph,"rig",animator).SetSourcePlayable(playable);graph.Play();playable.SetTime(0);graph.Evaluate(0);
            var skin=actor.GetComponentInChildren<SkinnedMeshRenderer>();var mesh=skin.sharedMesh;var bones=skin.bones;var binds=mesh.bindposes;var vertices=mesh.vertices;var weights=mesh.boneWeights;
            var names=new[]{mesh.name,AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Doppel6EngineProbe/Art/WorldPlayer.asset")?.name};
            var skinning=new Matrix4x4[bones.Length];for(int b=0;b<bones.Length;b++)skinning[b]=bones[b]!=null?bones[b].localToWorldMatrix*binds[b]:Matrix4x4.identity;
            Vector3 World(int i){var w=weights[i];var m=new Matrix4x4();void Add(int b,float x){if(x<=0)return;var s=skinning[b];for(int k=0;k<16;k++)m[k]+=s[k]*x;}Add(w.boneIndex0,w.weight0);Add(w.boneIndex1,w.weight1);Add(w.boneIndex2,w.weight2);Add(w.boneIndex3,w.weight3);return m.MultiplyPoint3x4(vertices[i]);}
            var world=new Vector3[vertices.Length];float pitch=float.MaxValue;for(int i=0;i<vertices.Length;i++){world[i]=World(i);pitch=Mathf.Min(pitch,world[i].y);}
            Transform Bone(string n)=>Array.Find(actor.GetComponentsInChildren<Transform>(),t=>t.name=="mixamorig:"+n);
            var feet=new[]{(Bone("LeftFoot"),Bone("LeftToeBase"),Bone("LeftToe_End")),(Bone("RightFoot"),Bone("RightToeBase"),Bone("RightToe_End"))};
            var text=new System.Text.StringBuilder();var inv=System.Globalization.CultureInfo.InvariantCulture;string F(float v){var t=v.ToString("0.#####",inv);return t.Contains(".")?t+"f":t;}int total=0;
            text.Append("// Generated by D6Cli.SoleContour (FootballSetup.GenerateSoleContour); do not edit.\n// Lower boot of the listed meshes: per point n, then n times (bone index,\n// weight, bind-pose x, y, z in that bone's space). Rebuilt by FootballGround.\nnamespace Doppel6.Probe {\npublic static class FootballSoleContour {\n    public sealed class Foot {public string[] bones;public float[] points;}\n    public static Foot[] Find(string mesh){\n        if(");
            text.Append(string.Join("&&",Array.ConvertAll(Array.FindAll(names,n=>!string.IsNullOrEmpty(n)),n=>"mesh!=\""+n+"\"")));text.Append(")return null;\n        return new[]{\n");
            foreach(var (ankle,toe,tip) in feet){
                var ahead=Vector3.ProjectOnPlane(toe.position-ankle.position,Vector3.up).normalized;var side=Vector3.Cross(Vector3.up,ahead);var keep=new Dictionary<(int,int,int),(int index,float score)>();
                void Keep((int,int,int) key,int index,float score){if(!keep.TryGetValue(key,out var old)||score<old.score)keep[key]=(index,score);}
                for(int i=0;i<vertices.Length;i++){
                    var owner=bones[weights[i].boneIndex0];if(owner!=ankle&&owner!=toe&&owner!=tip)continue;var p=world[i];if(p.y-pitch>.05f)continue;
                    float along=Vector3.Dot(p-ankle.position,ahead);int band=Mathf.FloorToInt((p.y-pitch)/.01f),lateral=Mathf.FloorToInt(Vector3.Dot(p-ankle.position,side)/.02f);
                    Keep((0,Mathf.FloorToInt(p.x/.01f),Mathf.FloorToInt(p.z/.01f)),i,p.y);Keep((1,band,lateral),i,along);Keep((2,band,lateral),i,-along);
                }
                var used=new List<string>();var data=new List<string>();int Index(Transform b){int k=used.IndexOf(b.name);if(k<0){used.Add(b.name);k=used.Count-1;}return k;}
                var chosen=new List<int>();foreach(var item in keep.Values)if(!chosen.Contains(item.index))chosen.Add(item.index);chosen.Sort();
                foreach(int i in chosen){var w=weights[i];var parts=new List<(int b,float x)>();if(w.weight0>0)parts.Add((w.boneIndex0,w.weight0));if(w.weight1>0)parts.Add((w.boneIndex1,w.weight1));if(w.weight2>0)parts.Add((w.boneIndex2,w.weight2));if(w.weight3>0)parts.Add((w.boneIndex3,w.weight3));
                    data.Add(parts.Count.ToString(inv));foreach(var (b,x) in parts){var local=binds[b].MultiplyPoint3x4(vertices[i]);data.Add(Index(bones[b]).ToString(inv));data.Add(F(x));data.Add(F(local.x));data.Add(F(local.y));data.Add(F(local.z));}}
                total+=chosen.Count;
                text.Append("            new Foot{bones=new[]{"+string.Join(",",used.ConvertAll(n=>"\""+n+"\""))+"},points=new float[]{"+string.Join(",",data)+"}},\n");
            }
            text.Append("        };\n    }\n}\n}\n");
            File.WriteAllText(Path.Combine(repository,"prototypes/match-engine-unity/FootballSoleContour.cs"),text.ToString().Replace("\r",""));
            return "sole contour points="+total+" meshes="+string.Join(",",names);
        }finally{if(graph.IsValid())graph.Destroy();EditorSceneManager.ClosePreviewScene(scene);}
    }
    public static string Configure(){
        AnimationClip Clip(string path,string name){return Array.Find(AssetDatabase.LoadAllAssetsAtPath(path),a=>a is AnimationClip&&a.name==name) as AnimationClip??throw new InvalidOperationException("Missing football clip "+name);}
        const string baseAsset="Assets/Doppel6EngineProbe/Art/football-v130.fbx",pilot="Assets/Doppel6EngineProbe/Art/football-contact-pilot.fbx";
        AnimationClip Adapt(string name){
            var source=Clip(pilot,name);var path="Assets/Doppel6EngineProbe/Art/"+name+".anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(path);
            if(clip==null){clip=new AnimationClip();AssetDatabase.CreateAsset(clip,path);}clip.ClearCurves();clip.name=name;clip.frameRate=source.frameRate;
            // Unity collapses the sole FBX armature root in animation-only files.
            // Restore the existing prefab's exact path; never animate the actor root.
            foreach(var binding in AnimationUtility.GetCurveBindings(source)){var target=binding;target.path="target_character"+(binding.path.Length>0?"/"+binding.path:"");AnimationUtility.SetEditorCurve(clip,target,AnimationUtility.GetEditorCurve(source,binding));}
            AnimationUtility.SetAnimationClipSettings(clip,AnimationUtility.GetAnimationClipSettings(source));EditorUtility.SetDirty(clip);return clip;
        }
        var pass=Adapt("pass_inside_meshy");var receive=Adapt("receive_ground_meshy");
        var previous=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var scene=EditorSceneManager.OpenScene("Assets/Doppel6EngineProbe/Probe.unity",OpenSceneMode.Additive);
        try{ProbeBridge bridge=null;foreach(var root in scene.GetRootGameObjects()){bridge=root.GetComponentInChildren<ProbeBridge>();if(bridge!=null)break;}if(bridge==null)throw new InvalidOperationException("ProbeBridge is missing");bridge.passClip=pass;bridge.receiveClip=receive;bridge.keeperHighClip=Clip(baseAsset,"keeper_high_meshy");bridge.keeperDiveClip=Clip(baseAsset,"keeper_dive_meshy");bridge.keeperRiseClip=Clip(baseAsset,"keeper_rise_meshy");bridge.walkClip=Clip(baseAsset,"walking");bridge.fastRunClip=Clip(baseAsset,"run_fast4");bridge.sprintClip=Clip(baseAsset,"sprint_forward");bridge.backClip=Clip(baseAsset,"back_walk");bridge.brakeClip=Clip(baseAsset,"brake_meshy");bridge.turnLeftClip=Clip(baseAsset,"turn_run_left");bridge.turnRightClip=Clip(baseAsset,"turn_run_right");EditorUtility.SetDirty(bridge);EditorSceneManager.SaveScene(scene);return "Football contacts and seven existing locomotion clips assigned";}
        finally{EditorSceneManager.CloseScene(scene,true);UnityEngine.SceneManagement.SceneManager.SetActiveScene(previous);AssetDatabase.SaveAssets();}
    }
    // Assigns further existing clips of football-v130.fbx for gait bands, turns,
    // fouls (victim fall, offender stumble) and celebrations. No clip, prefab or
    // Meshy asset is created or changed.
    public static string ConfigurePresentation(){
        const string baseAsset="Assets/Doppel6EngineProbe/Art/football-v130.fbx";
        AnimationClip Clip(string name){return Array.Find(AssetDatabase.LoadAllAssetsAtPath(baseAsset),a=>a is AnimationClip&&a.name==name) as AnimationClip??throw new InvalidOperationException("Missing football clip "+name);}
        var previous=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var scene=EditorSceneManager.OpenScene("Assets/Doppel6EngineProbe/Probe.unity",OpenSceneMode.Additive);
        try{
            ProbeBridge bridge=null;foreach(var root in scene.GetRootGameObjects()){bridge=root.GetComponentInChildren<ProbeBridge>();if(bridge!=null)break;}if(bridge==null)throw new InvalidOperationException("ProbeBridge is missing");
            bridge.jogClip=Clip("run_fast6");bridge.fastBackClip=Clip("back_left");bridge.turnIdleLeftClip=Clip("turn_idle_left");bridge.turnIdleRightClip=Clip("turn_idle_right");bridge.turnWalkLeftClip=Clip("turn_walk_left");bridge.turnWalkRightClip=Clip("turn_walk_right");
            bridge.celebrateArmsClip=Clip("celebrate_arms");bridge.celebrateFistClip=Clip("celebrate_fist");bridge.celebrateVictoryClip=Clip("celebrate_victory");bridge.foulFallClip=Clip("foul_fall_meshy");bridge.foulStumbleClip=Clip("foul_stumble_meshy");bridge.keeperShuffleClip=Clip("keeper_shuffle_meshy");
            // Natural-motion iteration: ready stance for the procedural side step, fastest measured backward stride.
            bridge.readyClip=Clip("idle_ready");bridge.backRunClip=Clip("back_right");
            EditorUtility.SetDirty(bridge);EditorSceneManager.SaveScene(scene);return "Fourteen further existing clips assigned";
        }finally{EditorSceneManager.CloseScene(scene,true);UnityEngine.SceneManagement.SceneManager.SetActiveScene(previous);AssetDatabase.SaveAssets();}
    }
}
#endif
