#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Doppel6.Probe;
public static class ProbeSetup {
    const string Folder="Assets/Doppel6EngineProbe";
    public static string Setup(string repository) {
        var modelPath=Folder+"/Art/football-v130.fbx";var importer=(ModelImporter)AssetImporter.GetAtPath(modelPath);importer.animationType=ModelImporterAnimationType.Generic;importer.animationCompression=ModelImporterAnimationCompression.Off;importer.importAnimation=true;importer.optimizeGameObjects=false;importer.addCollider=false;importer.globalScale=1;importer.SaveAndReimport();
        foreach(var name in new[]{"image-0.png","image-1.jpg","image-3.png"}) {var t=(TextureImporter)AssetImporter.GetAtPath(Folder+"/Art/textures/"+name);t.maxTextureSize=name=="image-0.png"?4096:2048;t.textureCompression=TextureImporterCompression.Uncompressed;t.sRGBTexture=name=="image-0.png";if(name=="image-3.png")t.textureType=TextureImporterType.NormalMap;if(name=="image-1.jpg")t.isReadable=true;t.SaveAndReimport();}
        var mr=AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"/Art/textures/image-1.jpg");var pixels=mr.GetPixels();for(int i=0;i<pixels.Length;i++)pixels[i]=new Color(pixels[i].b,0,0,1-pixels[i].g);var packed=new Texture2D(mr.width,mr.height,TextureFormat.RGBA32,false,true);packed.SetPixels(pixels);packed.Apply();var packedPath=Folder+"/Art/textures/metallic-smoothness.png";File.WriteAllBytes(packedPath,packed.EncodeToPNG());UnityEngine.Object.DestroyImmediate(packed);AssetDatabase.ImportAsset(packedPath);var pi=(TextureImporter)AssetImporter.GetAtPath(packedPath);pi.sRGBTexture=false;pi.textureCompression=TextureImporterCompression.Uncompressed;pi.SaveAndReimport();
        var materialPath=Folder+"/Art/Player.mat";var material=AssetDatabase.LoadAssetAtPath<Material>(materialPath);if(material==null){material=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(material,materialPath);}material.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"/Art/textures/image-0.png"));material.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"/Art/textures/image-3.png"));material.SetTexture("_MetallicGlossMap",AssetDatabase.LoadAssetAtPath<Texture2D>(packedPath));material.SetFloat("_Smoothness",1);material.SetFloat("_Metallic",1);material.SetFloat("_Cull",0);material.EnableKeyword("_NORMALMAP");material.EnableKeyword("_METALLICSPECGLOSSMAP");EditorUtility.SetDirty(material);
        var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(modelPath);var clips=AssetDatabase.LoadAllAssetsAtPath(modelPath).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview__")).ToArray();
        AnimationClip Clip(string name){return clips.First(c=>c.name==name||c.name.EndsWith("|"+name));}
        Directory.CreateDirectory(Folder+"/Data");var all=File.ReadAllText(Path.Combine(repository,"work/match-next/contacts/catalog.json"));var catalogue=JsonUtility.FromJson<Catalogue>("{\"cases\":"+all+"}");var config=new Config{scenario=catalogue.cases.First(s=>s.provenance.family=="keeper-reachable"),seed=617};File.WriteAllText(Folder+"/Data/default.json",JsonUtility.ToJson(config));AssetDatabase.ImportAsset(Folder+"/Data/default.json");
        var previous=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Additive);UnityEngine.SceneManagement.SceneManager.SetActiveScene(scene);
        try {RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=Color.white;RenderSettings.ambientIntensity=2;
            var cameraObject=new GameObject("TV Camera");var camera=cameraObject.AddComponent<Camera>();cameraObject.tag="MainCamera";camera.transform.position=new Vector3(0,48,-55);camera.transform.LookAt(Vector3.zero);camera.fieldOfView=50;camera.nearClipPlane=.1f;camera.farClipPlane=200;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(20/255f,41/255f,45/255f);camera.allowMSAA=false;
            var light=new GameObject("Sun").AddComponent<Light>();light.type=LightType.Directional;light.intensity=2;light.shadows=LightShadows.None;light.transform.rotation=Quaternion.Euler(50,-30,0);
            var bridge=new GameObject("ProbeBridge").AddComponent<ProbeBridge>();bridge.playerPrefab=prefab;bridge.playerMaterial=material;bridge.idleClip=Clip("idle_stand_meshy");bridge.runClip=Clip("running");bridge.keeperClip=Clip("keeper_ready_meshy");bridge.keeperActionClip=Clip("keeper_low_meshy");bridge.shotClip=Clip("shot_meshy");bridge.defaultScenario=AssetDatabase.LoadAssetAtPath<TextAsset>(Folder+"/Data/default.json");EditorSceneManager.SaveScene(scene,Folder+"/Probe.unity");
        }finally{EditorSceneManager.CloseScene(scene,true);UnityEngine.SceneManagement.SceneManager.SetActiveScene(previous);}
        AssetDatabase.SaveAssets();var smr=prefab.GetComponentInChildren<SkinnedMeshRenderer>();var report=new ImportReport{unity=Application.unityVersion,clips=clips.Select(c=>c.name).ToArray(),bones=smr.bones.Length,vertices=smr.sharedMesh.vertexCount,triangles=smr.sharedMesh.triangles.Length/3,boundsSize=smr.sharedMesh.bounds.size,rootScale=prefab.transform.localScale};File.WriteAllText(Path.Combine(repository,"prototypes/match-engine-unity/import-validation.json"),JsonUtility.ToJson(report,true));return JsonUtility.ToJson(report);
    }
    [Serializable] class ImportReport {public string unity;public string[] clips;public int bones,vertices,triangles;public Vector3 boundsSize,rootScale;}
    [Serializable] class Expected {public string type,actorId,reason;public bool allowed,whistle;}
    [Serializable] class TestScenario : Scenario {public Expected expected;}
    [Serializable] class Catalogue {public TestScenario[] cases;}
    [Serializable] class TestResult {public string id,observed,actorId;public bool passed,checkpointPassed,pausePassed,uniqueResult;public string[] events;}
    [Serializable] class NegativeReport {public bool outsideParryRejected,restrictedParryRejected,foreignCheckpointRejected,foreignSourceRejected,malformedCheckpointsRejected,restoreFailureAtomic;}
    [Serializable] class TestReport {public int total,passed,checkpoints;public TestResult[] cases;public NegativeReport negativeCases;}
    [Serializable] class TransportReport {public string fixture,fixtureSourceId,testSourceId;public int checkpointTick,restoredTick;public bool rawPayloadRestored,missingRejected,corruptRejected,failuresAtomic;}
    public static string TransportTest(string repository,string fixture) {
        var raw=File.ReadAllText(Path.Combine(repository,fixture));var original=JsonUtility.FromJson<Checkpoint>(raw);var originalSource=original.sourceId;
        // The captured pre-fix payload belongs to the previous build: update only its source stamp.
        raw=raw.Replace(originalSource,ProbeBuildIdentity.SourceId);
        string Command(string checkpoint){return "{\"id\":\"transport-test\",\"command\":\"restore\",\"config\":{\"checkpoint\":"+checkpoint+"}}";}
        var saved=ProbeBridge.ReadRestoreCheckpoint(Command(raw));var sim=new ProbeSimulation(saved.config);sim.Start();for(int i=0;i<25;i++)sim.Step();sim.Pause();sim.Restore(saved);var before=JsonUtility.ToJson(sim.State);bool atomic=true;
        bool Rejected(string command){try{sim.Restore(ProbeBridge.ReadRestoreCheckpoint(command));return false;}catch(ArgumentException){atomic&=before==JsonUtility.ToJson(sim.State);return true;}}
        var missing=Rejected("{\"command\":\"restore\",\"config\":{}}");var bad=JsonUtility.FromJson<Checkpoint>(raw);bad.state.ball.velocity=null;var corrupt=Rejected(Command(JsonUtility.ToJson(bad)));
        var report=new TransportReport{fixture=fixture,fixtureSourceId=originalSource,testSourceId=ProbeBuildIdentity.SourceId,checkpointTick=saved.state.tick,restoredTick=sim.State.tick,rawPayloadRestored=sim.State.tick==saved.state.tick&&sim.State.ball.position.SequenceEqual(saved.state.ball.position),missingRejected=missing,corruptRejected=corrupt,failuresAtomic=atomic};var json=JsonUtility.ToJson(report,true);File.WriteAllText(Path.Combine(repository,"prototypes/match-engine-unity/transport-regression.json"),json);return json;
    }
    public static string SelfTest(string repository) {
        var all=File.ReadAllText(Path.Combine(repository,"work/match-next/contacts/catalog.json"));var cases=JsonUtility.FromJson<Catalogue>("{\"cases\":"+all+"}").cases;var results=new List<TestResult>();
        foreach(var scenario in cases){var sim=new ProbeSimulation(new Config{scenario=scenario,seed=617});sim.Start();for(int i=0;i<12;i++)sim.Step();sim.Pause();var paused=JsonUtility.ToJson(sim.State);sim.Step();bool pausePassed=paused==JsonUtility.ToJson(sim.State);sim.Start();var cp=sim.Checkpoint();var restore=new ProbeSimulation(sim.Config);restore.Restore(ProbeBridge.ReadRestoreCheckpoint("{\"id\":\"selftest\",\"command\":\"restore\",\"config\":{\"checkpoint\":"+JsonUtility.ToJson(cp)+"}}"));restore.Start();while(!sim.State.finished)sim.Step();while(!restore.State.finished)restore.Step();var st=sim.State;var rs=restore.State;bool Near(double a,double b){return Math.Abs(a-b)<1e-8;}var checkpointPassed=st.scenarioId==rs.scenarioId&&st.tick==rs.tick&&Near(st.elapsed,rs.elapsed)&&st.score.SequenceEqual(rs.score)&&st.events.Count==rs.events.Count&&st.events.Zip(rs.events,(a,b)=>a.type==b.type&&a.id==b.id&&(a.actorId??"")==(b.actorId??"")&&Near(a.time,b.time)).All(x=>x)&&st.ball.position.Zip(rs.ball.position,Near).All(x=>x)&&st.actors.Zip(rs.actors,(a,b)=>a.id==b.id&&a.position.Zip(b.position,Near).All(x=>x)).All(x=>x);var contact=st.events.FirstOrDefault(e=>e.type=="contact");string observed=contact!=null?"contact":st.events.Any(e=>e.type=="goal")?"goal":st.events.Any(e=>e.type=="out")?"out":"free";bool passed;
            if(scenario.kind=="keeper-permission"){var e=st.events.First(e=>e.type=="keeper-permission");observed=e.reason;passed=e.allowed==scenario.expected.allowed&&e.reason==scenario.expected.reason;}
            else if(scenario.kind=="offside"){var e=st.events.First(e=>e.type=="offside-check");observed=e.whistle?"offside":"no-whistle";passed=e.whistle==scenario.expected.whistle;}
            else passed=observed==scenario.expected.type&&(string.IsNullOrEmpty(scenario.expected.actorId)||scenario.expected.actorId==contact?.actorId);
            results.Add(new TestResult{id=scenario.id,observed=observed,actorId=contact?.actorId,passed=passed,checkpointPassed=checkpointPassed,pausePassed=pausePassed,uniqueResult=st.events.Count(e=>e.type=="result")==1&&st.events.Select(e=>e.id).Distinct().Count()==st.events.Count,events=st.events.Select(e=>e.type).ToArray()});
        }
        bool IllegalParry(bool outside){var scenario=JsonUtility.FromJson<Scenario>(JsonUtility.ToJson(cases.First(s=>s.provenance.family=="keeper-reachable")));scenario.actors=scenario.actors.Where(a=>a.id=="keeper").ToArray();var keeper=scenario.actors[0];keeper.action="parry";scenario.ball.position=new[]{outside?-22.0:-31.0,.29,0.0};keeper.position=(double[])scenario.ball.position.Clone();scenario.provenance.sourceTeam=keeper.team;scenario.provenance.sourceAction=outside?"opponent-shot":"deliberate-foot-pass";var sim=new ProbeSimulation(new Config{scenario=scenario});sim.Start();sim.Step();return sim.State.events.Any(e=>e.type=="hand-contact-disallowed"&&e.reason==(outside?"outside-own-box":"restricted-origin"))&&!sim.State.events.Any(e=>e.type=="parry"||e.type=="possession"||e.type=="free-ball");}
        bool foreign=false;var identitySim=new ProbeSimulation(new Config{scenario=cases[0]});var foreignCp=identitySim.Checkpoint();foreignCp.engine="browser";try{identitySim.Restore(foreignCp);}catch(ArgumentException){foreign=true;}
        bool foreignSource=false;foreignCp=identitySim.Checkpoint();foreignCp.sourceId="other-source";try{identitySim.Restore(foreignCp);}catch(ArgumentException){foreignSource=true;}
        bool malformed=true,atomic=true;identitySim.Start();identitySim.Step();var before=JsonUtility.ToJson(identitySim.State);foreach(var mutation in new Action<Checkpoint>[]{c=>c.state.ball.velocity=null,c=>c.state.elapsed=-1,c=>c.state.actors[0].id="foreign",c=>c.state.events.Add(c.state.events[0])}){var bad=identitySim.Checkpoint();mutation(bad);bool rejected=false;try{identitySim.Restore(bad);}catch(ArgumentException){rejected=true;}malformed&=rejected;atomic&=before==JsonUtility.ToJson(identitySim.State);}
        var report=new TestReport{total=results.Count,passed=results.Count(r=>r.passed),checkpoints=results.Count(r=>r.checkpointPassed),cases=results.ToArray(),negativeCases=new NegativeReport{outsideParryRejected=IllegalParry(true),restrictedParryRejected=IllegalParry(false),foreignCheckpointRejected=foreign,foreignSourceRejected=foreignSource,malformedCheckpointsRejected=malformed,restoreFailureAtomic=atomic}};File.WriteAllText(Path.Combine(repository,"prototypes/match-engine-unity/selftest.json"),JsonUtility.ToJson(report,true));return JsonUtility.ToJson(report);
    }
}
#endif

