'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const base=path.resolve(__dirname,'../../../..'),runtime='C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node';
if(Number(process.versions.node.split('.')[0])<20){const run=require('node:child_process').spawnSync(path.join(runtime,'bin/node.exe'),[__filename],{stdio:'inherit'});process.exit(run.status??1);}
const {chromium}=require(path.join(runtime,'node_modules/playwright')),{createServer}=require('../../serve.cjs');
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const hashes=()=>({source:Object.fromEntries(fs.readdirSync(path.join(base,'dist'),{recursive:true}).filter(f=>/\.(js|css|html)$/.test(f)).sort().map(f=>[f,sha(path.join(base,'dist',f))])),build:sha(path.join(base,'outputs/index.html'))});
(async()=>{
 const before=hashes(),out=path.join(base,'outputs/ui-redesign/I00-market-check',new Date().toISOString().replace(/[:.]/g,'-'));fs.mkdirSync(out,{recursive:true});
 const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const results=[];let stage='launch';
 try{
  browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
  for(const target of ['source','build']){
   stage=`${target}:setup`;const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
   const url=target==='source'?`http://127.0.0.1:${server.address().port}/source/index.html`:pathToFileURL(path.join(base,'outputs/index.html')).href;
   await page.goto(url);await page.waitForFunction(()=>typeof v61CreateCareer==='function');
   const setup=await page.evaluate(async()=>{
    const career=v61CreateCareer('GER-2','u01-market-dom-proof','Vertragsprüfung'),own=v66Own(career);
    v66ChooseSponsor(career,own.id,own.sponsors[0].id);v124SetYouthBudget(career,0);
    const player=own.roster.filter(p=>v66Contract(career,p.pid)?.endSeason===career.world.season).sort((a,b)=>v66Salary(b)-v66Salary(a))[0];if(!player||v66Salary(player)<=60)throw Error('No suitable native expiring contract');
    v61CurrentCareer=await v61StoreNewCareer(career);v61RenderCareer(career);v61SetCareerTab('squad',false);
    return{id:career.id,pid:player.pid,season:career.world.season,promotionPid:own.youthPool.find(p=>!p.keeper).pid,releasePid:own.youthPool.find(p=>p.keeper).pid};
   });
   const renewOpen=()=>page.locator(`[data-v66-renew-open="${setup.pid}"]`),submit=()=>page.locator('[data-v66-renew-submit]');
   async function reload(){await page.reload();await page.waitForFunction(()=>typeof v61OpenCareer==='function');await page.evaluate(async id=>{await v61OpenCareer(id);v61SetCareerTab('squad',false);},setup.id);await page.locator('[data-v46-view="squad"]:not([hidden])').waitFor();}
   stage=`${target}:renew invalid/counter`;
   await renewOpen().click();await page.locator('#v66-renew-salary').fill('59');await submit().click();await page.waitForFunction(()=>document.querySelector('#v66-renew-dialog .v72-dialog-error')?.textContent.includes('ungültig'));
   assert.equal(await page.evaluate(pid=>v66Contract(v61CurrentCareer,pid).renewalOffers,setup.pid),0);checks.push('Q-MKT03: invalid salary rejected through native submit without contract mutation');
   await page.locator('#v66-renew-salary').fill('60');await submit().click();await page.waitForFunction(pid=>v66Contract(v61CurrentCareer,pid).renewalNegotiation?.history.length===1,setup.pid);await page.locator('[data-v66-renew-submit]').waitFor();
   await page.locator('#v66-renew-salary').fill('60');await submit().click();await page.waitForFunction(pid=>v66Contract(v61CurrentCareer,pid).renewalNegotiation?.history.length===2,setup.pid);await page.waitForFunction(()=>!document.querySelector('[data-v66-renew-submit]'));
   assert.match(await page.locator('#v66-renew-dialog').textContent(),/nächste Verhandlungsrunde öffnet/);await page.screenshot({path:path.join(out,`${target}-renew-blocked.png`),animations:'disabled'});checks.push('Q-MKT03: two real counteroffers; exhausted initial window removes submit and explains reopening');
   await page.locator('[data-v66-renew-close]').click();await reload();assert.equal(await page.evaluate(pid=>v66Contract(v61CurrentCareer,pid).renewalNegotiation.history.length,setup.pid),2);await renewOpen().click();assert.equal(await submit().count(),0);await page.locator('[data-v66-renew-close]').click();checks.push('Q-MKT03: saved counter history and window block survive browser reload');
   stage=`${target}:renew reopened accepted`;
   const annual=await page.evaluate(pid=>{const c=v61CurrentCareer,next=v66Contract(c,pid).renewalNextDay;for(let i=0;i<6&&c.world.market.phase!=='closed';i++)v66NextMarketDay(c);for(let i=0;i<30&&c.world.calendarCursor<next;i++)v62AdvanceDay(c);if(!v66RenewalWindow(c,v66Contract(c,pid)).canOffer)throw Error('Native calendar did not reopen negotiation');v61RenderCareer(c);v61SetCareerTab('squad',false);return Math.ceil(v66Salary(v66Player(c,pid))*2/10)*10;},setup.pid);
   await renewOpen().click();await page.locator('#v66-renew-salary').fill(String(annual));await page.locator('#v66-renew-years').selectOption('3');await submit().click();await page.waitForFunction(pid=>v66Contract(v61CurrentCareer,pid).endSeason===v61CurrentCareer.world.season+2,setup.pid);await page.waitForFunction(()=>!document.querySelector('#v66-renew-dialog')?.open);
   let renewed=await page.evaluate(pid=>{const c=v61CurrentCareer,own=v66Own(c),contract=v66Contract(c,pid);return{end:contract.endSeason,annual:contract.annual,ledger:own.ledger.filter(x=>x.id.includes(pid+':renewal:')).length,negotiation:!!contract.renewalNegotiation};},setup.pid);assert.equal(renewed.annual,annual);assert.equal(renewed.ledger,1);assert.equal(renewed.negotiation,false);await reload();assert.equal(await renewOpen().count(),0);assert.equal(await page.evaluate(pid=>v66Own(v61CurrentCareer).ledger.filter(x=>x.id.includes(pid+':renewal:')).length,setup.pid),1);checks.push('Q-MKT03: native calendar reopens window, DOM submit renews three years, exactly one ledger event survives reload; renewed player cannot renew again');
   stage=`${target}:youth disabled`;
   const youthBefore=await page.evaluate(async()=>{const c=v61CurrentCareer,club=v66Own(c),before={balance:club.balance,roster:club.roster.length,pool:club.youthPool.length};v66Book(c,club.id,'test:blocked-youth-fixture',-club.balance,'Isolated test fixture: insufficient balance');v61RenderCareer(c);v61SetCareerTab('squad',false);return before;});
   const promote=()=>page.locator(`[data-v67-promote="${setup.promotionPid}"]`),release=()=>page.locator(`[data-v67-release="${setup.releasePid}"]`);
   assert.equal(await promote().isDisabled(),true);checks.push('Q-MKT04: insufficient balance disables native youth promotion action');
   await page.evaluate(balance=>{const c=v61CurrentCareer,club=v66Own(c);v66Book(c,club.id,'test:restored-youth-fixture',balance,'Isolated test fixture: restore balance');v61RenderCareer(c);v61SetCareerTab('squad',false);},youthBefore.balance);
   stage=`${target}:youth promotion`;
   const fee=await page.evaluate(pid=>v67Fee(v66Own(v61CurrentCareer).youthPool.find(p=>p.pid===pid)),setup.promotionPid);assert.equal(await promote().isDisabled(),false);
   await promote().evaluate(button=>{button.click();button.click();});await page.locator('.v67-promote-dialog[open]').waitFor();assert.match(await page.locator('.v67-promote-dialog').textContent(),/Neu im Profikader/);await page.locator('[data-v67-promote-close]').last().click();
   const promoted=await page.evaluate(pid=>{const c=v61CurrentCareer,club=v66Own(c);return{roster:club.roster.length,pool:club.youthPool.length,count:club.roster.filter(p=>p.pid===pid).length,ledger:club.ledger.filter(e=>e.id.endsWith(pid+':youth-promotion')).map(e=>e.amount),balance:club.balance,contracts:c.world.contracts.filter(e=>e.pid===pid).length};},setup.promotionPid);
   assert.equal(promoted.roster,youthBefore.roster+1);assert.equal(promoted.pool,youthBefore.pool-1);assert.equal(promoted.count,1);assert.deepEqual(promoted.ledger,[-fee]);assert.equal(promoted.balance,youthBefore.balance-fee);assert.equal(promoted.contracts,1);checks.push('Q-MKT04: double DOM promotion click books one training fee, one player and one contract; native success dialog closes');
   stage=`${target}:youth release cancel/confirm`;
   const beforeCancel=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));page.once('dialog',dialog=>dialog.dismiss());await release().click();assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),beforeCancel);checks.push('Q-MKT04: native release confirmation cancel leaves full career unchanged');
   const beforeRelease=await page.evaluate(()=>({balance:v66Own(v61CurrentCareer).balance,ledger:v66Own(v61CurrentCareer).ledger.length}));page.once('dialog',dialog=>dialog.accept());await release().click();await page.waitForFunction(pid=>!v66Own(v61CurrentCareer).youthPool.some(p=>p.pid===pid),setup.releasePid);await page.waitForFunction(()=>!v67Busy);
   const released=await page.evaluate(pid=>{const c=v61CurrentCareer,club=v66Own(c);return{free:c.world.market.freePlayers.filter(p=>p.pid===pid).length,transfers:c.world.transfers.filter(t=>t.id.endsWith(pid+':youth-release')).length,balance:club.balance,ledger:club.ledger.length};},setup.releasePid);
   assert.equal(released.free,1);assert.equal(released.transfers,1);assert.equal(released.balance,beforeRelease.balance);assert.equal(released.ledger,beforeRelease.ledger);await reload();assert.equal(await promote().count(),0);assert.equal(await release().count(),0);assert.equal(await page.evaluate(pid=>v66Own(v61CurrentCareer).ledger.filter(e=>e.id.endsWith(pid+':youth-promotion')).length,setup.promotionPid),1);assert.equal(await page.evaluate(pid=>v61CurrentCareer.world.market.freePlayers.filter(p=>p.pid===pid).length,setup.releasePid),1);checks.push('Q-MKT04: accepted release adds one free player/transfer, no fee; promotion and release persist after reload with no repeat action');
   await page.screenshot({path:path.join(out,`${target}-youth-after-reload.png`),fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);results.push({target,checks,renewed,promoted,released,errors});console.log(`${target}: ${checks.length} checks passed`);await context.close();
  }
  assert.deepEqual(hashes(),before,'frozen source or offline build changed during run');fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({results,hashes:before,scope:'Tests only; isolated fresh browser contexts. Initial career and calendar advanced by native controllers. Balance block uses two explicitly labelled isolated fixture ledger entries; tested actions use existing DOM controls.'},null,2));console.log(out);
 }catch(error){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({stage,error:error.stack,completed:results,hashesBefore:before,hashesAfter:hashes()},null,2));throw new Error(`${stage}: ${error.message}`);}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(error=>{console.error(error);process.exitCode=1;});
