'use strict';
const translations={'Spielbericht':'Match report','Spielbericht schließen':'Close match report','Nicht erfasst':'Not recorded','Keine Ereignisse':'No events','Keine Wechsel':'No substitutions','Aufstellungen':'Line-ups','Spielerstatistik':'Player statistics','Spielereignisse':'Match events','Teamstatistik':'Team statistics','Auszeichnungen':'Awards','Spielerwechsel':'Substitutions','Keine Aufstellung erfasst':'No line-up recorded','Keine Spielerwerte erfasst':'No player statistics recorded','Keine Auszeichnungen':'No awards','Zurück':'Back','S':'W','U':'D','N':'L','Tore':'Goals'};
function fixture(lang='de',kind='full'){
 const en=lang==='en',clubs=Array.from({length:6},(_,i)=>({clubId:'club-'+i,wins:i+1,draws:2,losses:3,goalsFor:10+i,goalsAgainst:8}));
 const table=`<div class="v62-table-wrap" tabindex="0" role="region" aria-label="Ligatabelle"><table class="v62-table" data-fl-competition-id="league"><thead><tr><th>Pl.</th><th>${en?'Club':'Verein'}</th><th>Sp.</th><th>TD</th><th>Pkt.</th></tr></thead><tbody>${clubs.map((c,i)=>`<tr${i===1?' class="own"':''}><td>${i+1}</td><td><span class="v68-table-club"><button class="v68-club-link" data-v68-club="${c.clubId}">${en?'Football Club With A Long Name':'Fußballclub mit einem langen Namen'} ${i+1}</button></span></td><td>6</td><td>2</td><td>8</td></tr>`).join('')}</tbody></table></div>`;
 const result=`<div class="v62-fixture" data-fl-fixture-id="game-1"><span>08.09. · SF</span><div class="v68-result"><button class="v68-club-link" data-v68-club="club-0">FC Test</button><b>2:1<small> i. E. 4:3</small></b><button class="v68-club-link" data-v68-club="club-1">United Test</button></div></div>`;
 const player={id:'player-1',name:en?'Player With A Long Name':'Spieler mit einem langen Namen'};
 const report={id:'game-1',title:en?'Match report':'Spielbericht',contextLabel:en?'Season 4 · Cup semi-final':'Saison 4 · Pokalhalbfinale',home:{id:'club-0',name:'FC Test'},away:{id:'club-1',name:'United Test'},scoreLabel:'2 : 1',penaltiesLabel:'i. E. 4 : 3',teamStats:kind==='full'?[{label:en?'Shots':'Schüsse',home:'8',away:'5'}]:null,events:kind==='full'?[{minuteLabel:'23′',text:en?'Goal, Player With A Long Name':'Tor, Spieler mit einem langen Namen'}]:null,lineups:{home:[player],away:[{id:'player-2',name:'Alex Test'}]},substitutions:kind==='empty'?[]:[{minuteLabel:'45′',teamLabel:'FC Test',out:player,in:{id:'player-3',name:'Jamie Test'}}],players:kind==='full'?[{...player,teamLabel:'FC Test',stats:[{label:en?'Minutes':'Minuten',value:'45'},{label:en?'Goals':'Tore',value:'1'},{label:en?'Rating':'Note',value:null}]}]:null,awards:kind==='full'?[{kind:'man-of-the-match',label:'Man of the Match',playerId:player.id}]:null};
 return{translations:en?translations:{},report,competitions:{tables:[{id:'league',rows:clubs}],report:null},html:`<div data-v46-view="overview"><div class="v62-competitions"><details open><summary>Liga</summary>${table}</details></div></div><div data-v46-view="competition"><section class="v62-season"><div class="v62-competition-heading"><h2>${en?'Competitions':'Wettbewerbe'}</h2><label>${en?'Season':'Saison'}<select data-v62-season-choice><option>4</option><option>3</option></select></label></div><div class="v62-competition-tabs"><button data-v62-area="own" aria-selected="true">${en?'Your competitions':'Deine Wettbewerbe'}</button><button data-v62-area="other">${en?'Other countries':'Andere Länder'}</button></div><div class="v62-competitions"><details open><summary>Liga</summary>${table}</details><details class="v62-cup-details" open><summary>${en?'National cup':'Nationaler Pokal'}</summary><div data-v62-cup-bracket><div class="v62-cup-slide-controls"><button data-v62-cup-slide="-1">‹</button><span>${en?'Semi-final':'Halbfinale'}</span><button data-v62-cup-slide="1">›</button></div>${result}<p class="v62-cup-pending">${en?'Pairing pending':'Paarung folgt'}</p></div></details></div><details class="v68-archive"><summary>${en?'Title archive':'Titelarchiv'}</summary><p>Season 3 · FC Test</p></details></section></div><div data-v46-view="calendar"><section class="v62-season"><h2>${en?'Calendar':'Kalender'}</h2><ol class="v62-calendar-list"><li class="played" data-fl-fixture-id="game-1"><time>08.09.</time><span class="v62-calendar-competition">Pokal <small>SF</small></span><strong class="v62-calendar-opponent"><button data-v68-club="club-1">United Test</button><small>${en?'Away':'Auswärts'}</small></strong><b class="v62-calendar-result">2:1<small>i. E. 4:3</small></b></li></ol></section></div><div data-v46-view="statistics"><section class="v62-season v62-stat-board"><h2>${en?'Statistics':'Statistik'}</h2>${['Tore','Assists','Zu null','Fouls','Elfmeter verwandelt','Elfmeter verschossen'].map(label=>`<details class="v46-stat-category" open><summary>${label}</summary><p>${en?'No entries':'Keine Einträge'}</p></details>`).join('')}</section></div>`};
}
module.exports={fixture};
