'use strict';
// Independent Q01 integration checks. Direct controller calls below are explicitly setup only.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),runtime=path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node');
if(Number(process.versions.node.split('.')[0])<20){const run=require('node:child_process').spawnSync(path.join(runtime,'bin/node.exe'),[__filename,...process.argv.slice(2)],{stdio:'inherit'});process.exit(run.status??1);}
const {chromium}=require(path.join(runtime,'node_modules/playwright')),{createServer}=require('../serve.cjs');
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const target=option('--target','source'),mode=option('--mode','quick'),build=path.resolve(root,option('--build','outputs/index.html'));
assert(['source','build'].includes(target));assert(['quick','layout','finance','supplement','all'].includes(mode));
const runId=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(root,'outputs/ui-redesign/Q01',runId,target);fs.mkdirSync(out,{recursive:true});
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const hashes=()=>Object.fromEntries([...fs.readdirSync(path.join(root,'dist'),{recursive:true}).filter(f=>/\.(js|css|html|svg|json)$/.test(f)).map(f=>'dist/'+f),'docs/ui-redesign/contracts.md','docs/ui-redesign/inventory.md',...(target==='build'?[path.relative(root,build)]:[])].filter(f=>fs.existsSync(path.join(root,f))).sort().map(f=>[f,hash(path.join(root,f))]));
const records=[],errors=[],network=[];let browser,server,page,context,url;
const before=hashes();
async function check(id,name,fn){try{const detail=await fn();records.push({id,name,status:'bestanden',detail});console.log('PASS '+name);}catch(error){records.push({id,name,status:'fehlgeschlagen',error:String(error.stack||error)});console.log('FAIL '+name+': '+error.message);if(page)await page.screenshot({path:path.join(out,'failure-'+records.length+'.png'),fullPage:true}).catch(()=>{});if(page)await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close())).catch(()=>{});}}
async function ready(){await page.waitForFunction(()=>!!window.D6Flutlicht?.adapter&&v61StorageReady);}
async function settle(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function newCareer(seed='q01-independent'){await page.goto(url);await ready();await page.evaluate(async seed=>{v61CurrentCareer=await v61StoreNewCareer(v61CreateCareer('GER-2',seed,'Q01 Testmanager'));v61CareerTab='overview';v61RenderCareer(v61CurrentCareer);},seed);await page.locator('.fl-shell').waitFor();await settle();}
async function navigate(route){const direct=page.locator(`[data-fl-route="${route}"]:visible`).first();if(!await direct.count()){await page.locator('[data-fl-menu]:visible').click();}await page.locator(`[data-fl-route="${route}"]:visible`).first().click();await settle();assert.equal(await page.evaluate(()=>v61CareerTab),route);}
async function state(){return page.evaluate(()=>{const c=v61CurrentCareer,b=v66Own(c);return {id:c.id,season:c.world.season,phase:c.world.market.phase,sponsor:b.sponsorId,balance:b.balance,ledger:b.ledger.map(r=>({id:r.id,amount:r.amount,season:r.season})),roster:b.roster.map(p=>p.pid)}});}
async function reloadCareer(id){await page.reload();await ready();await page.locator(`[data-v61-open="${id}"]`).click();await page.locator('.fl-shell').waitFor();await settle();}
function keys(value,allowed,label){assert(value&&typeof value==='object'&&!Array.isArray(value),label+' object');assert.deepEqual(Object.keys(value).filter(key=>!allowed.includes(key)),[],label+' unknown fields');}
function validateProjection(p){
 require('./projection-schema.cjs').validate(p);
 keys(p,['frame','navigation','players','overview','club','competitions','settings'],'projection');
 keys(p.frame,['clubName','clubMeta','clubCrestHTML','managerLabel','titles','navigation','activeRoute','leadAction','themePreference','labels','language'],'frame');
 keys(p.players,['season','ownClubId','roster','all'],'players');
 const bands=['violetgray','bluegray','yellow','orange','pink','unknown'];
 for(const row of [...p.players.roster,...p.players.all]){
  keys(row,['id','name','number','nationCode','nationLabel','positionCode','positionLabel','age','skills','form','freshness','stats'],'player');
  for(const skill of row.skills){keys(skill,['key','label','band','colorLabel'],'skill');assert(bands.includes(skill.band));for(const value of Object.values(skill))assert.equal(typeof value,'string','skills only qualitative strings');}
  keys(row.form,['band','label'],'form');keys(row.freshness,['percent','band','label'],'freshness');keys(row.stats,['appearances','substitutions','goals','assists','averageRating','ratedGames','substitutionCoverage'],'stats');
 }
 const walk=(v,at='projection')=>{if(!v||typeof v!=='object')return;for(const [key,value]of Object.entries(v)){assert(!/^(talent|potential|developmentPoints|growthPoints|rawPlayer|career|skillValue|abilityValue)$/i.test(key),at+'.'+key+' is private');walk(value,at+'.'+key)}};walk(p);
 if(p.overview.fixture){keys(p.overview.fixture,['dateLabel','seasonLabel','competitionLabel','roundLabel','home','away'],'fixture');for(const team of [p.overview.fixture.home,p.overview.fixture.away]){keys(team,['id','name','crestHTML','rankLabel','recent'],'team');for(const recent of team.recent)keys(recent,['outcome','label','detail'],'recent');}}
 return {players:p.players.all.length,skills:p.players.all.reduce((n,p)=>n+p.skills.length,0),clubSchema:'v1.2 recursive whitelist',competitionsSchema:'v1.2 recursive whitelist'};
}
async function leakSnapshot(name){const dom=await page.evaluate(()=>{const skill=[...document.querySelectorAll('.fl-skill,.v55-skill-row,.v55-roster-skills>[role=listitem],.v55-skill-list>[role=listitem]')];const values=skill.map(n=>({text:n.textContent,html:n.outerHTML,aria:n.getAttribute('aria-label')}));const suspect=[...document.querySelectorAll('body *')].flatMap(n=>[...n.attributes].filter(a=>/^(data-.*(talent|development|potential|skill-value)|aria-valuenow)$/i.test(a.name)&&n.closest('.fl-skill,.v55-skill,[data-fl-player-id]')).map(a=>({tag:n.tagName,attribute:a.name,value:a.value})));return {values,suspect};});const session=await context.newCDPSession(page);const ax=await session.send('Accessibility.getFullAXTree');await session.detach();fs.writeFileSync(path.join(out,name+'-dom.json'),JSON.stringify(dom,null,2));fs.writeFileSync(path.join(out,name+'-ax.json'),JSON.stringify(ax,null,2));assert.deepEqual(dom.suspect,[]);assert(dom.values.length>0);for(const row of dom.values){assert(!/\d/.test(row.aria||''),'numeric skill aria '+row.aria);assert(!/\d/.test(row.text),'numeric skill text '+row.text);}return {skillNodes:dom.values.length,axNodes:ax.nodes.length,scope:'numeric skill text/aria and private attribute audit; AX captured for review'};}
async function quick(){
 await newCareer();
 await check('Q-DATA-01/03','projection strict player whitelist and repeated projection purity',async()=>{const value=await page.evaluate(()=>{const before=JSON.stringify(v61CurrentCareer),p=D6Flutlicht.adapter.project(v61CurrentCareer);for(let i=0;i<4;i++)D6Flutlicht.adapter.project(v61CurrentCareer);return {p,unchanged:before===JSON.stringify(v61CurrentCareer)}});assert(value.unchanged,'project() changed career');return validateProjection(value.p);});
 await check('Q-LOAD-02','shell update/unmount removes stale handlers',async()=>page.evaluate(()=>{const projection=D6Flutlicht.adapter.project(v61CurrentCareer).frame,root=document.createElement('div');document.body.append(root);let calls=0;const a={navigate:()=>calls++};const first=D6Flutlicht.shell.mount(root,projection,a),old=root.querySelector('[data-fl-route]');first.update(projection);old.click();if(calls!==1)throw Error('normal navigation count '+calls);first.unmount();old.click();if(calls!==1)throw Error('stale handler fired');const second=D6Flutlicht.shell.mount(root,projection,a);root.querySelector('[data-fl-route]').click();if(calls!==2)throw Error('remount duplicated handler');second.unmount();root.remove();return {normalCalls:2,staleCalls:0};}));
 await check('Q-PHASE-01/04','real sponsor action once, save and reload',async()=>{const button=page.locator('[data-v66-sponsor]').first(),sponsor=await button.getAttribute('data-v66-sponsor');await button.evaluate(n=>{n.click();n.click()});await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.market.phase==='budget');await page.evaluate(()=>v61WaitForStorage());const first=await state();assert.equal(first.sponsor,sponsor);assert.equal(first.ledger.filter(r=>r.id===sponsor+':fixed').length,1,'one sponsor fixed entry');await reloadCareer(first.id);assert.deepEqual(await state(),first);return {sponsor,ledgerEntries:first.ledger.length,saved:true};});
 await check('Q-PHASE-02/04','actual budget DOM action booked once',async()=>{await page.locator('#v67-budget').selectOption('200');await page.locator('[data-v124-budget]').evaluate(n=>{n.click();n.click()});await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.market.phase==='open');await page.evaluate(()=>v61WaitForStorage());const first=await state();const entries=first.ledger.filter(r=>r.id.endsWith(':youth-budget'));assert.equal(entries.length,1);await reloadCareer(first.id);assert.deepEqual(await state(),first);return {budgetEntries:entries};});
 await check('Q-SQ-01/Q-NAV-01','squad filters, profile and return',async()=>{await navigate('squad');await page.locator('[data-fl-squad-search]').fill('ZZZ_no_person');assert(await page.locator('.fl-squad-empty').isVisible());await page.locator('[data-fl-squad-search]').fill('');const first=page.locator('.fl-squad-table [data-v61-player]:visible').first();await first.click();await page.locator('dialog[open][data-fl-player-id]').waitFor();assert(await page.locator('dialog[open] .fl-squad-profile-skills').isVisible());await page.locator('dialog[open] [data-v74-profile-tab="career"]').click();assert(await page.locator('dialog[open] .v64-player-seasons').isVisible());await page.locator('dialog[open] [data-v61-close]').click();assert(await page.locator('[data-fl-squad-search]').isVisible());return {emptyFilter:true,profile:true,career:true};});
 await check('Q-DATA-02','integrated squad DOM and accessibility capture',()=>leakSnapshot('squad'));
 await check('Q-THEME-01/02/Q-DATA-03','theme and language retain career and filter across navigation/reload',async()=>{await navigate('squad');await page.locator('[data-fl-squad-search]').fill('QA_preserved_filter');const before=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));await navigate('settings');await page.locator('[data-fl-theme-preference-control]').selectOption('dark');assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),'dark');await page.emulateMedia({colorScheme:'light'});assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),'dark');await page.locator('[data-fl-settings-language]').selectOption('en');await settle();assert.equal(await page.locator('html').getAttribute('lang'),'en');await navigate('squad');assert.equal(await page.locator('[data-fl-squad-search]').inputValue(),'QA_preserved_filter');assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),before);await page.locator('[data-fl-squad-search]').fill('');const saved=await state();await reloadCareer(saved.id);assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),'dark');await navigate('settings');await page.locator('[data-fl-theme-preference-control]').selectOption('system');await page.emulateMedia({colorScheme:'light'});await settle();assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),'light');await page.emulateMedia({colorScheme:'dark'});await settle();assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),'dark');return {filter:true,careerUnchanged:true,themePersisted:true,systemChanges:true};});
 await check('Q-SET-01','legal dialog actual action and close',async()=>{await navigate('settings');await page.locator('[data-fl-settings-legal="datenschutz"]').click();await page.locator('dialog[open]').waitFor();assert(await page.locator('dialog[open]').innerText());await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);return {openedAndClosed:true};});
 await check('Q-SAVE-01','settings returns to real save list and reopen',async()=>{await navigate('settings');const saved=await state();await page.locator('[data-fl-settings-action="manage"]').click();await page.locator(`[data-v61-open="${saved.id}"]`).waitFor();assert(await page.locator(`[data-v61-export="${saved.id}"]`).isVisible());await page.locator(`[data-v61-open="${saved.id}"]`).click();await settle();assert.deepEqual(await state(),saved);return {saved:true,exportReachable:true,reopened:true};});
}
async function layout(){
 if(!await page.locator('.fl-shell').count())await newCareer('q01-layout');
 const routes=await page.evaluate(()=>D6Flutlicht.adapter.project(v61CurrentCareer).frame.navigation.map(r=>r.id)),rows=[];
 for(const width of [320,390,768,1280,1440,844])for(const language of ['de','en'])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:width===844?390:900});await navigate('settings');await page.locator('[data-fl-theme-preference-control]').selectOption(theme);await page.locator('[data-fl-settings-language]').selectOption(language);await settle();
  for(const route of routes){await check('Q-LAY-01',`layout ${width}/${language}/${theme}/${route}`,async()=>{await navigate(route);const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,shells:document.querySelectorAll('.fl-shell').length,view:document.querySelector('.fl-content > [data-v46-view]:not([hidden])')?.dataset.v46View,heading:[...document.querySelectorAll('.fl-content h1,.fl-content h2,.fl-content h3')].filter(n=>n.getClientRects().length).map(n=>n.textContent),over:[...document.querySelectorAll('.fl-content *')].filter(n=>n.getClientRects().length&&n.getBoundingClientRect().right>innerWidth+2).slice(0,8).map(n=>({tag:n.tagName,class:n.className,text:n.textContent.slice(0,60)}))}));rows.push({width,language,theme,route,...metrics});if(route!=='matchplan'){assert(metrics.heading.length,'no visible heading');assert(metrics.scroll<=width+1,'page overflow '+metrics.scroll+' > '+width);}assert.equal(metrics.shells,1);if([390,1440].includes(width)&&['overview','squad','settings','transfers'].includes(route))await page.screenshot({path:path.join(out,`${route}-${width}-${language}-${theme}.png`),fullPage:true});return metrics;});}
 }
 fs.writeFileSync(path.join(out,'layout.json'),JSON.stringify(rows,null,2));
}
async function finance(){
 await newCareer('q01-finance');await page.locator('[data-v66-sponsor]').first().click();await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.market.phase==='budget');await page.locator('#v67-budget').selectOption('0');await page.locator('[data-v124-budget]').click();await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.market.phase==='open');
 await check('Q-PHASE-03/04/Q-CLUB-02','native finance closing, season transition and reload',async()=>{
  // Native simulation setup reaches season end; every review and mandatory decision below is a DOM action.
  await page.evaluate(async()=>{v61CurrentCareer.manager.reputation=5;while(v61CurrentCareer.world.market.phase==='open')v66NextMarketDay(v61CurrentCareer);let guard=0;while(!v61CurrentCareer.world.seasonFinished&&guard++<400)v62AdvanceDay(v61CurrentCareer);if(!v61CurrentCareer.world.seasonFinished)throw Error('season setup guard');await v64UiSave();v61CareerTab='overview';v61RenderCareer(v61CurrentCareer);});await settle();
  const steps=[];for(let step=0;step<4;step++){assert.equal(await page.evaluate(()=>v61CurrentCareer.world.transition.reviewStep),step);steps.push(await page.locator('#v67-season-show h2').innerText());await page.locator('[data-v67-review-next]').click();await page.waitForFunction(expected=>!v67Busy&&v61CurrentCareer.world.transition.reviewStep===expected,step+1);}const manager=await page.evaluate(()=>({choice:v61CurrentCareer.world.transition.choice,offers:v61CurrentCareer.world.transition.offers}));if(manager.choice===null){assert.equal(await page.locator('[data-v124-next]').count(),0,'manager decision must precede season start');await page.locator('[data-v67-stay]').click();await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.transition.choice!==null);}else{assert.equal(manager.choice,'stay');assert.equal(manager.offers.length,0);}const closing=await page.evaluate(()=>v66Own(v61CurrentCareer).balance);await page.locator('[data-v124-next]').evaluate(n=>{n.click();n.click()});await page.waitForFunction(()=>v61CurrentCareer.world.season===2&&!v67Busy);await page.locator('[data-v66-sponsor]').first().click();await page.waitForFunction(()=>v61CurrentCareer.world.market.phase==='budget'&&!v67Busy);await page.evaluate(()=>v61WaitForStorage());
  const accounts=await page.evaluate(()=>{const c=v61CurrentCareer,b=v66Own(c),before=JSON.stringify(c),a=v130SeasonAccounts(c,b.id,1);return {data:a,pure:before===JSON.stringify(c),budgetCount:b.ledger.filter(r=>r.season===2&&r.id.endsWith(':youth-budget')).length};});assert.equal(accounts.data.closing,closing);assert(accounts.pure);assert(accounts.data.salaryPaid);assert.equal(accounts.budgetCount,0);const saved=await state();await reloadCareer(saved.id);assert.deepEqual(await state(),saved);assert(await page.locator('#v124-budget').isVisible());await page.screenshot({path:path.join(out,'season-two-finance.png'),fullPage:true});await page.locator('#v67-budget').selectOption('200');await page.locator('[data-v124-budget]').click();await page.waitForFunction(()=>!v67Busy&&v61CurrentCareer.world.market.phase==='open');const second=await state();assert.equal(second.ledger.filter(r=>r.season===2&&r.id.endsWith(':youth-budget')).length,1);await reloadCareer(second.id);assert.deepEqual(await state(),second);return {...accounts,reviewSteps:steps,managerDecision:manager.choice===null?'explicit DOM stay':'native no-offers stay',newSeasonBudgetOnce:true,limitation:'Season matches simulated by native setup; all review and required decisions used DOM.'};
 });
}
(async()=>{try{server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));url=target==='source'?`http://127.0.0.1:${server.address().port}/source/index.html`:require('node:url').pathToFileURL(build).href;browser=await chromium.launch({executablePath:process.env.D6_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>network.push({url:r.url(),failure:r.failure()}));if(['quick','all'].includes(mode)){await quick();await require('./edge-cases.cjs')({page,check,navigate,settle});}if(['layout','all'].includes(mode))await layout();if(['finance','all'].includes(mode))await finance();if(mode==='supplement')await require('./supplement.cjs')({page,check,navigate,settle,newCareer,state,reloadCareer});await check('Q-LOAD-01','no JavaScript runtime errors',async()=>{assert.deepEqual(errors,[]);return {networkFailures:network};});}catch(error){records.push({id:'RUNNER',status:'fehlgeschlagen',error:String(error.stack||error)});}finally{const after=hashes(),changed=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(f=>before[f]!==after[f]);const report={runId,target,mode,url,browser:browser?.version(),node:process.version,platform:process.platform,startedWith:before,endedWith:after,changed,evidenceValid:changed.length===0,records,errors,network,limitations:['Each record proves only its named assertion, not the entire matrix condition.','No physical hardware, real screenreader, true 200-percent zoom or final inventory certification.','Source/build remain separate; evolving source invalidates acceptance evidence.']};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));console.log(out);process.exitCode=records.some(r=>r.status==='fehlgeschlagen')?1:0;}})();
