'use strict';
const assert=require('node:assert/strict'),{validate}=require('./projection-schema.cjs');
module.exports=async function({page,check,navigate,settle}){
 await check('Q-I18N-01','no malformed object labels anywhere in integrated DOM',async()=>{const broken=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(n=>n.tagName!=='SCRIPT'&&n.tagName!=='STYLE').flatMap(n=>[...n.attributes].map(a=>({element:n.tagName,attribute:a.name,value:a.value}))).filter(a=>/\[object object\]/i.test(a.value)));assert.deepEqual(broken,[]);return {malformedAttributes:0};});
 await check('Q-NAV-01','mobile direct routes overview squad transfers',async()=>{assert.deepEqual(await page.locator('.fl-mobile-nav [data-fl-route]').evaluateAll(nodes=>nodes.map(n=>n.dataset.flRoute)),['overview','squad','transfers']);return {directRoutes:['overview','squad','transfers']};});
 await check('Q-SQ-03/Q-MKT-04','pro profile then youth profile gets correct player skills',async()=>{
  await navigate('squad');await page.locator('.fl-squad-table [data-v61-player]:visible').first().click();await page.locator('dialog[open] [data-v61-close]').click();await page.locator('[data-fl-section-tab="youth"]').click();const youth=page.locator('[data-v67-profile]:visible').first(),pid=await youth.getAttribute('data-v67-profile');await youth.click();await settle();assert.equal(await page.locator('dialog[open]').getAttribute('data-fl-player-id'),pid);const expected=await page.evaluate(pid=>D6Flutlicht.adapter.project(v61CurrentCareer).players.all.find(p=>p.id===pid).skills.map(s=>s.label+': '+s.colorLabel),pid);assert.deepEqual(await page.locator('dialog[open] .fl-squad-profile-skills .fl-skill').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label'))),expected);await page.locator('dialog[open] [data-v61-close]').click();return {pid,skills:expected};
 });
 await check('Q-SQ-03/Q-DATA-04','fatigued profile uses effective form consistently',async()=>{
  const prepared=await page.evaluate(()=>{const p=v66Own(v61CurrentCareer).roster[0],original={form:p.form,fresh:p.fresh};p.form=2;p.fresh=20;v61RenderCareer(v61CurrentCareer);return {pid:p.pid,original,expected:D6Flutlicht.adapter.project(v61CurrentCareer).players.roster.find(r=>r.id===p.pid).form.label};});
  try{await navigate('squad');await page.locator('[data-fl-section-tab="roster"]').click();await page.locator(`.fl-squad-table [data-v61-player="${prepared.pid}"]:visible`).click();await settle();const form=await page.locator('dialog[open] .player-card-facts > span').evaluateAll(nodes=>nodes.filter(n=>/^(Form)/.test(n.textContent.trim())).map(n=>n.querySelector('b')?.textContent));assert.equal(form.length,1);assert.equal(form[0].toLowerCase(),prepared.expected.toLowerCase());return {form:form[0],expected:prepared.expected};}
  finally{await page.locator('dialog[open] [data-v61-close]').click().catch(()=>{});await page.evaluate(({pid,original})=>{Object.assign(v66Player(v61CurrentCareer,pid),original);v61RenderCareer(v61CurrentCareer)},prepared);}
 });
 await check('Q-NAV-01/Q-A11Y-01','browser Back/Forward and route focus',async()=>{await navigate('squad');await navigate('settings');await page.goBack();await settle();assert.equal(await page.evaluate(()=>v61CareerTab),'squad');assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('fl-content')),true);await page.goForward();await settle();assert.equal(await page.evaluate(()=>v61CareerTab),'settings');return {back:'squad',forward:'settings',contentFocus:true};});
 await check('Q-NAV-01','browser back from club detail restores visible settings',async()=>{await navigate('settings');await navigate('overview');const own=await page.evaluate(()=>v61CurrentCareer.manager.managedClubId);await page.locator(`[data-v46-view="overview"] [data-v68-club]:not([data-v68-club="${own}"]):visible`).first().click();await page.locator('[data-v68-detail]').waitFor();await page.goBack();await settle();assert(await page.locator('[data-v46-view="settings"]').isVisible());assert.equal(await page.locator('[data-v68-detail]').count(),0);return {settingsVisible:true,detailsRemoved:true};});
 await check('Q-A11Y-02','tooltip focus Escape tap outside and route cleanup',async()=>{let phase='focus';try{await navigate('squad');const trigger=page.locator('[data-v46-view="squad"] [data-fl-tooltip]:visible').first();await trigger.focus();await page.locator('.fl-tooltip:visible').waitFor();const within=await page.locator('.fl-tooltip:visible').evaluate(n=>{const b=n.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth+1&&b.top>=0&&b.bottom<=innerHeight+1});assert(within);await page.keyboard.press('Escape');assert.equal(await page.locator('.fl-tooltip:visible').count(),0);phase='tap';await trigger.click();await page.locator('.fl-tooltip:visible').waitFor();await page.locator('.fl-page-context').click({position:{x:2,y:2}});assert.equal(await page.locator('.fl-tooltip:visible').count(),0);await trigger.focus();await navigate('settings');assert.equal(await page.locator('.fl-tooltip:visible').count(),0);return {focus:true,escape:true,tap:true,outside:true,routeCleanup:true};}catch(error){const detail=await page.evaluate(()=>({active:document.activeElement?.outerHTML.slice(0,900),scrollY,tips:[...document.querySelectorAll('.fl-tooltip')].map(t=>({hidden:t.hidden,text:t.textContent,rect:t.getBoundingClientRect().toJSON()}))}));throw Error(phase+': '+error.message+' '+JSON.stringify(detail));}});
 await check('Q-DATA-01/03','projection has no career references, draws no random numbers and deep clones remain unchanged',async()=>{
  const result=await page.evaluate(()=>{const raw=new Set(),collect=v=>{if(!v||typeof v!=='object'||raw.has(v))return;raw.add(v);Object.values(v).forEach(collect)};collect(v61CurrentCareer);let calls=0;const random=Math.random;Math.random=()=>{calls++;return random()};let p;try{p=D6Flutlicht.adapter.project(v61CurrentCareer)}finally{Math.random=random}const leaks=[],seen=new Set(),walk=(v,at)=>{if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);if(raw.has(v))leaks.push(at);Object.entries(v).forEach(([k,x])=>walk(x,at+'.'+k))};walk(p,'projection');return {calls,leaks,p};});assert.equal(result.calls,0);assert.deepEqual(result.leaks,[]);validate(result.p);return {randomCalls:0,rawObjectReferences:0};
 });
 await check('Q-SQ-02/Q-DATA-04','six appearances include three substitutes; missing record stays unknown',async()=>{
  const result=await page.evaluate(()=>{const c=structuredClone(v61CurrentCareer),club=v66Own(c),p=club.roster[0],fixtures=v62Fixtures(c).filter(f=>f.homeId===club.id||f.awayId===club.id).slice(0,6);p.history=fixtures.map((f,index)=>{const side=f.homeId===club.id?0:1;f.matchRecord={players:[{pid:p.pid}],starters:{home:[],away:[]},substitutions:[]};if(index<3)f.matchRecord.starters[side===0?'home':'away']=[p.pid];else f.matchRecord.substitutions.push({side,inPid:p.pid});return {fixtureId:f.id,clubId:club.id,season:c.world.season,goals:0,assists:0}});const row=()=>D6Flutlicht.adapter.project(c).players.roster.find(r=>r.id===p.pid).stats;const complete=row();delete fixtures[0].matchRecord;const missing=row();return {complete,missing};});assert.equal(result.complete.appearances,6);assert.equal(result.complete.substitutions,3);assert.equal(result.missing.substitutions,null);assert.equal(result.missing.substitutionCoverage,'partial');return result;
 });
 await check('Q-CLUB-03','club records deduplicate summaries/history/fixture and tie ranks',async()=>{
  const result=await page.evaluate(()=>{const c=structuredClone(v61CurrentCareer),club=v66Own(c),[p,q]=club.roster;for(const player of club.roster){player.seasons=[];player.history=[]}p.seasons=[{season:1,clubId:club.id,games:6,goals:4}];p.history=[{season:1,clubId:club.id,fixtureId:'already-summary',goals:4},{season:2,clubId:club.id,fixtureId:'distinct-game',goals:2},{season:2,clubId:club.id,fixtureId:'distinct-game',goals:2}];q.seasons=[{season:1,clubId:club.id,games:7,goals:6}];const projected=D6Flutlicht.adapter.project(c);return {ids:[p.pid,q.pid],records:projected.club.profiles.find(r=>r.id===club.id).records};});const [p,q]=result.ids;assert.equal(result.records.goals.find(r=>r.playerId===p).value,6);assert.equal(result.records.appearances.find(r=>r.playerId===p).value,7);assert.equal(result.records.goals.find(r=>r.playerId===p).rank,result.records.goals.find(r=>r.playerId===q).rank);return result;
 });
 await check('Q-MKT-01/02','native free-agent negotiation is reachable, preserves original controls and submits once',async()=>{
  await navigate('transfers');await page.locator('[data-fl-section-tab="search"]').click();await page.locator('#v66-club').selectOption('free');await settle();const button=page.locator('[data-v66-select]:visible').first(),pid=await button.getAttribute('data-v66-select');await button.click();await page.locator('dialog[open] [data-v72-free-offer]').waitFor();const before=await page.evaluate(pid=>v61CurrentCareer.world.market.pendingBids.filter(b=>b.pid===pid).length,pid);await page.locator('dialog[open] [data-v72-free-offer]').click();await settle();const bids=await page.evaluate(pid=>v61CurrentCareer.world.market.pendingBids.filter(b=>b.pid===pid).map(b=>({id:b.id,pid:b.pid,status:b.status})),pid);assert.equal(bids.length,before+1);await page.locator('dialog[open] [data-v72-close]').first().click();return {pid,bids,limitation:'Offer submission; eventual acceptance/rejection and full transfer deadline cycle require separate coverage.'};
 });
};
