'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),target=process.argv[2]||'source',out=path.join(root,'outputs/ui-redesign/feedback',new Date().toISOString().replace(/[:.]/g,'-')+'-'+target);
const {chromium}=require('C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{createServer}=require('../serve.cjs');
const files=()=>Object.fromEntries(fs.readdirSync(path.join(root,'dist'),{recursive:true}).filter(f=>/\.(js|css|html)$/.test(f)).sort().map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'dist',f))).digest('hex')]));
const settle=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
(async()=>{
 fs.mkdirSync(out,{recursive:true});const before=files(),report={target,cases:[],errors:[]},server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,page,stage='launch';
 try{
  browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:956}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
  await page.goto(target==='source'?`http://127.0.0.1:${server.address().port}/source/index.html`:require('node:url').pathToFileURL(path.join(root,'outputs/index.html')).href);await page.waitForFunction(()=>v61StorageReady&&window.D6Flutlicht?.start&&window.D6Flutlicht?.navigation);
  const id=await page.evaluate(async()=>{const c=v61CreateCareer('ENG-2','feedback-real-menu','Menüprüfung'),club=v66Own(c);v66ChooseSponsor(c,club.id,club.sponsors[1].id);v124SetYouthBudget(c,0);v61CurrentCareer=await v61StoreNewCareer(c);v61CareerTab='overview';v61RenderCareer(c);return c.id;});await settle(page);
  async function navigate(route){let direct=page.locator(`[data-fl-route="${route}"]:visible`).first();if(!await direct.count()){await page.locator('[data-fl-menu]:visible').click();direct=page.locator(`[data-fl-route="${route}"]:visible`).first();}await direct.click();await settle(page);assert.equal(await page.evaluate(()=>v61CareerTab),route);}
  const pristine=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));
  require('./projection-schema.cjs').validate(await page.evaluate(()=>D6Flutlicht.adapter.project(v61CurrentCareer)));
  stage='menu matrix';
  for(const width of process.argv.includes('--actions')?[]:[320,390,768,1440])for(const language of ['de','en'])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:956});await page.evaluate(({language,theme})=>{doppel6Language.set(language);localStorage.setItem('doppel6.ui.flutlicht.theme',theme);}, {language,theme});
   // Theme preference is read by the adapter at load; use the real settings control.
   await navigate('settings');await page.locator('[data-fl-theme-preference-control]').selectOption(theme);await settle(page);
   for(const route of ['overview','squad','matchplan','transfers','competition','calendar','statistics','club','settings']){
    await navigate(route);const view=page.locator(`[data-v46-view="${route}"]`);assert(await view.isVisible());
    const tabs=view.locator('.fl-section-tabs [role="tab"],.fl-club-tabs [role="tab"]');
    for(let i=0;i<await tabs.count();i++){const button=tabs.nth(i);await button.click();await settle(page);assert.equal(await button.getAttribute('aria-selected'),'true');assert.equal(await view.locator('.fl-section-tabs [aria-selected="true"],.fl-club-tabs [aria-selected="true"]').count(),1);const box=await button.boundingBox();assert(box.height>=44&&box.width>=44);}
    const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,theme:document.querySelector('.fl-shell')?.dataset.flTheme}));assert(geometry.scroll<=width+1,`${route} ${width} overflow ${geometry.scroll}`);assert.equal(geometry.theme,theme);
    if((width===1440&&theme==='dark'&&language==='de')||(width===390&&theme==='light'&&language==='de'))await page.screenshot({path:path.join(out,`${route}-${width}-${theme}.png`),fullPage:route!=='matchplan'});
    report.cases.push({route,width,language,theme,tabs:await tabs.count(),passed:true});if(route==='settings')console.log(JSON.stringify({completed:report.cases.length,width,language,theme}));
   }
  }
  assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),pristine,'navigation/theme/filter presentation mutated career');
  stage='overview values';await page.evaluate(()=>doppel6Language.set('en'));await settle(page);await navigate('overview');
  assert.equal(await page.locator('.fl-overview-kpis>div').count(),4);const facts=await page.evaluate(()=>({balance:v66Credits(v66Own(v61CurrentCareer).balance),roster:v66Own(v61CurrentCareer).roster.length,plan:v124FinancePlan(v61CurrentCareer,v66Own(v61CurrentCareer).id)}));assert((await page.locator('.fl-overview-kpis').textContent()).includes(facts.balance));assert((await page.locator('.fl-overview-finance').textContent()).includes(await page.evaluate(v=>v66Credits(v),facts.plan.safe)));
  stage='offer dialog';await navigate('transfers');await page.locator('[data-fl-section-tab="search"]').click();
  const pid=await page.evaluate(()=>v66MarketPlayers(v61CurrentCareer).find(x=>x.club&&!v72SaleBlockReason(v61CurrentCareer,x.club.id,x.player.pid)).player.pid),pick=page.locator(`[data-v66-select="${pid}"]`);await pick.scrollIntoViewIfNeeded();const scroll=await page.evaluate(()=>scrollY),offerBefore=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));await pick.click();await page.locator('#v72-transfer-dialog[open]').waitFor();assert(await page.locator('#v72-fee').isVisible());assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),offerBefore);assert.equal(await page.locator('#v72-transfer-dialog').getAttribute('aria-labelledby'),'v72-dialog-title');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement?.dataset.v66Select),pid);assert(Math.abs(await page.evaluate(()=>scrollY)-scroll)<2);await pick.click();await page.locator('#v72-fee').fill('100');await page.locator('[data-v72-start]').click();await page.waitForFunction(()=>!v72DialogBusy);const deal=await page.evaluate(pid=>v72Market(v61CurrentCareer).negotiations.filter(n=>n.pid===pid&&n.buyerId===v61CurrentCareer.manager.managedClubId).map(n=>({id:n.id,stage:n.stage,price:n.price})),pid);assert.equal(deal.length,1);await page.keyboard.press('Escape');await page.locator(`[data-v66-select="${pid}"]`).click();assert.equal(await page.evaluate(()=>v72CurrentId),deal[0].id);assert.equal(await page.locator('[data-v72-start]').count(),0);assert.equal(await page.locator('#v72-dialog-title').textContent(),'Transfer negotiation');assert((await page.locator('#v72-transfer-dialog').textContent()).includes('Decision at the end of the transfer day'));await page.screenshot({path:path.join(out,'offer-current-dialog.png')});await page.keyboard.press('Escape');
  stage='lead feedback';await navigate('overview');await page.evaluate(()=>{const save=v64UiSave;v64UiSave=async(...args)=>{await new Promise(r=>setTimeout(r,500));return save(...args);};});assert.match(await page.locator('.fl-lead-progress').textContent(),/1.*5/);await page.locator('[data-fl-lead]').evaluate(button=>{button.click();document.querySelector('[data-fl-lead]').click();});await page.locator('.fl-lead-spinner').waitFor();assert.equal(await page.locator('[data-fl-lead]').getAttribute('aria-busy'),'true');assert(await page.locator('[data-fl-lead]').isDisabled());await page.screenshot({path:path.join(out,'lead-loading.png')});await page.waitForFunction(()=>v61CurrentCareer.world.market.day===2&&!v66DayBusy&&document.querySelector('[data-fl-lead]')?.getAttribute('aria-busy')==='false');assert.match(await page.locator('.fl-lead-progress').textContent(),/2.*5/);await page.evaluate(()=>v61WaitForStorage());
  stage='reload';const saved=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));await page.reload();await page.waitForFunction(()=>v61StorageReady&&window.D6Flutlicht?.adapter);await page.locator(`[data-v61-open="${id}"]`).click();await page.locator('.fl-content').waitFor();await settle(page);const restored=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));fs.writeFileSync(path.join(out,'saved.json'),saved);fs.writeFileSync(path.join(out,'restored.json'),restored);assert.equal(crypto.createHash('sha256').update(restored).digest('hex'),crypto.createHash('sha256').update(saved).digest('hex'),'restored career differs: saved.json/restored.json');
  assert.deepEqual(report.errors,[]);assert.deepEqual(files(),before,'source changed during proof');report.pass=true;report.nativeDeal=deal;report.loadingDay=2;
 }catch(error){report.pass=false;report.failure={stage,error:error.stack};if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});}
 finally{report.sourceBefore=before;report.sourceAfter=files();fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(report,null,2));if(browser)await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,report:path.join(out,'checks.json'),failure:report.failure}));if(!report.pass)process.exitCode=1;}
})().catch(e=>{console.error(e);process.exitCode=1;});
