'use strict';
// Isolated native start-flow proof. No user browser/profile is opened.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../../..'),runtime=path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node');
const {chromium}=require(path.join(runtime,'node_modules/playwright')),{createServer}=require('../../serve.cjs');
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const target=option('--target','source'),inject=args.includes('--inject'),build=path.resolve(root,option('--build','outputs/index.html'));
assert(['source','build'].includes(target));assert(!inject||target==='source');
const out=path.join(root,'outputs/ui-redesign/I00-start',new Date().toISOString().replace(/[:.]/g,'-'),target);fs.mkdirSync(out,{recursive:true});
const files=['dist/ui-flutlicht/start.js','dist/ui-flutlicht/start.css',...(target==='build'?[path.relative(root,build)]:[])];
const hashes=()=>Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')]));
const before=hashes(),checks=[],layouts=[],errors=[];let server,browser,page,url;
async function settle(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function check(name,run){try{const detail=await run();checks.push({name,status:'passed',detail});}catch(error){checks.push({name,status:'failed',error:String(error.stack||error)});throw error;}}
async function capture(name){await page.evaluate(()=>scrollTo(0,0));await settle();await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function contrast(selector){return page.locator(selector).first().evaluate(node=>{const rgb=value=>(value.match(/[\d.]+/g)||[]).slice(0,3).map(Number),lum=color=>rgb(color).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);let surface=node;while(surface&&getComputedStyle(surface).backgroundColor==='rgba(0, 0, 0, 0)')surface=surface.parentElement;const foreground=lum(getComputedStyle(node).color),background=lum(getComputedStyle(surface||document.body).backgroundColor);return (Math.max(foreground,background)+.05)/(Math.min(foreground,background)+.05);});}
async function layout(name){const value=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,theme:document.querySelector('.fl-start,.fl-start-flow')?.dataset.flTheme,headline:[...document.querySelectorAll('.fl-start h1,.fl-start-flow h1')].find(n=>n.getClientRects().length)?.textContent,headingFont:[...document.querySelectorAll('.fl-start h1,.fl-start-flow h1')].filter(n=>n.getClientRects().length).map(n=>getComputedStyle(n).fontFamily),over:[...document.querySelectorAll('.fl-start :is(button,input,select),.fl-start-flow :is(button,input,select),.fl-start-header')].filter(n=>n.getClientRects().length&&n.getBoundingClientRect().right>innerWidth+1).slice(0,4).map(n=>n.className)}));assert(value.scroll<=value.width+1,name+': document overflow '+value.scroll);assert.deepEqual(value.over,[],name+': control overflow');assert(value.headingFont.every(font=>font.includes('Segoe UI')),name+': old display typeface');layouts.push({name,...value});return value;}
async function boot(){await page.goto(url);await page.waitForFunction(()=>!!window.D6Flutlicht?.components&&v61StorageReady);if(inject){await page.addStyleTag({content:fs.readFileSync(path.join(root,'dist/ui-flutlicht/start.css'),'utf8')});await page.addScriptTag({content:fs.readFileSync(path.join(root,'dist/ui-flutlicht/start.js'),'utf8')});}await page.waitForFunction(()=>!!window.D6Flutlicht?.start);await settle();}
async function themeLanguage(theme,language){await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});await page.evaluate(async language=>{await window.doppel6Language.set(language);D6Flutlicht.start.refresh();},language);await settle();}
async function begin(){await page.locator('#v61-begin').click();await page.locator('#v61-manager-name').waitFor();await settle();}
(async()=>{server=createServer();if(target==='build'){const native=server.listeners('request')[0];server.removeAllListeners('request');server.on('request',(req,res)=>{if(req.url==='/__start_build.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fs.readFileSync(build));}else native(req,res);});}await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));url='http://127.0.0.1:'+server.address().port+(target==='source'?'/source/index.html':'/__start_build.html');browser=await chromium.launch({executablePath:path.join('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'),headless:true});page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));
 try{
  await boot();
  await check('native homepage, creation controls and options remain present',async()=>{assert.equal(await page.locator('#start-screen').isVisible(),true);assert.equal(await page.locator('#v61-begin').count(),1);assert.equal(await page.locator('.v46-extras').count(),1);assert.equal(await page.locator('.v81-options').count(),1);assert.equal(await page.locator('#language-select').count(),1);assert.equal(await page.locator('.legal-nav button').count(),3);return {begin:1,language:1,extras:true,options:true,legal:3};});
  for(const width of [390,1440])for(const language of ['de','en'])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:1000});await themeLanguage(theme,language);const key=width+'-'+language+'-'+theme;
   await layout('home-'+key);assert(await contrast('.legal-nav button')>=4.5,'legal-link contrast '+key);await capture('home-'+key);await begin();await layout('manager-'+key);
   if(width===390&&language==='de'&&theme==='light'){await page.locator('[data-v61-manager-next]').click();await page.locator('[data-v61-name-error]:not([hidden])').waitFor();assert.equal(await page.locator('#v61-manager-name').evaluate(n=>document.activeElement===n),true);await capture('manager-name-error-390-light');}
   await page.locator('#v61-manager-name').fill('Start QA '+language);const manager=await page.locator('#v61-manager-name').evaluate(n=>(window.inputBefore=n,true));const seed=await page.evaluate(()=>v61Flow.seed);
   await page.emulateMedia({colorScheme:theme==='dark'?'light':'dark'});await page.evaluate(()=>D6Flutlicht.start.refresh());assert.equal(await page.locator('#v61-manager-name').inputValue(),'Start QA '+language);assert.equal(await page.locator('#v61-manager-name').evaluate(n=>n===window.inputBefore),true);assert.equal(await page.evaluate(()=>v61Flow.seed),seed);await page.emulateMedia({colorScheme:theme});await settle();await capture('manager-'+key);
   await page.locator('[data-v61-manager-next]').click();await settle();assert.equal(await page.locator('[data-v61-country]').count(),6);await layout('country-'+key);await capture('country-'+key);
   await page.locator('[data-v61-country="ENG"]').click();await settle();assert.equal(await page.locator('[data-v61-club]').count(),6);await layout('clubs-'+key);await capture('clubs-'+key);
   await page.locator('[data-v61-club="ENG-1"]').click();await settle();const roster=await page.evaluate(()=>v61GenerateRoster(v61Catalog.find(c=>c.id===v61Flow.clubId),v61Flow.seed).map(p=>({pid:p.pid,name:p.name})));assert(roster.length>=10);await layout('roster-'+key);await capture('roster-'+key);
   await page.locator('[data-v61-review]').click();await settle();await layout('summary-'+key);await capture('summary-'+key);await page.locator('[data-v61-back="club"]').click();await page.locator('[data-v61-back="clubs"]').click();await page.locator('[data-v61-club="ENG-1"]').click();assert.deepEqual(await page.evaluate(()=>v61GenerateRoster(v61Catalog.find(c=>c.id===v61Flow.clubId),v61Flow.seed).map(p=>({pid:p.pid,name:p.name}))),roster);assert.equal(await page.evaluate(()=>v61Flow.seed),seed);
   await page.evaluate(()=>v61ShowStart());await settle();
  }
  checks.push({name:'48 native route layouts in desktop/mobile light/dark DE/EN, live theme keeps input/seed and back keeps roster',status:'passed',detail:{layouts:48}});
  await check('saved manual theme overrides device and language retains current input',async()=>{await page.evaluate(()=>{localStorage.setItem('doppel6.ui.flutlicht.theme','dark');D6Flutlicht.start.refresh();});await page.emulateMedia({colorScheme:'light'});await begin();await page.locator('#v61-manager-name').fill('Erhaltener Name');const seed=await page.evaluate(()=>v61Flow.seed);await page.evaluate(async()=>{window.languageInput=document.querySelector('#v61-manager-name');await doppel6Language.set('en');D6Flutlicht.start.refresh();});await settle();assert.equal(await page.locator('#v61-manager-name').inputValue(),'Erhaltener Name');assert.equal(await page.locator('#v61-manager-name').evaluate(n=>n===window.languageInput),true);assert.equal(await page.locator('.fl-start-flow').getAttribute('data-fl-theme'),'dark');assert.equal(await page.evaluate(()=>v61Flow.seed),seed);return {manual:'dark',inputSame:true,seedSame:true};});
  await page.locator('[data-v61-manager-next]').click();await page.locator('[data-v61-country="ENG"]').click();await page.locator('[data-v61-club="ENG-1"]').click();await page.locator('[data-v61-player]').first().click();await settle();await check('native player preview opens in same theme and closes',async()=>{assert.equal(await page.locator('dialog[open].fl-start-dialog').count(),1);assert.equal(await page.locator('dialog[open]').getAttribute('data-fl-theme'),'dark');await capture('player-preview-dark');await page.evaluate(()=>document.querySelector('dialog[open]').close());return {theme:'dark',nativeDialog:true};});
  await page.locator('[data-v61-review]').click();await check('320 and user 1575 widths retain summary and manager-name error',async()=>{for(const width of [320,1575]){await page.setViewportSize({width,height:956});await layout('summary-'+width);await capture('summary-'+width);}return {widths:[320,1575]};});
  await check('native creation write failure leaves summary, retry stores the same selected roster',async()=>{const selected=await page.evaluate(()=>{window.realStore=v61StoreNewCareer;v61StoreNewCareer=()=>new Promise((resolve,reject)=>window.rejectStart=()=>reject(Error('Start QA: lokaler Schreibfehler')));return {seed:v61Flow.seed,clubId:v61Flow.clubId,manager:v61Flow.managerName,roster:v61GenerateRoster(v61Catalog.find(c=>c.id===v61Flow.clubId),v61Flow.seed).map(p=>p.pid)};});await page.setViewportSize({width:390,height:1000});await page.locator('[data-v61-create]').click();await page.waitForFunction(()=>typeof window.rejectStart==='function');assert.equal(await page.locator('[data-v61-create]').isDisabled(),true);assert.equal(await page.locator('.fl-start-flow .v67-loading').isVisible(),true);await capture('save-loading-390');await page.evaluate(()=>window.rejectStart());await page.locator('[data-v61-start-error]').waitFor();assert.equal(await page.locator('[data-v61-create]').isEnabled(),true);assert.equal(await page.evaluate(()=>v61ReadCareers().length),0);assert.equal(await page.evaluate(()=>v61CurrentCareer),null);await layout('write-error-390');await capture('write-error-390');await page.evaluate(()=>v61StoreNewCareer=window.realStore);await page.locator('[data-v61-create]').click();await page.waitForFunction(()=>!!v61CurrentCareer&&!v61StorageWriting&&!v61StoragePending);await settle();const stored=await page.evaluate(()=>({clubId:v61CurrentCareer.manager.managedClubId,manager:v61CurrentCareer.manager.name,roster:v61CurrentCareer.world.clubs.find(c=>c.id===v61CurrentCareer.manager.managedClubId).roster.map(p=>p.pid),count:v61ReadCareers().length}));assert.equal(stored.clubId,selected.clubId);assert.equal(stored.manager,selected.manager);assert.deepEqual(stored.roster,selected.roster);assert.equal(stored.count,1);assert.equal(await page.locator('#v61-world-screen').getAttribute('class'), '');return {oneCareer:true,sameManager:true,sameRoster:true,loading:true,summaryBeforeConfirmedWrite:true};});
  await page.evaluate(async()=>{await v61ShowStart();D6Flutlicht.start.refresh();});await settle();await check('saved-world open/export/delete, legacy/import and legal/help controls remain reachable',async()=>{assert.equal(await page.locator('[data-v61-open]').count(),1);assert.equal(await page.locator('[data-v61-export]').count(),1);assert.equal(await page.locator('[data-v61-delete]').count(),1);await page.locator('.v46-extras>summary').click();await settle();await layout('home-extras-390');await capture('home-extras-390');assert.equal(await page.locator('#new-game').isVisible(),true);const importButtons=await page.locator('button').filter({hasText:/import/i}).count();assert(importButtons>=1);assert.equal(await page.locator('.legal-nav button').count(),3);await page.locator('.v46-extras>summary').click();await capture('home-saved-390-dark');return {savedActions:3,legacy:true,import:true,legal:3,help:await page.locator('[data-v134-help],.v134-footer-help').count()};});
  await check('delete confirmation and cancellation remain native and retain the saved career',async()=>{await page.locator('[data-v61-delete]').click();await page.locator('[data-v61-confirm-delete]').waitFor();assert.equal(await page.locator('[data-v61-cancel-delete]').count(),1);await layout('delete-confirmation-390');await capture('delete-confirmation-390');assert.equal(await page.evaluate(()=>v61ReadCareers().length),1);await page.locator('[data-v61-cancel-delete]').click();assert.equal(await page.locator('[data-v61-confirm-delete]').count(),0);assert.equal(await page.evaluate(()=>v61ReadCareers().length),1);return {confirmation:true,cancel:true,careerUnchanged:true};});
  assert.deepEqual(errors,[]);assert.deepEqual(hashes(),before,'owned source changed during test');
 }finally{const report={target,injected:inject,url,hashes:before,checks,layouts,errors,passed:checks.every(c=>c.status==='passed')&&errors.length===0};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:checks.length,layouts:layouts.length,output:out}));await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
