(function(){'use strict';
let graphicsSeed=481;function graphics(fn){const old=Math.random;Math.random=()=>{graphicsSeed=(Math.imul(graphicsSeed,1664525)+1013904223)>>>0;return graphicsSeed/4294967296;};try{return fn();}finally{Math.random=old;}}
window.D6DemoRenderer={async create(container){
 const T=window.THREE;if(!T)throw Error('Three.js missing');
 let gltf=window.D6ProbeGltf;
 if(!gltf){const [{GLTFLoader},buffer]=await Promise.all([import('/source/camera-prototype/vendor/GLTFLoader.js'),fetch('/source/players/football-v130.glb').then(r=>{if(!r.ok)throw Error('Player asset unavailable');return r.arrayBuffer();})]);gltf=await new GLTFLoader().parseAsync(buffer,'');}
 let renderer,scene,camera,ball,ballShadow,field,netViews=[],netMaxDeformation=0,netVertexCount=0,roster=new Map(),contactPoses=[],geometryKey='',cameraMode='overview',frames=0,lastRender=performance.now(),renderMs=[],width=0,height=0;
 graphics(()=>{
 renderer=new T.WebGLRenderer({antialias:false,alpha:false});renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=false;renderer.setClearColor('#14292d');container.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D-Vergleichsszene der Browserengine');renderer.domElement.setAttribute('role','img');renderer.domElement.style.cssText='width:100%;height:100%;display:block';
 scene=new T.Scene();scene.scale.x=-1; // Convert canonical left-handed field axes for the right-handed renderer.
scene.add(new T.HemisphereLight(0xe9f5ff,0x5b7350,2));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(-25,60,-25);scene.add(sun);camera=new T.PerspectiveCamera(50,16/9,.1,200);camera.position.set(0,58,-70);camera.lookAt(0,0,0);
 ball=new T.Mesh(new T.SphereGeometry(.1764,16,12),new T.MeshStandardMaterial({color:'#fffef5',roughness:.7}));scene.add(ball);
 ballShadow=new T.Mesh(new T.CircleGeometry(.24,24),new T.MeshBasicMaterial({color:'#173727',transparent:true,opacity:.45,depthWrite:false}));ballShadow.rotation.x=-Math.PI/2;scene.add(ballShadow);
 });
 function line(points,parent){const mesh=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color:'#f4f3dc'}));parent.add(mesh);}
 function goalNet(x,back,gw,gh){
  const vertices=[],indices=[],tags=[],thickness=.025;let panelTag='back';
  function segment(a,b,normal){const start=new T.Vector3(...a),end=new T.Vector3(...b),offset=end.clone().sub(start).cross(new T.Vector3(...normal)).normalize().multiplyScalar(thickness/2),n=vertices.length/3;for(const p of [start.clone().add(offset),start.clone().sub(offset),end.clone().sub(offset),end.clone().add(offset)]){vertices.push(p.x,p.y,p.z);tags.push(panelTag);}indices.push(n,n+1,n+2,n,n+2,n+3);}
  function strand(a,b,normal){const steps=Math.ceil(Math.hypot(...b.map((x,i)=>x-a[i]))/.25),at=t=>a.map((x,i)=>x+(b[i]-x)*t);for(let n=0;n<steps;n++)segment(at(n/steps),at((n+1)/steps),normal);}
  function panel(origin,u,v,normal,tag){panelTag=tag;const point=(a,b)=>origin.map((n,i)=>n+u[i]*a+v[i]*b),nu=Math.ceil(Math.hypot(...u)/.35),nv=Math.ceil(Math.hypot(...v)/.35);for(let i=0;i<=nu;i++)strand(point(i/nu,0),point(i/nu,1),normal);for(let i=0;i<=nv;i++)strand(point(0,i/nv),point(1,i/nv),normal);}
  panel([back,0,-gw/2],[0,0,gw],[0,gh,0],[1,0,0],'back');panel([x,gh,-gw/2],[back-x,0,0],[0,0,gw],[0,1,0],'roof');for(const z of [-gw/2,gw/2])panel([x,0,z],[back-x,0,0],[0,gh,0],[0,0,1],z<0?'left':'right');
  const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);const net=new T.Mesh(geometry,new T.MeshBasicMaterial({color:'#c9d6ce',side:T.DoubleSide}));net.name='Goal net';field.add(net);netViews.push({geometry,rest:new Float32Array(vertices),tags,goalSign:Math.sign(x),signature:null});
 }
 function rebuild(g){netViews=[];if(field){scene.remove(field);field.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [].concat(o.material))m.dispose();});}field=new T.Group();scene.add(field);const L=g.length||68,W=g.width||44,gw=g.goalWidth||9.705882352941178,gh=g.goalHeight||gw/3;
 for(let i=0;i<12;i++){const m=new T.Mesh(new T.PlaneGeometry(L/12,W),new T.MeshStandardMaterial({color:i%2?'#4b8447':'#579450',roughness:1}));m.rotation.x=-Math.PI/2;m.position.set(-L/2+(i+.5)*L/12,0,0);field.add(m);}
 const rect=(a,b,c,d)=>line([[a,.04,b],[c,.04,b],[c,.04,d],[a,.04,d],[a,.04,b]],field);rect(-L/2,-W/2,L/2,W/2);line([[0,.04,-W/2],[0,.04,W/2]],field);line(Array.from({length:65},(_,i)=>[Math.cos(i/64*Math.PI*2)*5.4,.04,Math.sin(i/64*Math.PI*2)*5.4]),field);
 const rod=(pos,length,horizontal=false)=>{const mesh=new T.Mesh(new T.CylinderGeometry(.06,.06,length,16),new T.MeshStandardMaterial({color:'#f4f3dc',roughness:.7}));mesh.position.set(...pos);if(horizontal)mesh.rotation.x=Math.PI/2;field.add(mesh);};
 for(const s of [-1,1]){rect(s*L/2,-10,s*(L/2-10),10);rect(s*L/2,-5,s*(L/2-4),5);const x=s*L/2,b=x+s*2.2;const bar=(position,size)=>{const mesh=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color:'#f4f3dc',roughness:.7}));mesh.position.set(...position);field.add(mesh);};for(const z of [-gw/2,gw/2]){rod([x,gh/2,z],gh);bar([b,gh/2,z],[.065,gh,.065]);bar([(x+b)/2,gh,z],[2.2,.065,.065]);}rod([x,gh,0],gw,true);bar([b,gh,0],[.065,.065,gw]);goalNet(x,b,gw,gh);}
 }
 function cloneModel(actor){const model=gltf.scene.clone(true),map=new Map();function pair(a,b){map.set(a,b);a.children.forEach((c,i)=>pair(c,b.children[i]));}pair(gltf.scene,model);gltf.scene.traverse(o=>{if(o.isSkinnedMesh){const m=map.get(o);m.skeleton=new T.Skeleton(o.skeleton.bones.map(b=>map.get(b)),o.skeleton.boneInverses.map(b=>b.clone()));m.bindMatrix.copy(o.bindMatrix);m.bindMatrixInverse.copy(o.bindMatrixInverse);m.frustumCulled=false;}});const group=new T.Group();model.scale.setScalar(1.45);model.position.y=.08;group.add(model);const ring=new T.Mesh(new T.RingGeometry(.44,.57,24),new T.MeshBasicMaterial({color:actor.team===0?'#f1bd5a':'#67d3d1',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.055;group.add(ring);scene.add(group);const mixer=new T.AnimationMixer(model);return {group,model,mixer,clip:null,ring,rig:window.D6Pose.bind(model,T)};}
 function render(state){return graphics(()=>{if(!state?.ready||!state.ball)return;const g=state.geometry||window.D6Probe?.config?.scenario?.geometry||{length:68,width:44};const key=JSON.stringify(g);if(key!==geometryKey){geometryKey=key;rebuild(g);}const rect=container.getBoundingClientRect(),w=Math.max(320,Math.round(rect.width)),h=Math.max(180,Math.round(rect.height));if(w!==width||h!==height){width=w;height=h;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
 if(cameraMode==='contact'){const f=window.D6ProbeCamera.frame([...(state.cameraPoints||[state.ball.position]),...((state.physicsProbe||state.playProbe)?[state.ball.position]:[])],camera.aspect),c=f.center;camera.position.set(-c[0],c[1]+f.distance*.6,c[2]-f.distance*.8);camera.lookAt(-c[0],c[1],c[2]);}else{const fit=Math.max(1,(16/9)/camera.aspect)*Math.max(g.length/68,g.width/44);camera.position.set(0,48*fit,-55*fit);camera.lookAt(0,0,0);}
 const ids=new Set((state.actors||[]).map(a=>a.id));for(const [id,v]of roster)if(!ids.has(id)){scene.remove(v.group);v.mixer.stopAllAction();v.mixer.uncacheRoot(v.model);v.model.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.dispose();});v.ring.geometry.dispose();v.ring.material.dispose();roster.delete(id);}
 contactPoses=[];for(const a of state.actors||[]){let v=roster.get(a.id);if(!v){v=cloneModel(a);roster.set(a.id,v);}v.ring.material.color.set(a.team===0?'#f1bd5a':'#67d3d1');const p=a.position||[0,0,0];v.group.position.set(p[0],0,p[2]);const velocity=a.velocity||[0,0,0],speed=Math.hypot(velocity[0],velocity[2]);const target=state.ball.position;v.group.rotation.y=state.playProbe?Math.atan2(a.facing[0],a.facing[2]):speed>.1?Math.atan2(velocity[0],velocity[2]):Math.atan2(target[0]-p[0],target[2]-p[2]);const pose=state.playProbe?window.D6Pose.sample(a,state):null;const name=pose?.clip||(speed>.1?'running':a.role==='keeper'?'keeper_ready_meshy':'idle');const clip=gltf.animations.find(c=>c.name===name)||gltf.animations.find(c=>/idle/i.test(c.name))||gltf.animations[0];if(v.clip!==clip){v.mixer.stopAllAction();v.mixer.clipAction(clip).play();v.clip=clip;}v.mixer.setTime(Math.max(0,pose?Math.min(pose.time,clip.duration):state.elapsed||0));if(pose?.active){const actual=window.D6Pose.solve(v.rig,pose.point,pose.kind);if(!actual)throw Error('Missing player contact bones');contactPoses.push({id:a.id,kind:pose.kind,target:pose.point,actual:actual.point,error:actual.error,clip:name,time:pose.time});}}
 netMaxDeformation=0;netVertexCount=0;const patches=state.netPatches||[],signature=JSON.stringify(patches);
 for(const view of netViews){netVertexCount+=view.rest.length/3;if(view.signature!==signature){view.signature=signature;const attr=view.geometry.attributes.position,values=attr.array;values.set(view.rest);let max=0;for(const patch of patches){if(patch.goalSign!==view.goalSign||Math.abs(patch.displacement)<.00001)continue;const axis=patch.panel==='back'?0:patch.panel==='roof'?1:2,sign=patch.panel==='back'?patch.goalSign:patch.panel==='left'?-1:1;for(let n=0;n<view.tags.length;n++){if(view.tags[n]!==patch.panel)continue;const i=n*3,p=[view.rest[i],view.rest[i+1],view.rest[i+2]],d=window.D6Net.displacement(g,p,patch);values[i+axis]+=sign*d;max=Math.max(max,Math.abs(d));}}view.max=max;attr.needsUpdate=true;view.geometry.computeBoundingSphere();}netMaxDeformation=Math.max(netMaxDeformation,view.max||0);}
 ball.position.fromArray(state.ball.position);ball.position.y=Math.max(.1764,ball.position.y);ballShadow.position.set(ball.position.x,.045,ball.position.z);ballShadow.material.opacity=.45/(1+Math.max(0,ball.position.y-.1764)*.5);renderer.render(scene,camera);const now=performance.now();renderMs.push(now-lastRender);if(renderMs.length>7200)renderMs.shift();lastRender=now;frames++;
 });}
 return {render,setCamera(mode){cameraMode=mode==='contact'?'contact':'overview';},stats(){return {frames,renderCount:frames,frameTimesMs:renderMs.slice(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,players:roster.size,contactPoses:JSON.parse(JSON.stringify(contactPoses)),netMaxDeformation,netVertexCount,renderMs:renderMs.slice(-120)};},dispose(){for(const v of roster.values())v.mixer.stopAllAction();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [].concat(o.material))m.dispose();});renderer.dispose();renderer.domElement.remove();}};
}};
})();
