'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),os=require('node:os');
const runtime=path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node');
if(Number(process.versions.node.split('.')[0])<20){const r=require('node:child_process').spawnSync(path.join(runtime,'bin/node.exe'),[__filename],{stdio:'inherit'});process.exit(r.status??1);}
const {chromium}=require(path.join(runtime,'node_modules/playwright')),base=path.resolve(__dirname,'../../../..');
const files=['dist/ui-flutlicht/views/settings.js','dist/ui-flutlicht/views/settings.css'],hashes=()=>Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex')]));
(async()=>{const before=hashes(),out=path.join(base,'outputs/ui-redesign/U01-F/fixture-2026-10-07');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setContent('<html><body style="margin:0"><main id="v61-world-screen"><div id="host"></div></main><dialog id="foreign"></dialog></body></html>');
 for(const file of ['tokens.css','components.css','views/settings.css'])await page.addStyleTag({content:fs.readFileSync(path.join(base,'dist/ui-flutlicht',file),'utf8')});for(const file of ['components.js','shell.js','registry.js','views/settings.js'])await page.addScriptTag({content:fs.readFileSync(path.join(base,'dist/ui-flutlicht',file),'utf8')});
 await page.evaluate(labels=>{
  window.labels=labels;window.events=[];window.projection={frame:{clubName:'Beispielverein',clubMeta:'Deutschland · Liga',navigation:[{id:'overview',label:'Übersicht'},{id:'squad',label:'Kader'},{id:'transfers',label:'Transfers'},{id:'settings',label:'Hilfe & Einstellungen'}],activeRoute:'settings',themePreference:'system',labels:{brand:'Doppel 6',menu:'Menü',close:'Schließen',skip:'Zum Hauptinhalt',navigation:'Karrieremenü'}},settings:{themePreference:'system',language:'de'}};
  window.refresh=()=>{shell.update(projection.frame);D6Flutlicht.registry.enhance(shell.content,projection,actions);};
  window.actions={t:text=>projection.settings.language==='en'?(labels[text]||text):text,navigate:id=>events.push(id),themeChanged:value=>{events.push(`theme:${value}`);projection.settings.themePreference=value;projection.frame.themePreference=value;refresh();},setLanguage:lang=>{events.push(`language:${lang}`);projection.settings.language=lang;refresh();},manageCareers:async()=>{events.push('manage');if(window.failSave)throw Error('Test: Speichern fehlgeschlagen');if(window.delaySave)await new Promise(resolve=>window.finishSave=resolve);},openHelp:()=>events.push('help'),openLegal:id=>events.push(`legal:${id}`)};
  window.shell=D6Flutlicht.shell.mount(document.querySelector('#host'),projection.frame,actions);refresh();refresh();window.originalTheme=document.querySelector('#fl-settings-theme');window.originalLanguage=document.querySelector('#fl-settings-language');
  D6Flutlicht.registry.enhance(document.querySelector('#foreign'),projection,actions);
 },JSON.parse(fs.readFileSync(path.join(__dirname,'labels.json'),'utf8')));
 assert.equal(await page.locator('[data-v46-view=settings]').count(),1);assert.equal(await page.locator('#foreign').evaluate(node=>node.childElementCount),0);
 const cases=[];for(const width of [320,390,768,1440])for(const theme of ['light','dark'])for(const lang of ['de','en']){await page.setViewportSize({width,height:844});await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});await page.evaluate(lang=>{projection.settings.language=lang;refresh()},lang);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#fl-settings-theme').evaluate(node=>node===originalTheme),true);assert.equal(await page.locator('#fl-settings-language').evaluate(node=>node===originalLanguage),true);assert.equal(await page.locator('.fl-settings h1').innerText(),lang==='en'?'Help & settings':'Hilfe & Einstellungen');cases.push({width,theme,lang,overflow:false});if(lang==='de'&&[390,1440].includes(width))await page.screenshot({path:path.join(out,`settings-${width}-${theme}.png`),fullPage:true});}
 await page.locator('#fl-settings-theme').selectOption('dark');assert.equal(await page.locator('#host').getAttribute('data-fl-theme'),'dark');await page.emulateMedia({colorScheme:'light'});assert.equal(await page.locator('#host').getAttribute('data-fl-theme'),'dark');await page.locator('#fl-settings-theme').selectOption('system');assert.equal(await page.locator('#host').getAttribute('data-fl-theme'),'light');
 await page.locator('#fl-settings-language').focus();await page.locator('#fl-settings-language').selectOption('de');assert.equal(await page.locator('#fl-settings-language').evaluate(node=>node===document.activeElement),true);assert.equal(await page.locator('.fl-settings h1').innerText(),'Hilfe & Einstellungen');
 await page.locator('[data-fl-settings-action=help]').click();for(const id of ['impressum','datenschutz','speicher'])await page.locator(`[data-fl-settings-legal=${id}]`).click();assert.deepEqual(await page.evaluate(()=>events.filter(item=>item==='help'||item.startsWith('legal:'))),['help','legal:impressum','legal:datenschutz','legal:speicher']);
 await page.evaluate(()=>window.failSave=true);await page.locator('[data-fl-settings-action=manage]').click();assert.equal(await page.locator('.fl-settings-error').innerText(),'Test: Speichern fehlgeschlagen');assert.equal(await page.locator('[data-fl-settings-action=manage]').isEnabled(),true);
 await page.evaluate(()=>{window.failSave=false;window.delaySave=true;});await page.locator('[data-fl-settings-action=manage]').click();assert.equal(await page.locator('[data-fl-settings-action=manage]').isDisabled(),true);await page.evaluate(()=>document.querySelector('[data-fl-settings-action=manage]').dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(await page.evaluate(()=>events.filter(item=>item==='manage').length),2);await page.evaluate(()=>finishSave());await page.locator('[data-fl-settings-action=manage]').waitFor({state:'visible'});assert.equal(await page.locator('.fl-settings-error').isVisible(),false);
 assert.deepEqual(errors,[]);assert.deepEqual(hashes(),before);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:true,sourceHashes:before,cases,checks:['one view after repeated enhancement','no settings view in dialogs','input identity preserved','DE/EN labels','theme device and manual override','language change focus retained','all native-controller action callbacks','save error shown and retry enabled','duplicate pending save suppressed'],limitations:['Sanitized fixture with callback spies; actual help, legal, save and import/export need integrated controller evidence','No physical device, Safari or screen-reader validation']},null,2));console.log(JSON.stringify({passed:true,cases:cases.length,out}));
 }finally{await browser.close();}})().catch(error=>{console.error(error.stack);process.exitCode=1});
