'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Play=require('../engine-probe/web/play.js'),catalog=require('../engine-probe/web/play-catalog.json');
function run(scene){const m=Play.create({scenario:structuredClone(scene),followThroughSeconds:3}),trace=[];m.state.running=true;for(let i=0;i<1000&&!m.state.finished;i++){m.step();if(i%12===0)trace.push(structuredClone(m.state));}assert(m.state.finished);return {state:m.state,trace};}
const results=[];for(const scene of catalog){const r=run(scene),s=r.state,again=run(scene);assert.deepEqual(r,again);assert.equal(s.actors.length,(scene.geometry.fieldPlayers+1)*2);assert.equal(s.events.filter(e=>e.type==='result').length,1);assert(Math.abs(s.elapsed-s.resolvedAt-3)<1e-8);assert.equal(s.events.filter(e=>e.type==='pass-release').length,1);const family=scene.provenance.family;
 if(family==='play-goal'){assert.equal(s.score.reduce((a,b)=>a+b),1);assert.equal(s.outcome,'goal');assert(s.events.some(e=>e.type==='received'));assert(s.events.some(e=>e.type==='net-contact'));}
 if(family==='play-interception'){assert.equal(s.outcome,'interception');assert.equal(s.ownerId,'defender');assert(!s.events.some(e=>e.type==='received'||e.type==='shot-release'));assert.equal(s.score.reduce((a,b)=>a+b),0);}
 if(family==='play-parry'){assert.equal(s.outcome,'possession');assert.equal(s.score.reduce((a,b)=>a+b),0);const parry=s.events.findIndex(e=>e.type==='parry'),free=s.events.findIndex(e=>e.type==='free-ball'),possession=s.events.findIndex(e=>e.type==='possession');assert(parry>0&&free>parry&&possession>free);assert(r.trace.some(t=>t.playPhase==='rebound'&&t.ownerId===null));assert(r.trace.some(t=>t.actors.some(a=>a.pose==='chase'&&Math.hypot(...a.velocity)>1)));}
 for(const e of s.events.filter(e=>e.type==='contact')){assert(e.actorId);assert(e.contactPoint);assert(e.ballDistance<=s.ball.radius+e.contactRadius+1e-7);}
 results.push({id:scene.id,...r});
}
// Removing the actual contact must change the outcome; expected labels never drive simulation.
const open=structuredClone(catalog.find(s=>s.provenance.family==='play-goal')),miss=structuredClone(open);miss.actors.find(a=>a.id==='receiver').velocity=[0,0,6];assert(!run(miss).state.events.some(e=>e.type==='received'||e.type==='shot-release'));
const blocked=structuredClone(catalog.find(s=>s.provenance.family==='play-interception'));blocked.actors.find(a=>a.id==='defender').position[2]+=7;assert.equal(run(blocked).state.outcome,'goal');
const saved=Play.create({scenario:open,followThroughSeconds:3});saved.state.running=true;while(saved.state.elapsed<1.7)saved.step();saved.state.running=false;const paused=structuredClone(saved.state);saved.step();assert.deepEqual(saved.state,paused);
let crossEngine=null;const unityFile=path.resolve('prototypes/match-engine-unity/play-tests.json');if(fs.existsSync(unityFile)){const u=JSON.parse(fs.readFileSync(unityFile)),source=require('../../../prototypes/match-engine-unity/source-identity.json').sourceId;if(u.sourceId===source){let maxDelta=0;for(const row of results){const other=u.cases.find(c=>c.id===row.id);assert(other?.passed);assert.equal(other.state.outcome,row.state.outcome);assert.deepEqual(other.state.score,row.state.score);for(const k of ['position','velocity'])for(let i=0;i<3;i++)maxDelta=Math.max(maxDelta,Math.abs(other.state.ball[k][i]-row.state.ball[k][i]));assert.deepEqual(other.state.events.map(e=>[e.type,e.actorId||null,e.tick]),row.state.events.map(e=>[e.type,e.actorId||null,e.tick]));}assert(maxDelta<1e-8);crossEngine={cases:results.length,maxDelta,tolerance:1e-8};}}
const out=path.resolve('outputs/platform/play');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'js-tests.json'),JSON.stringify({pass:true,cases:results.length,negativeCases:{receiverMiss:true,removedInterception:true,pause:true},crossEngine,results},null,2));console.log(JSON.stringify({pass:true,cases:results.length,crossEngine}));
