'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.D6_PLAYWRIGHT||'C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {manifest}=require('../performance/collect.cjs'),ROOT=path.resolve(__dirname,'../../..');
const {imageEvidence}=require('./image-evidence.cjs');
const engine=process.argv[2]||'browser';let base=process.env.D6_PROBE_URL;
const projection=s=>({scenarioId:s.scenarioId,tick:s.tick,elapsed:s.elapsed,ball:s.ball,actors:s.actors,events:s.events,score:s.score});
function checkpointEqual(actual,expected){const copy=structuredClone(actual);let maxPhysicalDelta=0;function number(a,b){assert(Number.isFinite(a)&&Number.isFinite(b));maxPhysicalDelta=Math.max(maxPhysicalDelta,Math.abs(a-b));assert(Math.abs(a-b)<=1e-10,`Physical checkpoint delta ${a-b} exceeds 1e-10`);return b}function vector(a,b){assert.equal(a.length,b.length);return a.map((v,i)=>number(v,b[i]))}copy.elapsed=number(copy.elapsed,expected.elapsed);copy.ball.position=vector(copy.ball.position,expected.ball.position);copy.ball.velocity=vector(copy.ball.velocity,expected.ball.velocity);assert.equal(copy.actors.length,expected.actors.length);copy.actors.forEach((a,i)=>{a.position=vector(a.position,expected.actors[i].position);a.velocity=vector(a.velocity,expected.actors[i].velocity)});assert.equal(copy.events.length,expected.events.length);copy.events.forEach((e,i)=>{e.time=number(e.time,expected.events[i].time);e.position=vector(e.position,expected.events[i].position)});assert.deepEqual(copy,expected,'Checkpoint identity/ticks/event metadata/configuration remain exact');return {maxPhysicalDelta,physicalTolerance:1e-10,exactFields:'scenarioId, tick, actor identities/actions, event identities/types/ticks/parent links/metadata, score, all other projected fields'}}
(async()=>{
 const out=path.join(ROOT,'outputs/platform/qa',`${new Date().toISOString().replaceAll(':','-').replaceAll('.','-')}-${engine}`);fs.mkdirSync(out,{recursive:true});
 const report={schema:1,engine,cases:[],errors:[],consoleMessages:[],renderErrors:[],observations:[],sourceSha256:manifest(path.join(ROOT,'dist')).sha256,scope:'local demo controls and observed runtime state; no full-match, career persistence, Android, or engine decision'};
 const sourceRoots=['work/platform/engine-probe','work/match-next/shared','work/match-next/contacts','docs/match-contracts',...(engine==='unity'?['outputs/platform/unity-web','prototypes/match-engine-unity']:[])],sources=sourceRoots.map(root=>({root,manifest:manifest(path.join(ROOT,root))}));fs.writeFileSync(path.join(out,'demo-source-manifests.json'),JSON.stringify(sources,null,2));
 let server;if(!base){server=require('../engine-probe/server.cjs').createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`}
 const browser=await chromium.launch({executablePath:process.env.D6_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,ignoreDefaultArgs:['--enable-unsafe-swiftshader']});
 async function check(name,fn){try{const evidence=await fn();report.cases.push({name,status:'passed',evidence})}catch(e){report.cases.push({name,status:'failed',error:e.stack})}}
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(['warning','error'].includes(m.type())){const entry={type:m.type(),text:m.text()};report.consoleMessages.push(entry);if(/GL_INVALID_|WebGL: too many errors|Can't add component|NullReferenceException|MissingReferenceException|RuntimeError/.test(entry.text))report.renderErrors.push(entry)}});
  async function fieldImage(label){const bytes=await page.locator('#frame').screenshot({path:path.join(out,`field-${label}.png`)}),evidence={label,...imageEvidence(bytes),actors:(await page.evaluate(()=>window.D6Probe.snapshot())).actors.length};report.observations.push(evidence);assert(evidence.greenPixelFraction>.02,`${label}: visible grass must occupy over 2% of image; got ${evidence.greenPixelFraction}`);assert(evidence.nonDominantPixelFraction>.02&&evidence.distinctColors>100,`${label}: scene must contain rendered detail, not a blank background`);return evidence}
  await page.route(/football-v130\.glb|\/unity\/Build\//,async route=>{await new Promise(r=>setTimeout(r,2000));await route.continue()});
  await page.goto(`${base}/demo/?engine=${engine}`,{waitUntil:'domcontentloaded'});
  await check('latest requested scene wins when loading again during initialisation',async()=>{await page.waitForFunction(()=>document.querySelector('#scene').options.length>0&&window.D6Probe);assert.equal(await page.locator('#start').isDisabled(),true);await page.locator('#scene').selectOption('backpass');await page.locator('#load').click();await page.locator('#scene').selectOption('offside-late-participation');await page.locator('#load').click();await page.waitForFunction(()=>window.D6Probe?.ready===true&&!document.querySelector('#start').disabled,null,{timeout:150000});const s=await page.evaluate(()=>window.D6Probe.snapshot());assert(s.scenarioId.startsWith('offside-late-participation-'));assert(!(await page.locator('#status').innerText()).startsWith('Fehler'));return {scenarioId:s.scenarioId,artificialAssetDelayMs:2000}});
  await page.unrouteAll({behavior:'wait'});await page.locator('#scene').selectOption('free-goal-keeper-left');await page.locator('#load').click();await page.waitForFunction(()=>window.D6Probe?.ready===true&&window.D6Probe.snapshot()?.scenarioId?.startsWith('free-goal-keeper-left-'),null,{timeout:150000});
  const state=()=>page.evaluate(()=>window.D6Probe.snapshot());
  await check('actual field imagery survives initial load, reset and checkpoint restore',async()=>{const images=[];images.push(await fieldImage('initial'));await page.locator('#reset').click();await page.waitForTimeout(250);images.push(await fieldImage('reset'));const cp=await page.evaluate(()=>window.D6Probe.checkpoint());await page.evaluate(cp=>window.D6Probe.restore(cp),cp);await page.waitForTimeout(250);images.push(await fieldImage('restored'));return images});
  await check('visible controls start, pause and resume a loaded scene',async()=>{
   const initial=await state();assert.equal(initial.engine,engine);assert.equal(initial.actors.length,12);await page.locator('#start').click();await page.waitForTimeout(200);await page.locator('#pause').click();await page.waitForTimeout(80);const paused=await state();assert(paused.tick>0);assert.equal(paused.running,false);await page.waitForTimeout(180);assert.deepEqual(projection(await state()),projection(paused));await page.locator('#resume').click();await page.waitForTimeout(180);await page.locator('#pause').click();await page.waitForTimeout(80);assert((await state()).tick>paused.tick);return {initialTick:initial.tick,pausedTick:paused.tick,resumedTick:(await state()).tick};
  });
  await check('visible checkpoint restore recovers paused state',async()=>{
   await page.locator('#reset').click();await page.waitForTimeout(120);await page.locator('#start').click();await page.waitForTimeout(180);await page.locator('#pause').click();await page.waitForTimeout(80);await page.locator('#checkpoint').click();await page.waitForFunction(()=>!document.querySelector('#restore').disabled);const saved=await state();await page.locator('#resume').click();await page.waitForTimeout(180);await page.locator('#pause').click();await page.waitForTimeout(80);await page.locator('#restore').click();await page.waitForTimeout(200);const precision=engine==='unity'?checkpointEqual(projection(await state()),projection(saved)):(assert.deepEqual(projection(await state()),projection(saved)),{physicalTolerance:0});return {tick:saved.tick,method:engine==='browser'?'deterministic replay checkpoint':'engine checkpoint',precision};
  });
  await check('camera controls change the picture and preserve paused simulation state',async()=>{await page.locator('#pause').click();await page.locator('#camera').selectOption('overview');await page.waitForTimeout(120);const before=projection(await state()),frame=page.locator('#frame'),overview=await frame.screenshot({path:path.join(out,'camera-overview.png')}),count=await page.evaluate(()=>window.D6Probe.stats().renderCount);await page.locator('#camera').selectOption('contact');await page.waitForFunction(count=>window.D6Probe.stats()?.renderCount>count,count);if(engine==='unity')await page.waitForFunction(()=>window.D6Probe.snapshot()?.cameraMode==='contact');await page.waitForTimeout(100);const contact=await frame.screenshot({path:path.join(out,'camera-contact.png')}),cameraEvidence={statePreserved:true,pictureChanged:!overview.equals(contact),cameraMode:(await state()).cameraMode,renderCountBefore:count,renderCountAfter:await page.evaluate(()=>window.D6Probe.stats().renderCount),overviewSha256:require('node:crypto').createHash('sha256').update(overview).digest('hex'),contactSha256:require('node:crypto').createHash('sha256').update(contact).digest('hex')};report.observations.push(cameraEvidence);assert(cameraEvidence.pictureChanged,'Contact camera must visibly differ from overview');assert.deepEqual(projection(await state()),before);await page.locator('#camera').selectOption('overview');await page.waitForTimeout(100);assert.deepEqual(projection(await state()),before);return cameraEvidence});
  await check('UI selects both field sizes, roster sizes and attack directions',async()=>{
   const observations=[];for(const [field,players,direction]of [['large','6','-1'],['current','5','1']]){await page.locator('#field').selectOption(field);await page.locator('#players').selectOption(players);await page.locator('#direction').selectOption(direction);await page.locator('#load').click();await page.waitForFunction(({field,players,direction})=>{const s=window.D6Probe.snapshot();return s?.geometry?.fieldPlayers===Number(players)&&s?.geometry?.attackDirection===Number(direction)&&Math.abs(s.geometry.length-(field==='large'?81.6:68))<.01},{field,players,direction});const s=await state();assert.equal(s.actors.length,(Number(players)+1)*2);await page.waitForTimeout(200);const image=await fieldImage(`${field}-${players}`);observations.push({scenarioId:s.scenarioId,actors:s.actors.length,geometry:s.geometry,findings:s.findings,image})}return observations;
  });
  await check('scene completion retains actual events and permits reset',async()=>{await page.locator('#start').click();await page.waitForFunction(()=>window.D6Probe.snapshot()?.finished,null,{timeout:15000});const completed=await state();report.observations.push(completed);assert(completed.elapsed>=3,'Scene must include three seconds of follow-through');if(engine==='unity'){assert.equal(completed.following,false);assert(Math.abs(completed.elapsed-completed.resolvedAt-3)<1e-8);assert.equal(completed.events.filter(e=>e.type==='result').length,1);assert(completed.events.some(e=>e.type==='net-contact'),'Free goal must visibly continue to the net');}await page.locator('#reset').click();await page.waitForTimeout(200);const reset=await state();assert.equal(reset.tick,0);assert.equal(reset.running,false);return {elapsed:completed.elapsed,tick:completed.tick,events:completed.events,score:completed.score,findings:completed.findings}});
  await check('follow-through stays visible, pauses and restores without changing the contact result',async()=>{
   await page.locator('#scene').selectOption('free-goal-keeper-left');await page.locator('#load').click();await page.waitForFunction(()=>window.D6Probe?.ready&&window.D6Probe.snapshot()?.scenarioId?.startsWith('free-goal-keeper-left-'));
   await page.locator('#start').click();await page.waitForFunction(()=>{const s=window.D6Probe.snapshot();return s?.following&&s.elapsed>=(s.resolvedAt||1)+.2},null,{timeout:15000});await page.locator('#pause').click();await page.waitForTimeout(80);const saved=await state();assert(saved.following&&!saved.finished&&!saved.running);const image=await fieldImage('follow-through');
   await page.locator('#checkpoint').click();await page.waitForFunction(()=>!document.querySelector('#restore').disabled);await page.locator('#resume').click();await page.waitForTimeout(200);await page.locator('#pause').click();await page.waitForTimeout(80);assert((await state()).tick>saved.tick);await page.locator('#restore').click();await page.waitForTimeout(200);const restored=await state();const precision=engine==='unity'?checkpointEqual(projection(restored),projection(saved)):(assert.deepEqual(projection(restored),projection(saved)),{physicalTolerance:0});assert(restored.following&&!restored.running);assert.deepEqual(restored.score,saved.score);return {elapsed:saved.elapsed,following:true,precision,image};
  });
  await check('actual hand and offside diagnostics or explicit native limitations are visible',async()=>{const observations=[];for(const family of ['backpass','offside-late-participation']){await page.locator('#scene').selectOption(family);await page.locator('#load').click();await page.waitForFunction(f=>window.D6Probe?.ready&&window.D6Probe.snapshot()?.scenarioId?.startsWith(f+'-'),family);await page.locator('#start').click();await page.waitForFunction(()=>window.D6Probe.snapshot()?.finished,null,{timeout:15000});await page.waitForTimeout(200);const s=await state(),events=await page.locator('#events').innerText(),findings=await page.locator('#findings').innerText();if(engine==='unity'){if(family==='backpass'){assert(s.events.some(e=>e.allowed===false));assert(events.includes('Handkontakt nicht erlaubt'))}else{assert(s.events.some(e=>e.whistle===true));assert(events.includes('Abseitspfiff'))}}else{assert(s.findings.some(f=>f.code===(family==='backpass'?'NATIVE_PERMISSION_PROBE':'OFFSIDE_FIXTURE_UNSUPPORTED')));assert(findings.includes(family==='backpass'?'Herkunftssperren':'keine native Abspielhistorie'))}observations.push({family,events:s.events,visibleEvents:events,visibleFindings:findings,nativeRuleOutcomeSupported:engine==='unity'})}return observations});
  if(engine==='unity')await check('missing checkpoint ball is rejected visibly without altering current state',async()=>{await page.evaluate(()=>{const api=document.querySelector('#frame').contentWindow.D6Probe,original=api.checkpoint;api.checkpoint=async()=>{api.checkpoint=original;const cp=await original();delete cp.state.ball;window.__qaBadCheckpointReady=true;return cp}});await page.locator('#checkpoint').click();await page.waitForFunction(()=>window.__qaBadCheckpointReady===true);await page.waitForTimeout(100);const before=projection(await state());await page.locator('#restore').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Fehler:'));const message=await page.locator('#status').innerText();await page.waitForTimeout(500);assert.equal(await page.locator('#status').innerText(),message);assert.deepEqual(projection(await state()),before);return {message,persistsAcrossUpdates:true,statePreserved:true,injectedInvalidField:'checkpoint.state.ball'}});
  await check('export button creates JSON download from observed state',async()=>{const event=page.waitForEvent('download');await page.locator('#export').click();const download=await event;await download.saveAs(path.join(out,'export.json'));const data=JSON.parse(fs.readFileSync(path.join(out,'export.json'),'utf8'));assert.equal(data.schema,'d6-probe-1');assert(data.state);return {filename:download.suggestedFilename(),scenario:data.scenario}});
  await page.screenshot({path:path.join(out,'demo.png'),fullPage:true});
  report.sourceUnchanged=manifest(path.join(ROOT,'dist')).sha256===report.sourceSha256;report.demoSources=sources.map(s=>({root:s.root,sha256:s.manifest.sha256,unchanged:manifest(path.join(ROOT,s.root)).sha256===s.manifest.sha256}));report.pass=report.cases.every(c=>c.status==='passed')&&report.errors.length===0&&report.renderErrors.length===0&&report.sourceUnchanged&&report.demoSources.every(s=>s.unchanged);
 }catch(e){report.failure=e.stack;report.pass=false}finally{await browser.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,engine,cases:report.cases,errors:report.errors,failure:report.failure,report:path.relative(ROOT,path.join(out,'report.json'))}));if(!report.pass)process.exitCode=1}
})().catch(e=>{console.error(e);process.exitCode=1});
