'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),os=require('node:os');
const runtime=path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node');
if(Number(process.versions.node.split('.')[0])<20){const result=require('node:child_process').spawnSync(path.join(runtime,'bin/node.exe'),[__filename],{stdio:'inherit'});process.exit(result.status??1);}
const {chromium}=require(path.join(runtime,'node_modules/playwright')),base=path.resolve(__dirname,'../../../..');
const own=['dist/ui-flutlicht/views/market.js','dist/ui-flutlicht/views/market.css'];
const hash=()=>Object.fromEntries(own.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex')]));
const fixture=`<main id="v61-world-screen"><div class="fl-shell" data-fl-theme="light" style="display:block"><div class="fl-content" id="root">
<section class="v62-season v66-market"><div class="v62-season-head"><h2>Transfers</h2><p>Transfertag 3 von 5 · 11 Profis · Kontostand 800 Credits</p></div>
<section class="v72-open-deals"><h3>Deine Angebote & Ergebnisse</h3><div><span><button data-v68-player="p1">Spielerprofil</button><small>Gegenforderung des Vereins · Antwort ausstehend</small></span><button data-v72-deal="deal1">Dialog öffnen</button></div></section>
<section class="v72-own-sales" id="v72-own-sales"><h3>Eigene Verkaufsangebote</h3><article class="v72-own-card"><div><button data-v61-player="p1">Alex Beispielspieler</button><small>Zum Verkauf · 800 Credits</small></div><button data-v72-withdraw="p1">Angebot zurückziehen</button><div class="v72-own-offer"><span>Aktuelles Gebot 750 Credits</span><div class="v72-own-actions"><button class="v72-quick-accept" data-v72-quick-seller="deal2" data-v72-response="accept" aria-label="Gebot annehmen">✓</button><button class="v72-quick-reject" data-v72-quick-seller="deal2" data-v72-response="reject" aria-label="Gebot ablehnen">×</button></div></div></article></section>
<section class="v72-sale-list" id="v72-sale-list"><div class="section-heading"><h3>Von Vereinen angeboten</h3><span>1 angezeigt</span></div><div class="v72-filters"><label>Land<select id="v72-country"><option>Alle Länder</option></select></label><label>Position<select id="v72-line"><option>Alle Positionen</option></select></label><label>Verhandelbare Ablöse bis<input id="v72-max-price" value="800"></label><label>Wechselbereitschaft<select id="v72-willingness"><option>Offen</option></select></label></div><div class="v72-sale-grid"><article class="v72-sale-card"><div class="v72-sale-top"><div><button data-v66-profile="p1">Alex außergewöhnlich langer vollständiger Spielername</button><small>Fußballverein Lange Vereinsnamen · Mittelfeld · 21 Jahre</small></div><span class="v72-willingness v72-open" role="img" aria-label="Offen">✓</span></div><div class="v72-sale-prices"><span>Ablöse<b>800 Credits</b></span><span>Marktwert<b>750 Credits</b></span></div><button data-v72-open="p1" disabled>Erst im nächsten Fenster</button></article></div></section>
<h3>Spieler suchen</h3><div class="v66-filters"><label>Vereinsland<select id="v66-country"><option>Deutschland</option></select></label><label>Nationalität<select id="v66-nationality"><option>Alle Nationalitäten</option></select></label><label>Verein<select id="v66-club"><option>Alle Vereine und Freie</option></select></label><label>Position<select id="v66-line"><option>Mittelfeld</option></select></label></div><div class="v66-player-list"><article class="v66-player-card" data-selected="true"><div class="v66-player-identity"><span><button data-v66-profile="p1" class="v66-player-name">Alex außergewöhnlich langer vollständiger Spielername</button><small>Langer Beispielverein · Deutschland · Mittelfeld, 21</small></span></div><button class="v66-player-pick" data-v66-select="p1"><b>750 Credits</b><small>Angebot planen</small></button></article></div><section class="v66-offer"><h3>Neues Angebot</h3><div class="v66-fields"><label>Gehalt<input id="v66-salary" value="150"></label><button data-v66-offer="p1">Angebot senden</button></div><p role="alert">Nicht genügend Budget</p></section></section>
<section class="v62-season v66-contracts"><h3>Profiverträge</h3><div class="v66-contract-wrap"><table class="v66-contract-table fl-data-table"><thead><tr><th><button data-v66-contract-sort="name">Spieler</button></th><th>Restlaufzeit</th><th>Aktion</th></tr></thead><tbody><tr><td data-fl-label="Spieler"><button data-v61-player="p1">Alex Beispielspieler</button></td><td data-fl-label="Restlaufzeit">1 Saison</td><td data-fl-label="Aktion"><button data-v66-renew-open="p1">Verlängern</button></td></tr></tbody></table></div></section>
<section class="v62-season v67-youth" id="v67-youth"><h3>Nachwuchspool</h3><p>1 Kandidat · Profikader 14 / 14</p><div class="v67-filters"><label>Position<select id="v67-line"><option>Alle Positionen</option></select></label><label>Sortierung<select id="v67-sort"><option>Ablauf zuerst</option></select></label></div><div class="v67-youth-list"><article><div><button data-v67-profile="y1">Nachwuchsspieler langer Name</button><small>Sturm · 18 Jahre · bis Ende Saison 4</small><small>Ausbildungsentschädigung 100 Credits · Gehalt 80 Credits · 0 freie Kaderplätze</small></div><div class="v67-youth-actions"><button data-v67-promote="y1" disabled>In den Profikader übernehmen</button><button data-v67-release="y1">Entlassen</button></div></article></div><p class="v61-error" role="alert">Kader voll</p></section>
</div></div></main>`;
(async()=>{const before=hash(),out=path.join(base,'outputs/ui-redesign/U01-C/fixture-2026-10-07');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setContent(`<html><body style="margin:0">${fixture}</body></html>`);
 for(const file of ['world-start-v61.css','world-economy-v66.css','world-youth-v67.css','ui-flutlicht/tokens.css','ui-flutlicht/components.css','ui-flutlicht/views/market.css'])await page.addStyleTag({content:fs.readFileSync(path.join(base,'dist',file),'utf8')});
 for(const file of ['ui-flutlicht/components.js','ui-flutlicht/registry.js','ui-flutlicht/views/market.js'])await page.addScriptTag({content:fs.readFileSync(path.join(base,'dist',file),'utf8')});
 await page.evaluate(()=>{window.root=document.querySelector('#root');window.nativeInput=document.querySelector('#v66-salary');window.nativePromote=document.querySelector('[data-v67-promote]');window.nativeFilter=document.querySelector('#v66-country');window.nativeClicks=0;nativeFilter.addEventListener('change',()=>nativeClicks++);window.data={players:{all:['p1','y1'].map(id=>({id,skills:['violetgray','bluegray','yellow','orange','pink'].map((band,i)=>({label:['Tempo','Tackling','Passspiel','Technik','Abschluss'][i],band,colorLabel:band})),form:{band:'orange',label:'Gut'},freshness:{percent:84,band:'orange',label:'Frische'}}))}};D6Flutlicht.registry.enhance(root,data,{t:text=>text});D6Flutlicht.registry.enhance(root,data,{t:text=>text});});
 assert.equal(await page.locator('.fl-market-jumps').count(),1);assert.equal(await page.locator('.fl-market-player-details').count(),3);assert.equal(await page.locator('.fl-market-skills .fl-skill').count(),15);
 assert.equal(await page.evaluate(()=>nativeInput===document.querySelector('#v66-salary')&&nativePromote===document.querySelector('[data-v67-promote]')&&nativeFilter===document.querySelector('#v66-country')),true);assert.equal(await page.locator('[data-v67-promote]').isDisabled(),true);assert.equal(await page.locator('[data-v72-open]').isDisabled(),true);
 await page.locator('#v66-salary').fill('190');await page.evaluate(()=>D6Flutlicht.registry.enhance(root,data,{t:text=>text}));assert.equal(await page.locator('#v66-salary').inputValue(),'190');await page.locator('#v66-country').dispatchEvent('change');assert.equal(await page.evaluate(()=>nativeClicks),1);
 const checks=[];for(const width of [320,390,768,1440])for(const theme of ['light','dark']){await page.setViewportSize({width,height:844});await page.evaluate(theme=>document.querySelector('.fl-shell').dataset.flTheme=theme,theme);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}/${theme}`);checks.push({width,theme,overflow});if([390,1440].includes(width))await page.screenshot({path:path.join(out,`market-${width}-${theme}.png`),fullPage:true});}
 await page.locator('[data-fl-market-jump=search]').click();assert.equal(await page.locator('#v66-country').evaluate(node=>document.activeElement===node),true);
 await page.evaluate(()=>{const dialog=document.createElement('dialog');dialog.className='fl-dialog v72-transfer-dialog';dialog.dataset.flTheme='light';dialog.innerHTML='<div class="v72-dialog-head"><h2>Vertragsverhandlung</h2><button data-v66-renew-close aria-label="Dialog schließen">×</button></div><div class="v72-dialog-facts"><span>Dein Angebot<b>150 Credits</b></span><span>Gegenforderung<b>180 Credits</b></span></div><div class="v66-fields"><label>Jahresgehalt<input value="180"></label><label>Laufzeit<select><option>2 Saisons</option></select></label></div><p class="v72-stage">Antwort ausstehend</p><p class="v72-dialog-error" role="alert">Angebot konnte nicht gespeichert werden.</p><div class="v72-confirm-actions"><button>Angebot senden</button><button class="v72-confirm-danger">Verhandlung abbrechen</button></div>';document.body.append(dialog);dialog.querySelector('[data-v66-renew-close]').onclick=()=>dialog.close();dialog.showModal();});
 await page.setViewportSize({width:320,height:700});assert.equal(await page.locator('dialog').evaluate(node=>node.scrollWidth<=node.clientWidth),true);await page.locator('[data-v66-renew-close]').click();assert.equal(await page.locator('dialog').evaluate(node=>node.open),false);
 await page.evaluate(()=>{D6Flutlicht.registry.enhance(root,{players:{all:[]}},{t:text=>text});});assert.equal(await page.locator('.fl-market-player-details').count(),0);assert.equal(await page.locator('[data-v67-release]').count(),1);
 await page.evaluate(()=>{document.querySelector('.v66-player-list').innerHTML='<p>Keine Spieler in dieser Auswahl.</p>';document.querySelector('.v67-youth-list').innerHTML='<p>Keine Kandidaten in dieser Auswahl.</p>';D6Flutlicht.registry.enhance(root,{players:{all:[]}},{t:text=>text==='Transferbereiche'?'Transfer sections':text});});assert.equal(await page.locator('.fl-market-jumps').getAttribute('aria-label'),'Transfer sections');assert.equal(await page.locator('.v66-player-list').innerText(),'Keine Spieler in dieser Auswahl.');assert.deepEqual(errors,[]);assert.deepEqual(hash(),before);
 fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:true,sourceHashes:before,checks,interactionChecks:['idempotent repeated enhancement','all five skill bands','original nodes and directly attached listener retained','input value retained','native disabled conditions preserved','quick jump moves keyboard focus','missing projection preserves native actions','empty states and translated aria label'],limitations:['Representative sanitized native DOM fixture; real financial actions and storage require integrated source test','No real hardware or screen-reader evidence']},null,2));console.log(JSON.stringify({passed:true,cases:checks.length,out}));
 }finally{await browser.close();}})().catch(error=>{console.error(error.stack);process.exitCode=1});
