'use strict';
// Read-only asset/source audit. Does NOT run Unity, mutate clips or claim rendered proof.
// node work/platform/animation/quality-audit.cjs [--out outputs/3d-quality/animation-audit/<name>] [--self-test]
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),vm=require('node:vm');
const root=path.resolve(__dirname,'../../..');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const U='prototypes/match-engine-unity/',P=U+'FootballPresentation.cs',A=U+'FootballAnimation.cs',L=U+'FootballLocomotion.cs',S=U+'FootballSetup.cs',B='dist/world-unity-v151.js';
const tracked=[P,A,L,S,B,U+'ProbeBridge.cs',U+'ProbeSetup.cs',U+'WorldViewContract.cs',U+'FootballGaitTests.cs',U+'FootballActionTests.cs',U+'FootballDuel.cs',U+'FootballDuelTests.cs',U+'source-identity.json','dist/world-pitch3d-v98.js','dist/pitch-v56.js','dist/pitch-motion-v102.js','dist/player-ball-events-v111.js','dist/player-user-ball-actions-v111.js','dist/world-pitch-actions-v99.js','work/platform/assets/manifest.json','work/platform/assets/contact-pilot-manifest.json',U+'import-validation.json'];
function takeSources(){return Object.fromEntries(tracked.map(file=>[file,fs.readFileSync(path.join(root,file),'utf8')]));}
function anchor(sources,file,needle){const text=sources[file],at=text.indexOf(needle);return at<0?null:{file,line:text.slice(0,at).split('\n').length,needle};}
function evidence(sources,pairs){return pairs.map(([file,needle])=>anchor(sources,file,needle)).filter(Boolean);}
function glb(file){const bytes=fs.readFileSync(path.join(root,file));assert.equal(bytes.toString('ascii',0,4),'glTF');assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);let g,bin;for(let at=12;at<bytes.length;){const len=bytes.readUInt32LE(at),kind=bytes.readUInt32LE(at+4),chunk=bytes.subarray(at+8,at+8+len);if(kind===0x4e4f534a)g=JSON.parse(chunk.toString('utf8'));if(kind===0x004e4942)bin=chunk;at+=8+len;}assert.ok(g&&bin);return{g,bin,bytes,sha256:sha(bytes)};}
function fileFact(file,expected){const absolute=path.join(root,file);if(!fs.existsSync(absolute))return{file,exists:false};const bytes=fs.readFileSync(absolute),hash=sha(bytes);return{file,exists:true,bytes:bytes.length,sha256:hash,...(expected?{expectedSha256:expected,hashMatches:hash===expected}:{})};}
function times(asset,accessorIndex){const a=asset.g.accessors[accessorIndex],v=asset.g.bufferViews[a.bufferView];assert.equal(a.componentType,5126);assert.equal(a.type,'SCALAR');const step=v.byteStride||4,at=(v.byteOffset||0)+(a.byteOffset||0);return Array.from({length:a.count},(_,i)=>asset.bin.readFloatLE(at+i*step));}
function inventory(sources){
 const prior=JSON.parse(sources['work/platform/assets/manifest.json']),pilot=JSON.parse(sources['work/platform/assets/contact-pilot-manifest.json']);
 const loaded=glb('dist/players/football-v130.glb'),jointIndices=new Set(loaded.g.skins.flatMap(s=>s.joints));
 const clips=loaded.g.animations.map(a=>{const ts=a.samplers.flatMap(s=>times(loaded,s.input));const targets=[...new Set(a.channels.map(c=>c.target.node))];return{name:a.name,asset:'dist/players/football-v130.glb',duration:Math.max(...ts),start:Math.min(...ts),channels:a.channels.length,targetNodes:targets.map(i=>loaded.g.nodes[i].name),nonJointTargets:targets.filter(i=>!jointIndices.has(i)).map(i=>loaded.g.nodes[i].name),inputSamples:[...new Set(a.samplers.map(s=>loaded.g.accessors[s.input].count))]};});
 const pilotAssets=pilot.files.map(f=>fileFact(f.path,f.sha256));
 for(const c of pilot.clips){const f=pilotAssets.find(f=>f.file.endsWith('/'+c.name+'.anim'));if(!f?.exists)continue;const text=fs.readFileSync(path.join(root,f.file),'utf8'),paths=[...new Set([...text.matchAll(/^\s*path: ?([^\r\n]*)$/gm)].map(m=>m[1]).filter(p=>!/^\d+$/.test(p)))];clips.push({name:c.name,asset:f.file,duration:Number(text.match(/m_StopTime: ([\d.]+)/)?.[1]??c.duration),contactSecondsFromExistingManifest:c.contactSeconds,contact:c.contact,channels:paths.length,bindingPaths:paths,bindsActorRoot:paths.includes(''),allBindingsUnderExistingPrefabRoot:paths.every(p=>p==='target_character'||p.startsWith('target_character/')),metadataOrigin:'Existing pilot manifest, contact timings not remeasured in Unity by this audit'});}
 return {original:fileFact('dist/players/football-v130.glb',prior.assetHash),baseFbx:fileFact(prior.outputDirectory+'/football-v130.fbx'),pilotAssets,clips,joints:[...jointIndices].map(i=>loaded.g.nodes[i].name),priorClipCount:prior.clips.length,clipNamesMatchPrior:JSON.stringify(clips.filter(c=>c.asset.endsWith('.glb')).map(c=>c.name).sort())===JSON.stringify(prior.clips.map(c=>c.name).sort()),historicalUnityImport:JSON.parse(sources[U+'import-validation.json']),notes:['GLB durations read from binary sample times; not merely copied from the old manifest.','FBX existence/hash is measured; prior Unity import report is historical evidence, not a new import.','.anim binding paths are inspected; animated target_character under prefab is distinct from actor root. No new rig evaluation or retargeting.']};
}
function wiring(sources){
 const p=sources[P],start=p.indexOf('FootballAnimation.Pose WorldFootballPose'),end=p.indexOf('FootballAnimation.Pose DemoFootballPose',start),world=p.slice(start,end);
 assert.ok(start>=0&&end>start,'World pose selector anchors must exist');
 const catalogMatch=p.match(/AnimationClip\[\] FootballClips\(\)\s*\{return new\[\]\{([^}]+)\}/);assert.ok(catalogMatch,'Catalogue syntax changed: adapt audit rather than infer');
 const catalog=catalogMatch[1].split(',').map(x=>x.trim()),assignments={};
 for(const f of [U+'ProbeSetup.cs',S])for(const m of sources[f].matchAll(/bridge\.(\w+)=Clip\((?:baseAsset,)?"([^"]+)"\)/g))assignments[m[1]]={clip:m[2],anchor:anchor(sources,f,m[0])};
 for(const m of sources[S].matchAll(/var (pass|receive)=Adapt\("([^"]+)"\)/g)){const field=m[1]+'Clip';if(sources[S].includes('bridge.'+field+'='+m[1]))assignments[field]={clip:m[2],anchor:anchor(sources,S,m[0])};}
 const cases=[],branches=[];const re=/\b(?:if|else if)\s*\(/g;let m;
 // Balanced conditions include multiline expressions; clips inside bodies are source candidates.
 while((m=re.exec(world))){let at=re.lastIndex,depth=1;for(;at<world.length&&depth;at++){if(world[at]==='(')depth++;if(world[at]===')')depth--;}const cond=world.slice(re.lastIndex,at-1),actions=[...cond.matchAll(/p\.action\s*==\s*"([^"]+)"/g)].map(x=>x[1]);let begin=at;while(/\s/.test(world[begin]))begin++;let finish=begin;if(world[begin]==='{'){let braces=1;for(finish=begin+1;finish<world.length&&braces;finish++){if(world[finish]==='{')braces++;if(world[finish]==='}')braces--;}}else finish=world.indexOf(';',begin)+1;const body=world.slice(begin,finish),clipFields=[...new Set([...body.matchAll(/\b(\w+Clip)\b/g)].map(x=>x[1]).filter(x=>catalog.includes(x)))];const branch={condition:cond,body,clipFields,clips:clipFields.map(x=>assignments[x]?.clip||x),anchor:anchor(sources,P,cond)};branches.push(branch);for(const action of actions)cases.push({action,...branch});}
 // These world selectors use observed motion, not invented p.action labels.
 // Require both their real guard and body; a catalogue entry/comment alone is insufficient.
 const compact=text=>text.replace(/\s/g,'');
 const carrierBound=compact(world).includes('boolcarrying=f.owner==p.id&&!identity.keeper;')&&compact(world).includes('pose.clip=LocomotionClip(locomotion,carrying,identity.keeper);');
 const motionSelections={
  dribble:carrierBound?branches.find(b=>compact(b.condition).startsWith('locomotionAction&&carrying&&locomotion.Speed>')&&b.body.includes('Reach(')&&compact(b.body).includes('pose.contact=')&&compact(b.body).includes('pose.kind=')):null,
  keeperShuffle:/(?:^|[;{}])Lateral=actual>/.test(compact(sources[L]))?branches.find(b=>compact(b.condition).includes('identity.keeper&&keeperShuffleClip!=null')&&compact(b.condition).includes('Math.Abs(locomotion.Lateral)>')&&compact(b.condition).includes('locomotion.Speed>')&&compact(b.body).includes('pose.clip=keeperShuffleClip;')&&compact(b.body).includes('pose.time=locomotion.Lateral<0?cycle:-cycle;')):null
 };
 return{catalog,assignments,cases,world,motionSelections,controller:'Manual PlayableGraph + cached AnimationMixerPlayable; no AnimatorController state machine',catalogClipNames:catalog.map(x=>assignments[x]?.clip||x)};
}
function bridgeProbe(sources){const context={module:{exports:{}},console};vm.createContext(context);vm.runInContext(sources[B],context,{filename:B});const C=context.module.exports;assert.equal(typeof C.picture,'function');const fixture={clock:10,elapsed:10,ball:{x:0,height:.29,z:0},players:[{id:'p',x:0,z:0,team:0,number:1,slideActive:true,action:{kind:'run',id:1,progress:.4,duration:.5},unityAction:{kind:'slide',id:'slide:p',progress:.3,duration:.65,contactWorld:{x:.4,height:.29,z:0}},movement:{mode:'run',facing:{x:1,z:0}}}]},camera={position:{x:0,height:30,z:0},target:{x:0,height:0,z:0},fov:45};const picture=(f)=>JSON.parse(JSON.stringify(C.picture(f,'audit',1,camera,'live',[0,0])));const active=picture(fixture).players[0];fixture.players[0].unityAction={...fixture.players[0].unityAction,kind:'slideRecovery',progress:.5};const recovery=picture(fixture).players[0];fixture.players[0].action={kind:'foulOffender',id:'foul:10',progress:.6};const foul=picture(fixture).players[0];fixture.players[0].unityAction=null;fixture.players[0].action={kind:'save',id:'save:10',saved:true,holding:true,pickup:.4,height:1,progress:.8,duration:1,contactWorld:{x:0,height:1,z:0}};const save=picture(fixture).players[0];return{method:'Execute the actual browser picture contract in isolated node:vm; synthetic frame, no game state or browser',slide:active,slideRecovery:recovery,foulPrecedence:foul.action,preservedSaveFields:{saved:'saved' in save,holding:'holding' in save,pickup:'pickup' in save,height:'height' in save},slideProjected:active.action==='slide',recoveryProjected:recovery.action==='slideRecovery'};}
function actionRows(sources,assets,w,bridge){
 const rows=[],clipNames=new Set(assets.clips.map(c=>c.name));
 function row(id,label,{action=null,clips=[],native=[],contact='None required.',transition='Native time; shared mixer fade 0.12 s, cut on replay/time jump, pause freezes sampling.',mode=null,selector=null,limitation=null,defect=false,missing=false,unproven=false,rig='Existing 28-joint Generic rig; actor root motion disabled.',visual='Both directions, pause, replay seek, entry/exit and close/TV view.'}={}){
  const motion=selector?w.motionSelections[selector]:null,cases=selector?(motion?[motion]:[]):action?w.cases.filter(c=>c.action===action):[],clipFields=cases.flatMap(c=>c.clipFields),found=clips.filter(c=>clipNames.has(c));
  const integrated=selector?Boolean(motion)&&found.some(c=>w.catalogClipNames.includes(c)):mode?Boolean(anchor(sources,P,mode))&&found.some(c=>w.catalogClipNames.includes(c)):cases.length>0;
  let classification=unproven?'unproven':integrated?(defect?'integrated-quality-defect':'present+integrated'):found.length?'present-unwired':missing?'missing':'unproven';
  if(action==='slide'&&!bridge.slideProjected||action==='slideRecovery'&&!bridge.recoveryProjected)classification=found.length?'present-unwired':'missing';
  rows.push({id,label,classification,actionTrigger:action||'received position/facing/time',triggerEvidence:evidence(sources,native),unitySelection:cases.map(({action,condition,clips,anchor})=>({action,condition,clips,anchor})),modeEvidence:motion?.anchor||(mode?anchor(sources,P,mode):null),candidateClips:clips.map(c=>({name:c,present:clipNames.has(c),catalogued:w.catalogClipNames.includes(c),asset:assets.clips.find(x=>x.name===c)?.asset||null,duration:assets.clips.find(x=>x.name===c)?.duration||null})),selectedClipFields:clipFields,rig,contact,transition,limitation:typeof limitation==='function'?limitation(integrated):limitation,visualReviewRequired:visual,evidenceLevel:'asset bytes + source wiring only; no new rendered evidence'});
 }
 const movement=[['stand','Stehen',['idle_stand_meshy'],'return keeper?keeperClip:idleClip'],['walk','Gehen',['walking'],'if(mode=="walk")'],['run','Laufen/Joggen',['running','run_fast4','run_fast6'],'if(mode=="run")'],['sprint','Sprint',['sprint_forward'],'if(mode=="sprint")'],['turn','Drehungen Stand/Gehen/Laufen',['turn_idle_left','turn_idle_right','turn_walk_left','turn_walk_right','turn_run_left','turn_run_right'],'if(m.Mode.StartsWith("turn-"))'],['brake','Bremsen',['brake_meshy'],'if(m.Mode=="brake")'],['backpedal','Rückwärtsbewegung',['back_walk','back_left'],'if(mode=="back")']];
 for(const [id,label,clips,mode] of movement)row(id,label,{clips,mode,native:[[L,'public void Sample(']],contact:'Measured footfall/stride/sole on rig at runtime; no ball contact.',limitation:id==='backpedal'?'back_right/back_step_meshy remain unused; backward gait does not prove lateral keeper shuffle.':null});
 row('dribble','Dribbling/Ballführung',{clips:['running'],selector:'dribble',native:[['dist/world-pitch3d-v98.js','owner:current.owner?.pid']],contact:'Observed non-keeper carrier during locomotionAction: procedural alternating left/right foot reach before measured stride footfall; partial weight, ground-ball gate, no native impulse.',limitation:integrated=>integrated?'Carrier guard and procedural foot reach are source-wired; no dedicated dribble clip. Suitability in tight space and both feet remains visual review.':'Running clip exists, but world carrier guard/foot-reach selection is not source-proven.'});
 const foot=[['control','Bodenannahme/Kontrolle','control',['receive_ground_meshy'],'ReceiveContact=.7'],['receive','Passempfang','receive',['receive_ground_meshy'],'ReceiveContact=.7'],['pass','Bodenpass','pass',['pass_inside_meshy'],'PassContact=.8'],['high-pass','Hoher Pass','highPass',['pass_inside_meshy'],'PassContact=.8'],['cross','Flanke','cross',['pass_inside_meshy'],'PassContact=.8'],['shot','Schuss','shot',['shot_meshy'],'ShotContact=.46'],['volley','Volley','volley',['shot_meshy'],'ShotContact=.46']];
 for(const [id,label,action,clips,time] of foot)row(id,label,{action,clips,native:[['dist/pitch-motion-v102.js','function v102Pose']],contact:time+'; post-release contact gate .09 s (receive .12 s), right-foot IK within 1.4 m root and 1 m current ball. Standing support-foot planting.',defect:['cross','highPass','volley'].includes(action),limitation:action==='volley'?'Volley uses ground-shot body/foot pose; no dedicated aerial preparation, height or authored volley family.':action==='highPass'||action==='cross'?'Ground inside-pass pose reused for high delivery; authored crossing action absent.':null});
 row('pass-ready','Passvorbereitung',{action:'passReady',clips:['pass_inside_meshy'],contact:'Progress samples 0..0.8 s before contact; no invented ball release.'});
 row('kick-ready','Schussvorbereitung',{action:'kickReady',clips:['shot_meshy'],contact:'Progress samples 0..0.46 s before contact.'});
 row('header','Kopfball',{action:'header',clips:[],native:[['dist/pitch-motion-v102.js',"'header'"]],defect:true,contact:'Head/spine procedural reach; root distance <2.6 m, ball/contact distance <1.2 m; no dedicated clip; head correction at most 22 degrees.',limitation:'No authored takeoff/header/landing family; locomotion clip continues under head reach.'});
 row('air-ready','Luftballvorbereitung',{action:'airReady',clips:[],defect:true,contact:'Same bounded head reach as header; partial weight .8*progress.',limitation:'No aerial body preparation/takeoff clip.'});
 row('air-land','Landung nach Luftduell',{action:'airLand',clips:[],missing:true,native:[['dist/pitch-motion-v102.js',"action.kind==='airLand'"]],limitation:'No dedicated airLand selection or landing clip in current Unity action catalog.'});
 row('standing-tackle','Stehender Zweikampf',{action:'tackle',clips:[],missing:true,native:[['dist/pitch-v56.js',"v102Pose(m,tackler,'tackle'"]],contact:'Native actual ball contact; Unity selector must not decide winning/foul.',limitation:integrated=>integrated?'Standing tackle selects receiveClip and procedural lunge/left-or-right foot at observed contact. Dedicated tackle clip absent; visible reach, stance and return still need review.':'No Unity tackle branch or dedicated tackle clip is source-proven.'});
 for(const [id,label] of [['slide-front','Grätsche von vorn'],['slide-side','Grätsche von der Seite'],['slide-back','Grätsche von hinten']])row(id,label,{action:'slide',clips:[],missing:true,native:[['dist/pitch-v56.js','function v56ApproachInfo'],['dist/pitch-v56.js','m.slide={'],['dist/world-pitch3d-v98.js','slideActive:Boolean']],contact:'Native path/behind/contact gates decide legality; all origins use same observed slide action. No authored slide clip in source inventory.',transition:'Native slide progress then recovery; never local visual timer.',limitation:integrated=>!bridge.slideProjected?'Bridge does not project native slide; projection and Unity pose need integration.':integrated?'Native slide phase reaches a procedural low-body selector using supplied progress and frozen stride; front/side/back contact and floor continuity still need rendered review.':'Native slide phase reaches bridge; Unity procedural/authored slide selector remains missing.'});
 for(const [id,label,needle] of [['slide-gain','Grätsche: Ballgewinn','m.owner=tackler'],['slide-deflect','Grätsche: freier/abgefälschter Ball',"v50LooseBall({x:tackler.x"],['slide-miss','Grätsche: verfehlt','if(slide.progress>=1)'],['slide-foul','Grätsche: Foulkontakt','v50Foul(victim,tackler)']])row(id,label,{action:'slide',clips:[],missing:true,native:[['dist/pitch-v56.js',needle]],contact:'Outcome authoritative in native simulation; phase must preserve actual root/ball, never fake successful contact.',limitation:integrated=>integrated&&bridge.slideProjected?'Shared procedural slide is source-wired for the native outcomes; separate authored outcome clips are not required. Actual gain/deflection/miss/foul contact and phase exits need visual fixtures.':'No shared slide selector/projected phase is proven; preserve native outcome authority when integrating a common pose.'});
 row('slide-recover','Grätsche: Aufstehen/Erholung',{action:'slideRecovery',clips:['keeper_rise_meshy'],native:[['dist/pitch-v56.js','player.slideActive&&!m.slide']],contact:'No extra ball/contact decision.',transition:'Integrator supplies recovery progress/duration; rise uses supplied native phase, no new timer.',limitation:integrated=>integrated&&bridge.recoveryProjected?'Native recovery selects keeper rise with FootballDuelTiming.RiseTime/Recovery. Floor-to-rise continuity still needs rendered review.':'Keeper rise exists, but native projection and/or Unity slideRecovery selection is not integrated.'});
 row('foul-victim','Foulopfer: Sturz und Aufstehen',{action:'foulVictim',clips:['foul_fall_meshy','keeper_rise_meshy'],native:[['dist/player-ball-events-v111.js','function v113FoulAction']],contact:'Existing foul signal, no contact prediction.',transition:'Foul 2.7 s: fall first 1.6 s, then keeper_rise 4.4..6.3 clip seconds.',limitation:'A reused keeper rise after the fall needs floor/body continuity and contact checks on both sides.'});
 row('foul-offender','Foulverursacher/Stolpern',{action:'foulOffender',clips:['foul_stumble_meshy'],native:[['dist/player-ball-events-v111.js',"'foulOffender'"]],limitation:integrated=>integrated?'Existing stumble clip is assigned, catalogued and selected in the foulOffender branch with a bounded FootballDuelTiming.StumbleLength and standing blend. Short-window/floor/return quality still needs rendered review.':'Existing stumble clip is not source-wired for foulOffender; assign/catalog/select a suitable bounded window first.'});
 row('stumble-general','Stolpern außerhalb Foul',{action:'stumble',clips:['foul_stumble_meshy'],unproven:true,limitation:'No proven native independent stumble trigger; avoid inventing gameplay events merely for animation.'});
 row('keeper-ready','Torwartbereitschaft',{clips:['keeper_ready_meshy'],mode:'return keeper?keeperClip:idleClip',contact:'No ball contact.',limitation:'Current gaze/stance source exists; visible readiness before lateral action still needs review.'});
 row('keeper-shuffle','Seitlicher Torwartschritt',{clips:['keeper_shuffle_meshy'],selector:'keeperShuffle',native:[[L,'Lateral=actual']],contact:'Observed keeper lateral travel relative to facing, |Lateral|>.72 and speed .12..4.1 m/s; no turn/brake. Existing left clip reverses cycle for right travel, no extra AI.',limitation:integrated=>integrated?'Existing shuffle is assigned, catalogued and selected from measured Lateral; no keeperShuffle action is required. Reversed-cycle right side, readiness, stop/dive/rise transitions still need rendered review.':'Existing shuffle clip has no source-proven measured-lateral world selector or catalog assignment.'});
 for(const [id,label] of [['keeper-save','Torwartparade allgemein'],['keeper-dive','Seitliches Hechten'],['keeper-high','Hohe Parade']])row(id,label,{action:'save',clips:['keeper_low_meshy','keeper_high_meshy','keeper_dive_meshy'],contact:'Select high if contact y>1.6 m, dive if |contact.z-position.z|>1.2 m, else low; authored windows low .70..1.18, high .93..1.46, dive .23.. .81. Contact only progress>.78 and ball/contact distance<.6 m; one/two hands; bounded arms.',transition:'Urgent mixer response .035 s; recovery>.35 reuses keeper_rise.',limitation:'Source thresholds are global-z based while hands/dive lean use local space. Angled orientations and both diving sides require actual review.'});
 row('keeper-catch','Torwart fängt/hält',{action:'save',clips:['keeper_low_meshy'],unproven:true,contact:'Same native save signal/hand reach as parry; ball still native-owned.',limitation:'Picture contract does not preserve saved/holding, so distinct catch/hold/secure sequence is not proven.'});
 row('keeper-rebound','Torwart Abpraller/Nachfassen',{action:'save',clips:['keeper_low_meshy','keeper_dive_meshy'],unproven:true,limitation:'Rebound ball remains visible from native frames; no explicit saved vs parry outcome passed and no authored follow-up family proven.'});
 row('keeper-rise','Torwart Aufstehen',{action:'save',clips:['keeper_rise_meshy'],contact:'Contact disabled after recovery>.35.',transition:'Uses native recovery, samples (recovery-.35)/.65 of full rise clip.',limitation:'Separate foul rise uses short window, keeper uses full 8.23 s mapped recovery. Fallen pose and floor continuity require visual review.'});
 row('keeper-kick','Torwart Fußabspiel/Abstoß',{action:'goalKick',clips:['shot_meshy'],defect:true,native:[['dist/world-pitch-actions-v99.js',"'goalKick'"]],contact:'Same right-foot ground-shot timing .46 s.',limitation:'No pickup/ball hold/drop-kick preparation passed; dedicated distribution animation absent.'});
 row('keeper-throw','Torwart Wurf/Rollen',{action:'keeperThrow',clips:[],unproven:true,limitation:'No proven native keeperThrow action, no authored roll/throw clip. Existing throw denotes throw-in; do not assume keeper distribution is implemented.'});
 row('throw-in','Einwurf',{action:'throw',clips:[],defect:true,native:[['dist/world-pitch-actions-v99.js',"kind:'throw'"]],contact:'Procedural two-hands when actual ball y>1 m and within 1.3 m projected horizontal reach; no authored overhead throw clip.',limitation:'holding/pickup are discarded by picture contract; no full pickup/hold/windup/release follow-through sequence.'});
 row('corner','Eckball',{action:'cross',clips:['pass_inside_meshy'],defect:true,native:[['dist/world-pitch-actions-v99.js',"'corner'"]],contact:'Uses high-pass/cross right-foot window .8 s.',limitation:'Corner preparation/delivery reuses ground-pass movement; dedicated corner clip not required if validated visually, but not yet validated here.'});
 row('free-kick','Freistoß',{action:'freeKick',clips:['shot_meshy'],native:[['dist/pitch-motion-v102.js',"'freeKick'"]],contact:'Reuse shot .46 s and kickReady preparation.',limitation:'No specialised free-kick clip; shot reuse needs ball placement/foot/plant review.'});
 row('penalty','Elfmeter',{action:'shot',clips:['shot_meshy'],unproven:true,native:[['dist/world-pitch-actions-v99.js',"'penalty'"]],contact:'Generic shot contact .46 s if native penalty projects shot.',limitation:'Generic branch is present; full penalty-specific run-up/contact/keeper/result sequence not proven by this source audit.'});
 row('kickoff','Anstoß/Wiederanstoß',{action:'pass',clips:['pass_inside_meshy'],unproven:true,native:[['dist/world-pitch-actions-v99.js','current.kickoff']],limitation:'Reuse pass is possible; dedicated native kickoff action path and complete sequence must be demonstrated in fixture.'});
 row('celebration','Torjubel',{clips:['celebrate_arms','celebrate_fist','celebrate_victory'],mode:'if(f.celebrating&&locomotionAction',native:[[B,'celebrating:true']],limitation:'Only booked scoring team while nearly stationary; scorer gets victory; replay/pause and return to restart require review.'});
 return rows;
}
function recommendations(actions){
 const integrated=id=>actions.find(a=>a.id===id)?.classification==='present+integrated';
 const result=[];
 function next(ids,owner,missing,review){const ready=ids.every(integrated);result.push({priority:ready?'P1 visual gate':'P1',scope:ready?'visual-review':'source-gap',owner,actionIds:ids,task:ready?review:missing});}
 next(['slide-front','slide-side','slide-back','slide-gain','slide-deflect','slide-miss','slide-foul','slide-recover'],'Integrator + Claude',
  'Complete missing native slide/recovery projection and low-body source selection; preserve authoritative contact and supplied progress.',
  'Slide/recovery is source-wired. Review low pelvis, leading leg, floor-to-rise continuity and gain/deflection/miss/foul from all approach directions; no source reintegration required.');
 next(['foul-offender'],'Claude','Assign/catalog/select the existing foul_stumble_meshy with a suitable bounded source window.',
  'Foul-offender stumble is source-wired. Review the bounded upright window, lunge fade, standing blend and continuity with victim fall/rise.');
 next(['keeper-shuffle'],'Claude','Select existing keeper_shuffle_meshy from measured lateral movement relative to received facing.',
  'Measured-lateral keeper shuffle is source-wired. Review left/right reversed-cycle steps and readiness/stop/dive/rise transitions.');
 next(['standing-tackle','dribble'],'Claude','Complete any missing standing-tackle or observed-carrier foot-reach source selectors.',
  'Standing tackle and observed-carrier dribble reach are source-wired. Review both feet, bounded ball reach, tight-space carrier gait and return to normal stride.');
 const remaining=actions.filter(a=>a.classification!=='present+integrated');
 result.push({priority:'P2',scope:'remaining-source-gap-or-substitution',owner:'Claude',actionIds:remaining.filter(a=>a.classification==='missing'||a.classification==='integrated-quality-defect').map(a=>a.id),task:'Review/complete remaining aerial landing, aerial body preparation, high delivery/volley and throw/distribution source substitutions. A dedicated clip is not required when a validated procedural/local alternative works.'});
 result.push({priority:'P2',scope:'sequence-unproven',owner:'Integrator + Claude',actionIds:remaining.filter(a=>a.classification==='unproven').map(a=>a.id),task:'Demonstrate currently unproven catch/hold/parry/rebound, keeper throw/roll and complete penalty/kickoff sequences; independent stumble has no proven native trigger, so do not invent gameplay to animate it.'});
 result.push({priority:'P1 final gate',scope:'render-and-device-acceptance',owner:'Integrator + independent reviewer',task:'Review reproducible actual Unity sequences in TV/close view, both directions, pause/replay, normal/large pitch, 12/14 players. This source audit provides no screenshots/videos or smartphone proof and cannot accept visible 3D quality.'});
 return result;
}
function build(sources){
 const assets=inventory(sources),w=wiring(sources),bridge=bridgeProbe(sources),actions=actionRows(sources,assets,w,bridge),counts={};
 for(const a of actions)counts[a.classification]=(counts[a.classification]||0)+1;
 const catalogueClips=w.catalogClipNames.filter(c=>assets.clips.some(a=>a.name===c));
 return{schema:'d6-animation-quality-audit/1',generatedAt:new Date().toISOString(),unitySourceId:JSON.parse(sources[U+'source-identity.json']).sourceId,scope:'Current repo assets, JS picture contract and Unity source selection. No Editor, build, render, hardware or provider jobs.',sourceSnapshot:tracked.map(file=>({file,bytes:Buffer.byteLength(sources[file]),normalizedTextSha256:sha(sources[file])})),assets,wiring:{controller:w.controller,fields:w.catalog,assignments:w.assignments,actionCases:w.cases.map(({body,...entry})=>entry),observedMotionSelections:Object.fromEntries(Object.entries(w.motionSelections).map(([key,value])=>[key,value?{condition:value.condition,anchor:value.anchor,clips:value.clips}:null])),catalogueClips,existingUncataloguedClips:assets.clips.filter(c=>!catalogueClips.includes(c.name)).map(c=>c.name)},bridgeProbe:bridge,actions,counts,limitations:[
  'present+integrated means a source selector exists with existing clips and/or a procedural pose. It does not prove the active Editor scene, WebGL build, visible quality or smartphone performance.',
  'Missing authored clip families refer to the audited 34 original + 2 pilot clips; an absent authored clip is not a source gap when an existing/procedural alternative is already selected.',
  'integrated-quality-defect identifies demonstrable generic/partial source substitutions; visual severity is unmeasured.',
  'No new rig/contact-phase measurement, rendered screenshot/video, device performance measurement or licence decision.',
  'Source parser depends on explicit clip names and branch syntax. Observed carrier and lateral keeper selectors are inspected separately from p.action labels; unknown syntax remains unproven.',
  'Native tackle result/legality remains authoritative; origin/outcome details are not inferred as new gameplay states.'
 ],recommendedFixes:recommendations(actions)};
}
function selfTest(sources,report){
 const checks=[];function test(name,fn){fn();checks.push(name);}
 test('Actual original GLB hash matches frozen manifest',()=>assert.ok(report.assets.original.hashMatches));
 test('34 actual original clips, 28 actual rig joints',()=>{assert.equal(report.assets.clips.filter(c=>c.asset.endsWith('.glb')).length,34);assert.equal(report.assets.joints.length,28);});
 test('Binary clip list agrees with existing baseline',()=>assert.ok(report.assets.clipNamesMatchPrior));
 test('Pilot asset hashes and prefab binding root',()=>{for(const f of report.assets.pilotAssets)assert.ok(f.exists&&f.hashMatches,f.file);for(const c of report.assets.clips.filter(c=>c.asset.endsWith('.anim')))assert.ok(!c.bindsActorRoot&&c.allBindingsUnderExistingPrefabRoot,c.name);});
 test('Clip assignment maps all current original/pilot catalogued fields',()=>{const w=wiring(sources);for(const field of w.catalog)assert.ok(w.assignments[field],field);});
 test('Parser separates world actions from demo actions',()=>{const w=wiring(sources);assert.ok(w.cases.some(c=>c.action==='save'));assert.ok(w.cases.some(c=>c.action==='pass'));assert.ok(!w.cases.some(c=>c.action==='prepare-shot'));});
 test('All requested families represented and exact classifications',()=>{const ids=new Set(report.actions.map(a=>a.id));for(const id of ['slide-front','slide-side','slide-back','slide-gain','slide-deflect','slide-miss','slide-foul','slide-recover','standing-tackle','foul-victim','foul-offender','stumble-general','volley','header','keeper-shuffle','keeper-catch','keeper-rebound','keeper-throw','throw-in','corner','free-kick','penalty'])assert.ok(ids.has(id),id);for(const a of report.actions)assert.ok(['present+integrated','present-unwired','integrated-quality-defect','missing','unproven'].includes(a.classification));assert.equal(ids.size,report.actions.length);});
 test('Clip presence alone never proves Unity wiring',()=>{const w=wiring(sources),clone={...w,cases:w.cases.filter(c=>c.action!=='pass')};const rows=actionRows(sources,report.assets,clone,report.bridgeProbe);assert.equal(rows.find(a=>a.id==='pass').classification,'present-unwired');});
 test('Picture contract actually projects pass/contact and prioritises foul',()=>{const result=bridgeProbe(sources);assert.equal(result.foulPrecedence,'foulOffender');assert.ok(Array.isArray(result.slide.position));});
 test('Current keeper lateral and observed carrier branches are integrated without invented actions',()=>{
  for(const id of ['keeper-shuffle','dribble']){const row=report.actions.find(a=>a.id===id);assert.equal(row.classification,'present+integrated',id);assert.ok(row.modeEvidence,id);}
  assert.ok(!wiring(sources).cases.some(c=>c.action==='keeperShuffle'));
 });
 function mutatedRow(file,before,after,id){assert.ok(sources[file].includes(before),'Mutation anchor: '+before);const mutated={...sources,[file]:sources[file].replace(before,after)};return actionRows(mutated,report.assets,wiring(mutated),report.bridgeProbe).find(a=>a.id===id);}
 test('Removing measured Lateral guard leaves shuffle clip present but unwired',()=>assert.equal(mutatedRow(P,'Math.Abs(locomotion.Lateral)>.72f','true','keeper-shuffle').classification,'present-unwired'));
 test('Removing shuffle assignment leaves catalogue presence insufficient',()=>assert.equal(mutatedRow(P,'pose.clip=keeperShuffleClip;','pose.clip=keeperClip;','keeper-shuffle').classification,'present-unwired'));
 test('Removing observed Lateral calculation invalidates measured shuffle proof',()=>assert.equal(mutatedRow(L,'Lateral=actual>','unusedLateral=actual>','keeper-shuffle').classification,'present-unwired'));
 test('Removing carrier guard leaves running clip present but dribble unwired',()=>assert.equal(mutatedRow(P,'locomotionAction&&carrying&&locomotion.Speed>.2f','locomotionAction&&notCarrying&&locomotion.Speed>.2f','dribble').classification,'present-unwired'));
 test('Removing carrier foot-reach selection invalidates dribble proof',()=>assert.equal(mutatedRow(P,'pose.contact=(right>0||left>0)&&ballView.position.y<.45f;','unusedContact=(right>0||left>0)&&ballView.position.y<.45f;','dribble').classification,'present-unwired'));
 test('Recommendations distinguish integrated P1 visual gates from missing source selectors',()=>{
  for(const id of ['slide-front','slide-recover','foul-offender','keeper-shuffle','standing-tackle','dribble'])assert.ok(report.recommendedFixes.some(r=>r.scope==='visual-review'&&r.actionIds.includes(id)),id);
  const w=wiring(sources),removed={...w,cases:w.cases.filter(c=>c.action!=='tackle')},rows=actionRows(sources,report.assets,removed,report.bridgeProbe);
  assert.ok(recommendations(rows).some(r=>r.scope==='source-gap'&&r.actionIds.includes('standing-tackle')));
 });
 return{passed:checks.length,checks,method:'Node asset decoding, source mapping and actual picture-contract execution; negative selector mutations in memory only; no Unity runtime tests'};
}
function markdown(report){const title='# A02: reproduzierbarer Asset-/Animationsaudit\n\n';return title+'Stand: '+report.generatedAt+'. **Keine neue visuelle Abnahme.** Vollständige JSON-Evidenz in `report.json`; jede Aktion enthält Trigger-, Clip-, Rig-, Kontakt- und Übergangsbelege.\n\n'+`Original: ${report.assets.clips.filter(c=>c.asset.endsWith('.glb')).length} Clips, ${report.assets.joints.length} Gelenke; ${report.assets.clips.filter(c=>c.asset.endsWith('.anim')).length} zusätzliche Pilotclips. Katalog enthält ${report.wiring.catalogueClips.length} nachweislich vorhandene Clips.\n\n`+Object.entries(report.counts).map(([k,v])=>`${k}: ${v}`).join('; ')+'.\n\n'+report.actions.map(a=>`- **${a.id} — ${a.label}: ${a.classification}.** ${a.limitation||a.contact}`).join('\n')+'\n\n## Grenzen\n\n'+report.limitations.map(l=>'- '+l).join('\n')+'\n';}
function main(){const args=process.argv.slice(2),sources=takeSources(),report=build(sources);if(args.includes('--self-test'))report.tests=selfTest(sources,report);const after=takeSources();for(const f of tracked)assert.equal(sha(after[f]),sha(sources[f]),'Source changed during audit; rerun: '+f);const idx=args.indexOf('--out'),relative=idx>=0?args[idx+1]:'outputs/3d-quality/animation-audit/'+report.generatedAt.replaceAll(':','-').replaceAll('.','-');assert.ok(relative,'Missing --out path');const allowed=path.resolve(root,'outputs/3d-quality/animation-audit'),out=path.resolve(root,relative);assert.ok(out.startsWith(allowed+path.sep),'Output must stay below own audit directory');assert.ok(!fs.existsSync(out),'Preserve old audit runs: choose a new --out directory');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'README.md'),markdown(report));console.log(JSON.stringify({output:path.relative(root,out).replaceAll('\\','/'),counts:report.counts,actualOriginalClips:report.assets.clips.filter(c=>c.asset.endsWith('.glb')).length,pilotClips:report.assets.clips.filter(c=>c.asset.endsWith('.anim')).length,catalogueClips:report.wiring.catalogueClips.length,tests:report.tests?.passed,slideProjected:report.bridgeProbe.slideProjected,slideRecoveryProjected:report.bridgeProbe.recoveryProjected,renderedEvidence:false},null,2));}
if(require.main===module){
 if(process.argv.includes('--help'))console.log('Read-only animation source/asset audit. No Unity or rendered proof.\nUsage: node work/platform/animation/quality-audit.cjs [--self-test] [--out outputs/3d-quality/animation-audit/<new-run>]\nAn existing output directory is never overwritten.');
 else main();
}
module.exports={build,wiring,bridgeProbe,actionRows,selfTest,takeSources};
