'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../..');
const mime={'.html':'text/html','.js':'text/javascript','.cjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.glb':'model/gltf-binary','.wasm':'application/wasm','.data':'application/octet-stream','.wav':'audio/wav','.fbx':'application/octet-stream'};
const routes=[['/source/',path.join(root,'dist')],['/unity/',path.join(root,'outputs/platform/unity-web')],['/results/',path.join(root,'outputs/platform')],['/probe-assets/',path.join(root,'outputs/platform/assets')],['/contacts/',path.join(root,'work/match-next/contacts')],['/shared/',path.join(root,'work/match-next/shared')],['/demo/',path.join(__dirname,'web')]];
function sourceId(){const hash=crypto.createHash('sha256');for(const name of fs.readdirSync(path.join(root,'dist')).filter(n=>n.endsWith('.js')).sort()){hash.update(name);hash.update(fs.readFileSync(path.join(root,'dist',name)));}for(const rel of ['work/match-next/shared/contract.js','work/platform/engine-probe/web/native.js','work/platform/engine-probe/web/physics.js','work/platform/engine-probe/web/play.js','work/platform/engine-probe/web/play-catalog.json','work/platform/engine-probe/web/pose.js','work/platform/engine-probe/web/net.js','work/platform/engine-probe/web/camera.js','work/platform/engine-probe/web/physics-catalog.json']){const file=path.join(root,rel);if(fs.existsSync(file))hash.update(fs.readFileSync(file));}return hash.digest('hex');}
function createServer(){return http.createServer((req,res)=>{
 try{let url=new URL(req.url,'http://127.0.0.1'),route=url.pathname==='/'?'/demo/index.html':decodeURIComponent(url.pathname);
 if(route==='/native/index.html'){let html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8').replace('<head>','<head><base href="/source/">');html=html.replace('</body>','<script>window.D6ProbeSourceId="'+sourceId()+'";</script><script src="/shared/contract.js"></script><script src="/demo/camera.js?v=play-1"></script><script src="/demo/net.js?v=play-1"></script><script src="/demo/physics.js?v=play-1"></script><script src="/demo/play.js?v=play-1"></script><script src="/demo/pose.js?v=play-1"></script><script src="/demo/scene.js?v=play-1"></script><script src="/demo/native.js?v=play-1"></script></body>');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-cache');res.end(html);return;}
 const mapping=routes.find(([prefix])=>route.startsWith(prefix));if(!mapping){res.writeHead(404);res.end('Nicht gefunden');return;}
 const [prefix,base]=mapping;const file=path.resolve(base,route.slice(prefix.length)||'index.html');if(!file.startsWith(base+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end('Noch nicht verfügbar');return;}
 res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control',/\.(?:glb|png|jpg|wasm|data|js)$/.test(file)?'private, max-age=3600':'no-cache');
 if(route==='/source/index.html'){res.setHeader('Cache-Control','no-cache');res.end(fs.readFileSync(file,'utf8').replace('<head>','<head><script>window.D6UnityMatchUrl="/source/unity-match/runtime.html";</script>'));return;}
 if(route.startsWith('/source/')&&/\.(?:html|js|css)$/.test(file))res.setHeader('Cache-Control','no-cache');
 if(route==='/source/player-user-bootstrap-v112.js'){const script=fs.readFileSync(file,'utf8');const marker="mask.flipY=false;";if(!script.includes(marker))throw Error('Asset capture marker missing');res.end(script.replace(marker,'window.D6ProbeGltf=gltf;'+marker));return;}
 if(file.endsWith('.br'))res.setHeader('Content-Encoding','br');if(file.endsWith('.gz'))res.setHeader('Content-Encoding','gzip');
 fs.createReadStream(file).pipe(res);
 }catch(e){res.writeHead(400);res.end('Ungültige Anfrage');}
});}
module.exports={createServer};if(require.main===module){const port=Number(process.env.D6_PROBE_PORT||4300);createServer().listen(port,'127.0.0.1',()=>console.log('Doppel 6 Vergleich: http://127.0.0.1:'+port));}
