'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {chromium}=require(process.env.D6_PLAYWRIGHT||'C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const native=require('./native-adapter.cjs'),{installObserver}=require('./observer.cjs');
const ROOT=path.resolve(__dirname,'../../..');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
function manifest(root){const entries=[];function walk(dir){for(const ent of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const file=path.join(dir,ent.name);if(ent.isDirectory())walk(file);else if(ent.isFile()){const bytes=fs.readFileSync(file);entries.push({path:path.relative(root,file).replaceAll('\\','/'),bytes:bytes.length,sha256:hash(bytes)})}}}walk(root);return {sha256:hash(JSON.stringify(entries)),files:entries}}
function stats(xs){if(!xs.length)return {count:0};const s=[...xs].sort((a,b)=>a-b),q=p=>s[Math.min(s.length-1,Math.ceil(s.length*p)-1)];return {count:s.length,p50:q(.5),p95:q(.95),p99:q(.99),max:s.at(-1),mean:s.reduce((a,b)=>a+b,0)/s.length,over33_34Ms:s.filter(x=>x>33.34).length,over50Ms:s.filter(x=>x>50).length,over100Ms:s.filter(x=>x>100).length}}
function rendererInfo(){const r=typeof v98Scene!=='undefined'?v98Scene?.renderer:null;let canvas=r?.domElement,gl=r?.getContext(),owner=location.href;
 function find(doc){for(const candidate of doc.querySelectorAll('canvas')){const ctx=candidate.getContext('webgl2')||candidate.getContext('webgl');if(ctx){canvas=candidate;gl=ctx;owner=doc.location.href;return true}}for(const frame of doc.querySelectorAll('iframe')){try{if(frame.contentDocument&&find(frame.contentDocument))return true}catch{}}return false}
 if(!gl)find(document);if(!gl)return {available:false};const ext=gl.getExtension('WEBGL_debug_renderer_info'),name=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);return {available:true,owner,renderer:name,vendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),software:/swiftshader|llvmpipe|software|WARP|Microsoft Basic Render/i.test(name),gpuTimerQueryExtensionAvailable:Boolean(gl.getExtension('EXT_disjoint_timer_query_webgl2')||gl.getExtension('EXT_disjoint_timer_query')),gpuExecutionDurationMs:null,gpuExecutionDurationNote:'Not instrumented; renderer submission intervals are not GPU execution durations.',pixelRatio:r?.getPixelRatio(),canvas:{width:canvas.width,height:canvas.height},antialias:gl.getContextAttributes().antialias,shadows:r?.shadowMap.enabled,calls:r?.info.render.calls,triangles:r?.info.render.triangles,quality:typeof v98Scene!=='undefined'?v98Scene?.quality:null};}
function args(){const opts={seconds:30,adapter:'native',headless:false,view:'3d',label:'w0-browser',url:null};for(let i=2;i<process.argv.length;i++){const key=process.argv[i].replace(/^--/,'');opts[key]=key==='headless'?true:process.argv[++i]}opts.seconds=Number(opts.seconds);if(!(opts.seconds>0&&opts.seconds<=7200))throw Error('seconds must be 1..7200');return opts}
async function resourceEvidence(page){const frames=[];for(const frame of page.frames()){frames.push(await frame.evaluate(isMain=>({frameURL:location.href,frameScope:isMain?'dashboard-or-native-main':'engine-child',timeOrigin:performance.timeOrigin,navigation:performance.getEntriesByType('navigation')[0]?.toJSON(),resources:performance.getEntriesByType('resource').map(r=>r.toJSON())}),frame===page.mainFrame()))}return {navigation:frames[0].navigation,frameNavigations:frames.map(({resources,...frame})=>frame),resources:frames.flatMap(frame=>frame.resources.map(r=>({...r,frameURL:frame.frameURL,frameScope:frame.frameScope,timeOrigin:frame.timeOrigin}))),resourceAccounting:'Resource entries from each loaded frame; child navigation counted only through parent iframe resource, never added again from child navigation entry.'}}
async function run(){
 const opts=args(),runId=`${new Date().toISOString().replaceAll(':','-').replaceAll('.','-')}-${opts.label}`,out=path.join(ROOT,'outputs/platform/performance',runId);fs.mkdirSync(out,{recursive:true});
 const sourceRoot=path.resolve(opts['source-root']||path.join(ROOT,'dist')),source=manifest(sourceRoot);fs.writeFileSync(path.join(out,'source-manifest.json'),JSON.stringify(source,null,2));
 const extraSources=String(opts['freeze-roots']||'').split(',').filter(Boolean).map(root=>({root:path.resolve(root),manifest:manifest(path.resolve(root))}));fs.writeFileSync(path.join(out,'extra-source-manifests.json'),JSON.stringify(extraSources,null,2));
 let server;if(!opts.url){const probe=opts.adapter==='probe';server=require(probe?'../engine-probe/server.cjs':'../../ui-redesign/serve.cjs').createServer();if(!probe)server.prependListener('request',(_req,res)=>res.setHeader('Cache-Control','public, max-age=3600'));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));opts.url=`http://127.0.0.1:${server.address().port}${probe?'/demo/?engine='+(opts.engine||'browser'):'/source/index.html'}`;opts.cachePolicy=probe?'unchanged demo server headers':'perf-only frozen local responses: public, max-age=3600'}
 const executablePath=process.env.D6_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
 const report={schema:1,runId,started:new Date().toISOString(),options:opts,sourceRoot,sourceSha256:source.sha256,environment:{platform:os.platform(),release:os.release(),architecture:os.arch(),cpu:os.cpus()[0]?.model,logicalCpus:os.cpus().length,totalMemoryBytes:os.totalmem(),node:process.version,executablePath,backgroundLoad:'uncontrolled local workstation; other apps may be active',power:'not measured',thermal:'not available',androidHardware:false,emulated:false},loads:[],samples:[],errors:[],limitations:['GPU duration, GPU memory and temperature not available','rAF intervals measure callback cadence; native draw intervals measure actual renderer submissions','CPU wrapper timings overlap; cannot be summed','Local localhost network only; OS disk cache not flushed','No Android hardware acceptance or full-match claim from a short run']};
 report.environment.physicalDisplayRefreshHz=null;report.environment.displayRefreshNote=opts.headless?'Headless run; physical monitor refresh rate unavailable. rAF samples describe callback cadence only.':'Physical monitor refresh rate not queried; rAF samples describe callback cadence only.';report.environment.configuredEngineTargetFps=opts.engine==='unity'?60:null;
 let browser;
 try{
  browser=await chromium.launch({executablePath,headless:opts.headless,args:[],ignoreDefaultArgs:['--enable-unsafe-swiftshader']});report.environment.browserVersion=browser.version();
  const context=await browser.newContext({viewport:{width:1440,height:950},deviceScaleFactor:1}),page=await context.newPage();report.consoleMessages=[];report.renderErrors=[];page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(['warning','error'].includes(m.type())){const entry={type:m.type(),text:m.text()};report.consoleMessages.push(entry);if(/GL_INVALID_|WebGL: too many errors|Can't add component|NullReferenceException|MissingReferenceException|RuntimeError/.test(entry.text))report.renderErrors.push(entry)}});
  const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Performance.enable');
  try{const session=await browser.newBrowserCDPSession();report.environment.gpu=(await session.send('SystemInfo.getInfo')).gpu}catch(e){report.environment.gpuUnavailable=e.message}
  const isNative=opts.adapter==='native';
  for(const cache of String(opts.caches||'cold,warm').split(',')){
   if(cache==='cold')await cdp.send('Network.clearBrowserCache');
   const at=performance.now();await page.goto(opts.url,{waitUntil:'load',timeout:120000});
   if(isNative)await page.waitForFunction(()=>window.D6UserModelStatus==='ready',null,{timeout:120000});else await page.waitForFunction(()=>window.D6Probe?.ready===true,null,{timeout:120000});
   const assetsReadyMs=performance.now()-at;
   if(isNative)await native.prepare(page,{view:opts.view});
   else if(opts.scenario){const configs=await page.evaluate(async({id,duration,matrix})=>{const catalog=await fetch('/contacts/catalog.json').then(r=>r.json()),selected=catalog.find(s=>s.id===id);if(!selected)throw Error('Unknown scenario '+id);const scenarios=matrix?catalog.filter(s=>s.provenance.family===selected.provenance.family):[selected];return scenarios.map(s=>({scenario:{...s,...(duration?{duration:Number(duration)}:{})},seed:617}))},{id:opts.scenario,duration:opts['scenario-duration'],matrix:opts['cycle-matrix']==='true'});report.probeConfigs=configs;report.probeConfigsSha256=hash(JSON.stringify(configs));await page.evaluate(async configs=>{window.__D6StressConfigs=configs;await window.D6Probe.load(configs[0])},configs)}
   await page.bringToFront();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
   report.loads.push({cache,assetsReadyMs,firstPreparedFrameMs:performance.now()-at,...await resourceEvidence(page)});
   const load=report.loads.at(-1);load.transferBytes=load.resources.reduce((sum,r)=>sum+r.transferSize,0);load.zeroTransferResourceCount=load.resources.filter(r=>r.transferSize===0&&r.decodedBodySize>0).length;load.cacheReuseObserved=load.zeroTransferResourceCount>0;
   const initial=isNative?await native.snapshot(page):await page.evaluate(()=>window.D6Probe.snapshot?.()??window.D6Probe.stats?.()??{});
   const renderer=await page.evaluate(rendererInfo);if(!isNative){const evidence=require('../qa/image-evidence.cjs').imageEvidence(await page.locator('#frame').screenshot());load.firstValidatedImageMs=performance.now()-at;load.image=evidence;if(evidence.greenPixelFraction<=.02||evidence.distinctColors<=100)throw Error('Probe image is blank or field not visibly rendered');}if(report.renderErrors.length)throw Error('Renderer errors during loading; no performance acceptance');
   const initialEngineStats=!isNative?await page.evaluate(()=>window.D6Probe.stats()):null;
   await page.evaluate(installObserver,{native:isNative,detailed:true});if(isNative)await native.start(page);else await page.evaluate(()=>window.D6Probe.start());
   if(!isNative&&opts.cycle==='true')await page.evaluate(({minimumCycleSeconds})=>{const stress={cycles:0,minimumCycleSeconds,activeSimSeconds:0,nativeClockAdvancedSeconds:null,observedActiveWallSeconds:0,observedFinishedIdleWallSeconds:0,samples:0,errors:[],transitions:[],started:performance.now()},configs=window.__D6StressConfigs;let prev=null,prevAt=performance.now(),cycleStarted=prevAt,finishedAt=null,stopped=false,timer=0,pending=Promise.resolve();
    async function poll(){const now=performance.now(),current=await window.D6Probe.snapshot();stress.samples++;if(prev){if(prev.running)stress.observedActiveWallSeconds+=(now-prevAt)/1000;if(prev.finished)stress.observedFinishedIdleWallSeconds+=(now-prevAt)/1000;if(current.elapsed>=prev.elapsed)stress.activeSimSeconds+=current.elapsed-prev.elapsed;if(Number.isFinite(current.nativeElapsed)){stress.nativeClockAdvancedSeconds??=0;if(current.nativeElapsed>=prev.nativeElapsed)stress.nativeClockAdvancedSeconds+=current.nativeElapsed-prev.nativeElapsed}}prev=current;prevAt=now;if(current.finished&&finishedAt===null)finishedAt=now;
     if(current.finished&&!stopped&&now-cycleStarted>=minimumCycleSeconds*1000){const at=performance.now();if(configs)await window.D6Probe.load(configs[(stress.cycles+1)%configs.length]);else await window.D6Probe.reset();await window.D6Probe.start();stress.cycles++;stress.transitions.push({atSeconds:(at-stress.started)/1000,cycleWallSeconds:(at-cycleStarted)/1000,finishObservedAfterSeconds:(finishedAt-cycleStarted)/1000,loadAndStartMs:performance.now()-at,completedScenario:current.scenarioId,completedElapsed:current.elapsed});prev=await window.D6Probe.snapshot();prevAt=performance.now();cycleStarted=prevAt;finishedAt=null;}
    }
    function schedule(){timer=setTimeout(()=>{pending=poll().catch(e=>stress.errors.push(e.message)).finally(()=>{if(!stopped)schedule()})},100)}schedule();window.__D6Stress={async finish(){stopped=true;clearTimeout(timer);await pending;return {...stress,ended:performance.now(),activeTimeMethod:'100ms polling; observed active wall time is approximate; simulation deltas counted separately'}}};
   },{minimumCycleSeconds:Number(opts['cycle-min-seconds']||0)});
   const memories=[],snapshots=[],engineFramesMs=[],start=performance.now();let lastEngineRenderCount=initialEngineStats?.renderCount??initialEngineStats?.frames??null,droppedEngineIntervals=0,lastProgressMinute=0;
   while(performance.now()-start<opts.seconds*1000){await page.waitForTimeout(Math.min(5000,Math.max(1,opts.seconds*1000-(performance.now()-start))));
    const atSeconds=(performance.now()-start)/1000;if(report.renderErrors.length)throw Error('Renderer errors during sample; measurement rejected');let metrics;try{metrics=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]))}catch{}
    memories.push({atSeconds,metrics,jsHeap:await page.evaluate(()=>performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize,limit:performance.memory.jsHeapSizeLimit}:null)});
    snapshots.push({atSeconds,value:isNative?await native.snapshot(page):await page.evaluate(async()=>({snapshot:await window.D6Probe.snapshot(),stats:await window.D6Probe.stats()}))});
    if(!isNative){const engineStats=snapshots.at(-1).value.stats||{},count=engineStats.renderCount??engineStats.frames,intervals=engineStats.frameTimesMs;
     if(Array.isArray(intervals)&&Number.isFinite(count)){const expected=lastEngineRenderCount===null?intervals.length:count>=lastEngineRenderCount?count-lastEngineRenderCount:count;const fresh=intervals.slice(-Math.min(expected,intervals.length));if(expected>0)engineFramesMs.push(...fresh);droppedEngineIntervals+=Math.max(0,expected-intervals.length);lastEngineRenderCount=count;engineStats.frameTimesMs={count:intervals.length,retainedFresh:fresh.length};if(Array.isArray(engineStats.renderMs))engineStats.renderMs={count:engineStats.renderMs.length};}
    }
    const progress={runId,cache,atSeconds,requestedSeconds:opts.seconds,engine:opts.engine||'native',actualRenderIntervals:engineFramesMs.length,droppedEngineIntervals,jsHeapUsedBytes:metrics?.JSHeapUsedSize,latest:snapshots.at(-1).value};fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify(progress,null,2));if(Math.floor(atSeconds/60)>lastProgressMinute){lastProgressMinute=Math.floor(atSeconds/60);console.log(JSON.stringify({runId,cache,atSeconds,actualRenderIntervals:engineFramesMs.length,jsHeapUsedBytes:metrics?.JSHeapUsedSize}))}
   }
   const stress=!isNative&&opts.cycle==='true'?await page.evaluate(()=>window.__D6Stress.finish()):null;const raw=await page.evaluate(()=>window.__D6Measure.finish());if(isNative)await native.stop(page);else await page.evaluate(()=>window.D6Probe.pause());
   await page.screenshot({path:path.join(out,`${cache}.png`)});
   raw.engineFramesMs=engineFramesMs;const sample={cache,initial,renderer,stress,wallSeconds:(raw.ended-raw.started)/1000,rafMs:stats(raw.rafMs),drawIntervalsMs:stats(raw.drawIntervalsMs),engineDrawIntervalsMs:stats(engineFramesMs),droppedEngineIntervals,cpuMs:Object.fromEntries(Object.entries(raw.cpuMs).map(([k,v])=>[k,stats(v)])),longTasks:stats(raw.longTasks.map(x=>x.duration)),visibility:raw.visibility,memories,snapshots};report.samples.push(sample);fs.writeFileSync(path.join(out,`${cache}-raw.json`),JSON.stringify(raw));
   const final=snapshots.at(-1)?.value;console.log(JSON.stringify({cache,seconds:sample.wallSeconds,renderer:renderer.renderer,frames:isNative?sample.drawIntervalsMs:sample.engineDrawIntervalsMs,cycles:stress?.cycles,final:isNative?final:{scenarioId:final?.snapshot?.scenarioId,elapsed:final?.snapshot?.elapsed,tick:final?.snapshot?.tick,players:final?.snapshot?.actors?.length}}));
  }
  report.sourceUnchanged=manifest(sourceRoot).sha256===source.sha256;report.extraSources=extraSources.map(s=>({root:s.root,sha256:s.manifest.sha256,unchanged:manifest(s.root).sha256===s.manifest.sha256}));
 }catch(error){report.failure=error.stack;process.exitCode=1}finally{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));report.finished=new Date().toISOString();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(`Report: ${path.relative(ROOT,out)}`)}
 if(report.failure)throw Error(report.failure);
}
module.exports={manifest,stats};if(require.main===module)run().catch(error=>{console.error(error);process.exitCode=1});
