'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=path.resolve(__dirname,'../../../..'),files=['dist/ui-flutlicht/tokens.css','dist/ui-flutlicht/components.css','dist/ui-flutlicht/components.js','dist/ui-flutlicht/registry.js','dist/ui-flutlicht/views/club.css','dist/ui-flutlicht/views/club.js','work/ui-redesign/packages/U01-E/fixture.js'];
const hashes=()=>Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex')]));
const out=path.join(base,'outputs/ui-redesign/U01-E',new Date().toISOString().replace(/[:.]/g,'-'));
(async()=>{const before=hashes();fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const errors=[],results=[];
 try{const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.setContent('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0"><main id="v61-world-screen"><div class="fl-shell" data-fl-theme="light" style="display:block"><div class="fl-content" id="content"></div></div></main></body></html>');
  for(const file of files){const content=fs.readFileSync(path.join(base,file),'utf8');if(file.endsWith('.css'))await page.addStyleTag({content});else await page.addScriptTag({content});}
  await page.evaluate(()=>{content.innerHTML=flClubMarkup;window.nativeCount=0;window.savedKit=document.querySelector('[data-v81-save-patterns]');savedKit.addEventListener('click',()=>nativeCount++);window.refresh=()=>D6Flutlicht.registry.enhance(content,flClubFixture,{t:s=>s});refresh();refresh()});
  assert.equal(await page.locator('.fl-club-records').count(),2);assert.equal(await page.locator('.fl-club-last-lineup').count(),2);assert.equal(await page.locator('.fl-club-coach-detail .fl-club-records').count(),0);
  assert.equal(await page.locator('[data-v46-view=club] .fl-club-record-board').first().locator('li').count(),3);assert.deepEqual(await page.locator('[data-v46-view=club] .fl-club-record-board').first().locator('.fl-club-record-rank').allTextContents(),['1','1','3']);
  assert.equal(await page.locator('[data-v68-player="removed"]').count(),0);assert.equal(await page.locator('[data-fl-club-id="fixture-other"] .fl-club-empty').count(),3);
  const profile=page.locator('[data-v46-view=club] .fl-club-records [data-v68-player]').first();await profile.focus();await page.evaluate(()=>{window.focused=document.activeElement;refresh()});assert.equal(await page.evaluate(()=>document.activeElement===focused),true);
  await page.locator('[data-v81-save-patterns]').click();assert.equal(await page.evaluate(()=>nativeCount),1);assert.equal(await page.evaluate(()=>savedKit===document.querySelector('[data-v81-save-patterns]')),true);assert.equal(await page.locator('[data-v81-save-colors]').isDisabled(),true);
  await page.locator('[data-v81-pattern]').selectOption({label:'Einfarbig'});await page.locator('#v67-budget').selectOption('200');await page.evaluate(()=>refresh());assert.equal(await page.locator('[data-v81-pattern]').inputValue(),'Einfarbig');assert.equal(await page.locator('#v67-budget').inputValue(),'200');
  for(const width of [320,390,768,1440])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.evaluate(theme=>document.querySelector('.fl-shell').dataset.flTheme=theme,theme);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}/${theme}`);results.push({width,theme,overflow});if([390,1440].includes(width))await page.screenshot({path:path.join(out,`club-${width}-${theme}.png`),fullPage:true});}
  const labels=JSON.parse(fs.readFileSync(path.join(__dirname,'labels.json'),'utf8'));await page.evaluate(labels=>{D6Flutlicht.registry.enhance(content,flClubFixture,{t:s=>labels[s]||s})},labels);assert.equal(await page.locator('[data-v46-view=club] .fl-club-records h3').textContent(),'All-time top 10');assert.match(await profile.getAttribute('aria-label'),/^Open player profile:/);
  await page.evaluate(()=>{const projection=structuredClone(flClubFixture);projection.club.profiles[0].records.goals=Array.from({length:12},(_,index)=>({playerId:'cap-'+index,name:'<img src=x onerror=alert(1)>',rank:index+1,value:12-index,profileAvailable:true}));D6Flutlicht.registry.enhance(content,projection,{t:s=>s})});assert.equal(await page.locator('[data-v46-view=club] .fl-club-record-board').first().locator('li').count(),10);assert.equal(await page.locator('.fl-club-records img').count(),0);
  assert.deepEqual(errors,[]);assert.deepEqual(hashes(),before);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:true,results,checks:['one record/lineup block per club','no club records in coach profile','equal ranks','missing player not linked','empty records and missing lineup','refresh keeps focus and original kit action node','native kit listener works','disabled color action retained','kit and budget values survive refresh','all native finance/manager/transfer sections preserved'],limitations:['sanitized view fixtures; producer arithmetic and real actions require source tests','no physical device/Safari/screen reader'],hashes:before},null,2));console.log(out);
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
