'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{createServer}=require('../../serve.cjs');
const base=path.resolve(__dirname,'../../../..'),files=['index.html','ui-flutlicht/adapter.js','ui-flutlicht/registry.js','ui-flutlicht/components.js','ui-flutlicht/components.css','ui-flutlicht/views/club.js','ui-flutlicht/views/club.css','world-views-v68.js','world-kits-ui-v81.js','i18n-v75.js'];
const hashes=()=>Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(base,'dist',file))).digest('hex')]));
const out=path.join(base,'outputs/ui-redesign/U01-E',`source-${new Date().toISOString().replace(/[:.]/g,'-')}`);
(async()=>{const before=hashes();fs.mkdirSync(out,{recursive:true});const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const errors=[],checks=[];
 try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/source/index.html`);
  const setup=await page.evaluate(async()=>{v61CurrentCareer=await v61StoreNewCareer(v61CreateCareer('GER-2','fl-club-source','Fixture Manager'));const career=v61CurrentCareer,club=v66Own(career),own=club.roster[0],other=career.world.clubs.find(c=>c.id!==club.id&&!c.simulationOnly),former=other.roster[0];
   // Isolated in-memory historical fixture. It is not written to a real user's save.
   own.seasons=[{season:1,clubId:club.id,games:10,goals:5,assists:0,minutes:900}];own.history=[{fixtureId:'fixture-overlap',season:1,clubId:club.id,goals:99,minutes:90}];
   former.seasons=[{season:1,clubId:club.id,games:20,goals:5,assists:0,minutes:1800}];
   const games=v62Fixtures(career).filter(f=>f.homeId===club.id||f.awayId===club.id).sort((a,b)=>a.day-b.day);for(const f of games.slice(0,2))f.result={homeGoals:1,awayGoals:0,penalties:null,winnerId:f.homeId};const fixture=games[0];fixture.lineups=[career.world.clubs.find(c=>c.id===fixture.homeId).roster.slice(0,6).map(p=>p.pid),career.world.clubs.find(c=>c.id===fixture.awayId).roster.slice(0,6).map(p=>p.pid)];
   v61RenderCareer(career);v61SetCareerTab('club',false);return{ownId:club.id,ownPid:own.pid,formerPid:former.pid,otherId:other.id};});
  await page.locator('[data-v46-view=club] .fl-club-records').waitFor();
  const projection=await page.evaluate(()=>D6Flutlicht.adapter.project(v61CurrentCareer).club);const own=projection.profiles.find(c=>c.id===setup.ownId);
  assert.equal(own.records.goals.find(p=>p.playerId===setup.ownPid).value,5,'overlapping historical records must not count twice');assert.equal(own.records.appearances.find(p=>p.playerId===setup.formerPid).value,20,'former player must count for original club');assert.equal(own.records.goals[0].rank,1);assert.equal(own.records.goals[1].rank,1);assert.equal(own.lastLineup.olderThanLastMatch,true);assert.equal(own.lastLineup.players.length,6);
  const snapshot=await page.evaluate(()=>JSON.stringify(v61CurrentCareer));const formerButton=page.locator(`[data-v46-view=club] .fl-club-records [data-v68-player="${setup.formerPid}"]`).first();await formerButton.click();await page.locator('dialog[data-fl-player-id][open]').waitFor();assert.equal(await page.locator('dialog[open][data-fl-player-id]').getAttribute('data-fl-player-id'),setup.formerPid);await page.locator('dialog[open] [data-v61-close]').click();
  await page.evaluate(otherId=>v68OpenDetail('club',otherId,null),setup.otherId);await page.locator('[data-v68-detail][data-fl-club-id] .fl-club-records').waitFor();await page.locator('[data-v68-detail] [data-v68-back]').click();await page.locator('[data-v46-view=club]').waitFor({state:'visible'});
  assert.equal(await page.locator('[data-v46-view=club] [data-v81-kits] > summary .v81-shirt').count(),4);assert.equal(await page.locator('[data-v81-save-patterns]').isDisabled(),true,'kit edit remains locked before transfer window');
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`club source ${width}`);checks.push({width,overflow});if([390,1440].includes(width))await page.screenshot({path:path.join(out,`club-${width}.png`),fullPage:true});}
  assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),snapshot,'club view interactions changed career data');assert.deepEqual(errors,[]);assert.deepEqual(hashes(),before,'relevant sources changed during test');
  fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:true,checks,assertions:['source producer excludes overlapping history under summary','former-club player included','equal ranks','latest recorded six-player lineup rather than invented XI','newer missing-lineup notice','native former-player profile route','foreign-club detail and back','four native kits and edit lock','unchanged career after view actions','stable hashes'],limitations:['historical source cases seeded in isolated test memory','kit write/payment/save/reload end-to-end owned by I00','no physical hardware/Safari/screen-reader proof'],hashes:before},null,2));console.log(out);
 }finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});

