'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require('C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {createServer}=require('../../serve.cjs');
const base=path.resolve(__dirname,'../../../..'),build=path.join(base,'outputs/Doppel-6-Fussballmanager.html');
const index=fs.readFileSync(path.join(base,'dist/index.html'),'utf8');
const sourceFiles=[...new Set(['index.html',...Array.from(index.matchAll(/(?:src|href)="([^"?#]+\.(?:js|css))"/g),m=>m[1]).filter(s=>!/^https?:/.test(s))])];
const hashFile=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const hashes=()=>Object.fromEntries([...sourceFiles.map(f=>['dist/'+f,hashFile(path.join(base,'dist',f))]),['outputs/Doppel-6-Fussballmanager.html',hashFile(build)],['outputs/index.html',hashFile(path.join(base,'outputs/index.html'))]]);
const out=path.join(base,'outputs/ui-redesign/I00-save-check',new Date().toISOString().replace(/[:.]/g,'-'));
const digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function inspect(page){return page.evaluate(()=>{const c=v61CurrentCareer,own=c&&v66Own(c);return {id:c?.id,sponsorId:own?.sponsorId,balance:own?.balance,ledger:own?.ledger,phase:c?.world.market.phase,day:c?.world.market.day,world:c?.world,error:v61StorageError,status:document.querySelector('[data-v64-storage-status]')?.textContent,confirmed:v61StorageConfirmed.map(c=>({id:c.id,world:c.world})),currentVisible:!v61WorldScreen.hidden,flActive:document.body.classList.contains('fl-active')};});}
async function run(browser,url,target){
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});if(target==='offline')await context.setOffline(true);
 const page=await context.newPage(),errors=[],network=[],checks=[],findings=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
 const dir=path.join(out,target);fs.mkdirSync(dir,{recursive:true});
 try{
  await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>v61StorageReady);
  assert.equal(await page.evaluate(()=>v61ReadCareers().length),0,'fresh context must not contain user careers');
  const initial=await page.evaluate(async()=>{const career=await v61StoreNewCareer(v61CreateCareer('GER-2','save-check-isolated','Speicher Test'));v61CurrentCareer=career;v61RenderCareer(career);return{id:career.id,backend:v61StorageDb?'indexedDB':'localStorage'};});
  for(const theme of ['light','dark']){await page.emulateMedia({colorScheme:theme});const footer=await page.locator('body>.legal-nav button').first().evaluate(node=>{const s=getComputedStyle(node),rgb=c=>c.match(/[\d.]+/g).slice(0,3).map(Number),lum=c=>rgb(c).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),a=lum(s.color),b=lum(getComputedStyle(document.body).backgroundColor);return{height:node.getBoundingClientRect().height,contrast:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};});assert(footer.height>=44);assert(footer.contrast>=4.5);checks.push({case:'native footer '+theme,...footer});}
  // Fault injection only in the isolated test process; no source or real storage edits.
  await page.evaluate(()=>{window.saveCheckFail=false;window.saveCheckPuts=0;const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(saveCheckFail&&this.name==='careers'){saveCheckPuts++;throw new DOMException('Isolierter Test: Speicher voll','QuotaExceededError')}return put.apply(this,args)};const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(saveCheckFail&&key===v61WorldKey){saveCheckPuts++;throw new DOMException('Isolierter Test: Speicher voll','QuotaExceededError')}return set.call(this,key,value)};});
  const beforeSponsor=await inspect(page);const sponsor=await page.locator('[data-v66-sponsor]').first().getAttribute('data-v66-sponsor');await page.evaluate(()=>saveCheckFail=true);await page.locator('[data-v66-sponsor]').first().click();await page.waitForFunction(()=>Boolean(v61StorageError)&&!v61StorageWriting);
  const failed=await inspect(page);assert.equal(failed.sponsorId,sponsor);assert.equal(digest(failed.confirmed),digest(beforeSponsor.confirmed),'failed write altered confirmed storage');assert.equal(await page.evaluate(()=>saveCheckPuts>0),true);
  const storageStatusVisible=await page.locator('[data-v64-storage-status]').isVisible(),nativeRetryVisible=await page.locator('[data-v64-storage-retry]').isVisible();
  checks.push({case:'Q-PHASE05 controlled sponsor write failure',backend:initial.backend,confirmedUnchanged:true,storageStatusVisible,nativeRetryVisible,balanceBefore:beforeSponsor.balance,balanceAfter:failed.balance,ledgerBefore:beforeSponsor.ledger.length,ledgerAfter:failed.ledger.length,error:failed.error,status:failed.status});
  if(!storageStatusVisible||!nativeRetryVisible)findings.push({priority:'P1',issue:'Native storage failure status/retry hidden by Flutlicht header',sequence:'New career > enable isolated write failure > choose sponsor',storageStatusVisible,nativeRetryVisible});
  await page.screenshot({path:path.join(dir,'write-failure.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  const recovery=await page.locator('.v64-match-menu-panel').boundingBox();assert(recovery&&recovery.x>=0&&recovery.x+recovery.width<=390.5,'mobile recovery panel must fit');assert(await page.locator('[data-v64-storage-retry]').isVisible());
  const rescueDownload=page.waitForEvent('download');await page.locator(`[data-v64-rescue="${initial.id}"]`).click();const rescue=await rescueDownload,rescuePath=path.join(dir,'rescue.json');await rescue.saveAs(rescuePath);const rescueData=JSON.parse(fs.readFileSync(rescuePath,'utf8'));assert.equal(rescueData.rescue,true);assert.equal(digest(rescueData.save.world),digest(failed.world));checks.push({case:'mobile failure and actual rescue export',panel:recovery,worldIdentical:true});await page.screenshot({path:path.join(dir,'mobile-recovery.png')});await page.setViewportSize({width:1440,height:1000});
  // The visible settings save action must report failure without leaving the career.
  await page.locator('.fl-sidebar [data-fl-route=settings]').click();await page.locator('[data-fl-settings-action=manage]').click();await page.locator('.fl-settings-error:not([hidden])').waitFor();assert.equal(await page.locator('.fl-settings-error').isVisible(),true);const manageError=await page.locator('.fl-settings-error').textContent();const retained=await inspect(page);assert.equal(retained.currentVisible,true);assert.equal(retained.flActive,true);assert.equal(digest(retained.world),digest(failed.world),'failed settings save changed domain state');await page.screenshot({path:path.join(dir,'settings-save-error.png'),fullPage:true});
  await page.evaluate(()=>saveCheckFail=false);await page.locator('[data-v64-storage-retry]').click();await page.waitForFunction(()=>!v61StorageError&&!v61StorageWriting);assert.equal(await page.locator('.fl-shell').isVisible(),true);checks.push({case:'native retry action',errorCleared:true,careerRemainsOpen:true});await page.locator('[data-fl-settings-action=manage]').click();await page.locator(`[data-v61-open="${initial.id}"]`).waitFor({state:'visible'});await page.evaluate(()=>v61WaitForStorage());
  const confirmed=await page.evaluate(id=>v61StorageConfirmed.find(c=>c.id===id),initial.id);assert.equal(digest(confirmed.world),digest(failed.world),'retry double-booked or changed world');checks.push({case:'Q-SAVE02 settings save error and retry',errorVisible:true,error:manageError,careerRetained:true,retrySaved:true,worldUnchangedOnRetry:true,sponsorEntries:confirmed.world.clubs.find(c=>c.id===confirmed.manager.managedClubId).ledger.filter(r=>r.id===`${sponsor}:fixed`).length});
  const downloadPromise=page.waitForEvent('download');await page.locator(`[data-v61-export="${initial.id}"]`).click();const download=await downloadPromise;const exportPath=path.join(dir,'export.json');await download.saveAs(exportPath);const exported=JSON.parse(fs.readFileSync(exportPath,'utf8'));assert.equal(exported.format,'world');assert.equal(exported.schema,14);assert.equal(digest(exported.save.world),digest(confirmed.world));
  await page.locator('.v46-extras > summary').click();const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.locator('#import-save').click()]);await chooser.setFiles(exportPath);await page.waitForFunction(()=>document.querySelector('#import-status').textContent==='Vereinswelt erfolgreich importiert.');const imports=await page.evaluate(()=>v61ReadCareers());assert.equal(imports.length,2);const imported=imports.find(c=>c.id!==initial.id);assert.ok(imported);assert.equal(digest(imported.world),digest(confirmed.world));assert.equal(imported.manager.name,confirmed.manager.name);checks.push({case:'Q-SAVE01 native export/import',download:download.suggestedFilename(),bytes:fs.statSync(exportPath).size,sourceId:initial.id,importId:imported.id,uniqueIds:true,worldIdentical:true,managerIdentical:true});
  const beforeInvalid=await page.evaluate(()=>JSON.stringify(v61ReadCareers()));const invalid={...exported,save:{...exported.save,world:{...exported.save.world,clubs:[]}}};await page.locator('#import-file').setInputFiles({name:'invalid-world.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.querySelector('#import-status').textContent.includes('unvollständig oder beschädigt'));const invalidError=await page.locator('#import-status').textContent();assert.equal(await page.locator('#import-status').isVisible(),true);assert.equal(await page.evaluate(()=>JSON.stringify(v61ReadCareers())),beforeInvalid);checks.push({case:'Q-SAVE02 invalid import',visibleError:invalidError,storedCareersUnchanged:true});await page.screenshot({path:path.join(dir,'import-invalid.png'),fullPage:true});
  await page.reload({waitUntil:'load'});await page.waitForFunction(()=>v61StorageReady);await page.locator(`[data-v61-open="${imported.id}"]`).click();await page.locator('.fl-shell').waitFor();const reloaded=await inspect(page);assert.equal(digest(reloaded.world),digest(confirmed.world));assert.equal(reloaded.id,imported.id);checks.push({case:'Q-SAVE01 reload imported save',worldIdentical:true,importedCareerIdPreserved:true});assert.deepEqual(errors,[]);if(target==='offline')assert.deepEqual(network,[]);
  const evidence={target,passed:findings.length===0,checks,findings,pageErrors:errors,httpRequests:network.length,exportWorldSHA256:digest(exported.save.world),confirmedWorldSHA256:digest(confirmed.world),reloadWorldSHA256:digest(reloaded.world),limitations:['isolated synthetic career; no real user saves','initial creation uses native domain API; export/import/retry use actual UI','controlled IndexedDB/localStorage write exception; no real disk exhaustion','desktop Edge; no Safari or physical-device proof']};fs.writeFileSync(path.join(dir,'checks.json'),JSON.stringify(evidence,null,2));return evidence;
 }catch(error){fs.writeFileSync(path.join(dir,'failure.json'),JSON.stringify({error:String(error),stack:error.stack,checks,findings,pageErrors:errors},null,2));await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true}).catch(()=>{});throw error;}finally{await context.close();}
}
(async()=>{fs.mkdirSync(out,{recursive:true});const before=hashes();fs.writeFileSync(path.join(out,'hashes-before.json'),JSON.stringify(before,null,2));const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const results=[];for(const [target,url]of [['source',`http://127.0.0.1:${server.address().port}/source/index.html`],['offline',pathToFileURL(build).href]]){const result=await run(browser,url,target);results.push(result);console.log(target+': '+JSON.stringify({passed:result.passed,findings:result.findings}));}const after=hashes();fs.writeFileSync(path.join(out,'hashes-after.json'),JSON.stringify(after,null,2));assert.deepEqual(after,before,'source/build changed during frozen test');fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:results.every(r=>r.passed),stableHashes:true,results},null,2));console.log(out);}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(error=>{console.error(error);console.error(out);process.exitCode=1});

