'use strict';
const crest='<svg viewBox="0 0 50 60" aria-hidden="true"><path d="M3 3h44v32L25 57 3 35Z" fill="#41664f" stroke="#e9bb5d" stroke-width="3"/><text x="25" y="34" text-anchor="middle" fill="white" font-size="17">FC</text></svg>';
const logo='<svg viewBox="0 0 200 60" aria-hidden="true"><rect width="200" height="60" rx="5" fill="#e9bb5d"/><text x="100" y="37" text-anchor="middle" font-family="Arial" font-size="23" fill="#20352e">TESTWERKE</text></svg>';
const translations={'Nächste Begegnung':'Next fixture','Hauptsponsor':'Main sponsor','Vertrag ansehen':'View contract','Letzte Ligaspiele':'Recent league matches','Noch keine Ligaspiele erfasst':'No league matches recorded yet','Ältestes Ergebnis zuerst':'Oldest result first','Aktuell auf Kurs':'Currently on track','Endgültig erreicht':'Achieved','Ziel offen':'Target open','Status nicht erfasst':'Status not recorded','Zahlungsstatus nicht erfasst':'Payment status not recorded','Bereits bezahlt':'Already paid','Noch nicht bezahlt':'Not paid yet','Vereinsprofil':'Club profile','Erreichte Sponsorboni werden am Saisonende bezahlt.':'Achieved sponsor bonuses are paid at the end of the season.'};
function fixture(language='de',status='track'){
 const en=language==='en',names=en?['Football Club With A Very Long Name','United Riverside Athletic Association']:['Fußballclub mit einem außergewöhnlich langen Namen','Spielvereinigung Beispielstadt am langen Fluss'];
 const recent=['win','draw','loss','win','win'].map((outcome,index)=>({outcome,label:(en?{win:'W',draw:'D',loss:'L'}:{win:'S',draw:'U',loss:'N'})[outcome],detail:`${index+1}: ${en?'Home':'Heim'} · Testgegner · 2:1`}));
 const goals=[{label:en?'Top 3 finish':'Top-3-Abschluss',bonusLabel:'+ 350 Credits',onCourse:status==='track',achieved:status==='achieved',paid:false},{label:en?'Cup semi-final':'Pokalhalbfinale',bonusLabel:'+ 150 Credits',onCourse:true,achieved:true,paid:status==='paid'}];
 if(status==='unknown')Object.assign(goals[0],{onCourse:null,achieved:null,paid:null});
 const side=(name,label)=>`<div class="v49-club"><span class="v49-side">${label}</span><strong><span>${name}</span></strong><div class="v49-form"><b>S</b></div></div>`;
 const html=`<div data-v46-view="overview"><section class="v68-digest"><h3>${en?'Since your last advance':'Seit deinem letzten Fortschritt'}</h3><button data-v68-club="other">${en?'Club news':'Vereinsnachrichten'}</button></section><section class="v66-transfer-day"><button data-v66-go-transfers>Transfers</button></section><section class="v62-season"><h2>${en?'Season':'Saison'} 4</h2><section class="v49-match-preview v62-next-opponent"><p>Legacy fixture heading</p><div class="v49-fixture">${side(names[0],en?'Home':'Heim')}<span class="v62-first-leg-score"><small>${en?'First leg':'Hinspiel'}</small><strong>1 : 0</strong></span>${side(names[1],en?'Away':'Auswärts')}</div><div class="v62-duels"><h4>${en?'Recent meetings':'Letzte Duelle'}</h4><div class="win"><small>S3 · 08.09. · H</small><strong>2:1</strong></div></div></section><section class="v62-season v66-sponsors v66-sponsor-selected"><div class="v66-sponsor-main"><div><h3>Sponsor</h3>${logo}</div><p><small>${en?'Fixed fee received':'Fixum erhalten'}</small><strong>600 Credits</strong></p></div><div class="v66-sponsor-bonuses"><h4>${en?'Bonus targets':'Bonusziele'}</h4><ul class="v66-sponsor-goals">${goals.map(g=>`<li><span>${g.label}</span><strong>${g.bonusLabel}</strong></li>`).join('')}</ul></div></section><h3>${en?'Your competitions':'Deine Wettbewerbe'}</h3><div class="v62-own-competitions"><details open><summary>Liga</summary><table><thead><tr><th>${en?'Club':'Verein'}</th><th>P</th></tr></thead><tbody>${Array.from({length:6},(_,i)=>`<tr><td>Club ${i+1}</td><td>${18-i}</td></tr>`).join('')}</tbody></table></details></div></section><section class="v62-season v67-season-show" id="v67-season-show"><h2>${en?'Season review':'Saisonrückblick'}</h2><div class="v67-show-grid"><article>Sportbilanz</article><article>Titel / Awards</article></div><div class="v67-show-actions"><button data-v67-review-back>${en?'Back':'Zurück'}</button><button data-v67-review-next>${en?'Next':'Weiter'}</button></div><p id="v67-transition-error" role="alert"></p></section><section id="v124-budget" class="v62-season v67-transition"><label>Budget <select id="v67-budget"><option>200 Credits</option></select></label><button data-v124-budget>${en?'Confirm funding':'Jugendförderung bezahlen'}</button></section></div>`;
 return{html,translations:en?translations:{},overview:{fixture:{dateLabel:'15.09.',seasonLabel:en?'Season 4':'Saison 4',competitionLabel:'Liga',roundLabel:en?'Matchday 7':'Spieltag 7',home:{id:'home',name:names[0],crestHTML:crest,rankLabel:'2.',recent:status==='missing'?[]:recent},away:{id:'away',name:names[1],crestHTML:crest,rankLabel:'3.',recent:recent.slice(-2)}},sponsor:{name:'Testwerke',logoHTML:logo,goals}}};
}
module.exports={fixture};
