const fs=require('fs');
require('./generate-3d-documentation.cjs').generate();
const readSource=file=>fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');
let html=readSource('dist/index.html');
const flutlicht=require('./ui-redesign/shared/assets.cjs');
for(const file of flutlicht.styles)if(html.includes(`href="ui-flutlicht/${file}"`))html=html.replace(`<link rel="stylesheet" href="ui-flutlicht/${file}">`,()=>`<style>${readSource('dist/ui-flutlicht/'+file)}</style>`);
for(const file of flutlicht.scripts)if(html.includes(`src="ui-flutlicht/${file}"`))html=html.replace(`<script src="ui-flutlicht/${file}"></script>`,()=>`<script>${readSource('dist/ui-flutlicht/'+file)}</script>`);
for(const file of ['style.css','manager.css','world-start-v61.css','world-economy-v66.css','world-youth-v67.css','world-views-v68.css','progress-v58.css','player-tactics-ui.css','world-tactics-layout-v156.css'])html=html.replace(`<link rel="stylesheet" href="${file}">`,`<style>${readSource('dist/'+file)}</style>`);
for(const file of ['game.js','manager-v11.js','identity-v12.js','season-v13.js','halftime-v14.js','finance-v15.js','transfer-v16.js','qol-v17.js','player-card-v18.js','dashboard-v19.js','screen-wake-v20.js','match-clock-v21.js','club-history-v22.js','formation-label-v23.js','lineup-ux-v24.js','presentation-v25.js','sponsor-fix-v26.js','dashboard-order-v27.js','transfer-result-v28.js','transfer-actions-v29.js','sale-profile-v30.js','season-finale-v31.js','dashboard-layout-v32.js','youth-v33.js','season-roster-v34.js','transfer-sections-v35.js','youth-direct-v36.js','transfer-order-v37.js','legal-v38.js','awards-v40.js','cup-v41.js','penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','main-menu-v46.js','match-report-v47.js','next-match-v49.js','set-pieces-v50.js','status-icons-v51.js','player-status-v51.js','strength-v55.js','opponent-profile-v54.js','pitch-v55.js','pitch-v56.js','pitch-v57.js','progress-v58.js','live-player-v59.js','ai-career-v60.js'])html=html.replace(`<script src="${file}"></script>`,()=>`<script>${readSource('dist/'+file)}</script>`);
for(const file of ['world-catalog-v61.js','world-competition-v62.js','world-coaches-v63.js','world-match-v64.js','world-nationalities-v79.js','player-generation.js','player-effective-abilities.js','player-freshness.js','player-load-candidate-v158.js','player-development.js','player-aging.js','player-role-suitability.js','player-position-routine.js','player-tactic-transitions.js','player-match-ratings.js','player-tactics-ui.js','world-player-roles-v154.js','world-player-performance-v155.js','world-tactics-ui-v156.js','world-player-foundation-v153.js','world-player-load-v158.js','player-foundation-preview-v153.js','world-foundation-v61.js','world-match-ui-v64.js','world-physical-v65.js','world-economy-v66.js','world-transfer-list-v72.js','world-market-ui-v66.js','world-transfer-list-ui-v72.js','world-youth-manager-v67.js','world-payments-v124.js','world-youth-ui-v67.js','world-payments-ui-v124.js','world-honours-v74.js','world-views-v68.js','world-career-plan-v64.js','world-grid-touch-v71.js','match-presentation-v74.js','i18n-v75.js','world-kits-ui-v81.js','world-goal-scene-v83.js','world-goal-banner-v84.js','world-pitch-layout-v92.js','camera-prototype/vendor/three-r160.min.js','player-model-v105.js','pitch-scene-v98.js','world-pitch-actions-v99.js','pitch-motion-v102.js','world-backpedal-v108.js','world-corner-ball-v109.js','world-ball-motion-v110.js','world-space-passes-v150.js','world-attack-flow-v152.js','world-offensive-quality-v157.js','match-shot-choice-v159.js','world-football-flow-v159.js','match-ball-events-v117.js','world-pitch3d-v98.js','world-goal-replay-v103.js','world-unity-v151.js','world-3d-documentation-data-v134.js','world-3d-help-v134.js'])html=html.replace(`<script src="${file}"></script>`,()=>`<script>${readSource('dist/'+file)}</script>`);
const sounds={};for(const name of ['pass','shot','whistle','crowd','cheer','net'])sounds[name]=fs.readFileSync('dist/camera-prototype/audio/'+name+'.wav').toString('base64');
// Offline model loading uses embedded modules and assets from the authoritative source tree.
const moduleData=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64'),vendor='dist/camera-prototype/vendor/';
const gltfModule=moduleData(readSource(vendor+'GLTFLoader.js').replace('./BufferGeometryUtils.js',moduleData(readSource(vendor+'BufferGeometryUtils.js'))));
html=html.replace('./camera-prototype/vendor/three.module.js',moduleData(readSource(vendor+'three.module.js')));
for(const file of ['player-user-motion-v108.js','player-user-ball-actions-v111.js','player-ball-events-v111.js','player-user-meshy-v107.js','player-user-bootstrap-v112.js']){
 let code=readSource('dist/'+file);
 if(file==='player-user-bootstrap-v112.js')code=code.replace('./camera-prototype/vendor/GLTFLoader.js',gltfModule).replace('players/football-v130.glb','data:model/gltf-binary;base64,'+fs.readFileSync('dist/players/football-v130.glb').toString('base64')).replace('players/calibration-v130.json','data:application/json;base64,'+fs.readFileSync('dist/players/calibration-v130.json').toString('base64')).replace('players/cloth-mask.png','data:image/png;base64,'+fs.readFileSync('dist/players/cloth-mask.png').toString('base64'));
 html=html.replace(`<script src="${file}"></script>`,()=>`<script>${code}</script>`);
}
html=html.replace('</head>',()=>'<script>window.D6_AUDIO='+JSON.stringify(sounds)+';</script></head>');
for(const asset of [...new Set(html.match(/(?:referees|trophies|sprites|crests)\/[a-z0-9-]+\.png/g)||[])]){
 const data=fs.readFileSync('dist/'+asset).toString('base64');
 html=html.replaceAll(asset,`data:image/png;base64,${data}`);
}
// The published HTTP build loads its matching Unity runtime; file: retains the
// existing local bridge. The query also separates runtime caches by release.
html=html.replace('</head>',()=>'<script>if(location.protocol==="http:"||location.protocol==="https:")window.D6UnityMatchUrl=new URL("unity-match/runtime.html?v=111",document.baseURI).href;</script></head>');
html=html.replace(/PROTOTYP \d+\b/g,'PROTOTYP 111');
fs.mkdirSync('outputs',{recursive:true});
fs.writeFileSync('outputs/index.html',html);fs.writeFileSync('outputs/Doppel-6-Fussballmanager.html',html);
