const fs=require('fs');
const readSource=file=>fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');
let html=readSource('dist/index.html');
for(const file of ['style.css','manager.css','world-start-v61.css','world-economy-v66.css','world-youth-v67.css','world-views-v68.css','progress-v58.css'])html=html.replace(`<link rel="stylesheet" href="${file}">`,`<style>${readSource('dist/'+file)}</style>`);
for(const file of ['game.js','manager-v11.js','identity-v12.js','season-v13.js','halftime-v14.js','finance-v15.js','transfer-v16.js','qol-v17.js','player-card-v18.js','dashboard-v19.js','screen-wake-v20.js','match-clock-v21.js','club-history-v22.js','formation-label-v23.js','lineup-ux-v24.js','presentation-v25.js','sponsor-fix-v26.js','dashboard-order-v27.js','transfer-result-v28.js','transfer-actions-v29.js','sale-profile-v30.js','season-finale-v31.js','dashboard-layout-v32.js','youth-v33.js','season-roster-v34.js','transfer-sections-v35.js','youth-direct-v36.js','transfer-order-v37.js','legal-v38.js','awards-v40.js','cup-v41.js','penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','main-menu-v46.js','match-report-v47.js','next-match-v49.js','set-pieces-v50.js','status-icons-v51.js','player-status-v51.js','strength-v55.js','opponent-profile-v54.js','pitch-v55.js','pitch-v56.js','pitch-v57.js','progress-v58.js','live-player-v59.js','ai-career-v60.js'])html=html.replace(`<script src="${file}"></script>`,()=>`<script>${readSource('dist/'+file)}</script>`);
for(const file of ['world-catalog-v61.js','world-competition-v62.js','world-coaches-v63.js','world-match-v64.js','world-nationalities-v79.js','world-foundation-v61.js','world-match-ui-v64.js','world-physical-v65.js','world-economy-v66.js','world-transfer-list-v72.js','world-market-ui-v66.js','world-transfer-list-ui-v72.js','world-youth-manager-v67.js','world-youth-ui-v67.js','world-honours-v74.js','world-views-v68.js','world-career-plan-v64.js','world-grid-touch-v71.js','match-presentation-v74.js','i18n-v75.js','world-kits-ui-v81.js','world-goal-scene-v83.js','world-goal-banner-v84.js','world-pitch-layout-v92.js','camera-prototype/vendor/three-r160.min.js','pitch-scene-v98.js','world-pitch-actions-v99.js','world-pitch3d-v98.js'])html=html.replace(`<script src="${file}"></script>`,()=>`<script>${readSource('dist/'+file)}</script>`);
const sounds={};for(const name of ['pass','shot','whistle','crowd','cheer','net'])sounds[name]=fs.readFileSync('dist/camera-prototype/audio/'+name+'.wav').toString('base64');
html=html.replace('</head>',()=>'<script>window.D6_AUDIO='+JSON.stringify(sounds)+';</script></head>');
for(const asset of [...new Set(html.match(/(?:referees|trophies|sprites|crests)\/[a-z0-9-]+\.png/g)||[])]){
 const data=fs.readFileSync('dist/'+asset).toString('base64');
 html=html.replaceAll(asset,`data:image/png;base64,${data}`);
}
for(let version=9;version<=98;version++)html=html.replaceAll(`PROTOTYP ${String(version).padStart(2,'0')}`,'PROTOTYP 99');
fs.mkdirSync('outputs',{recursive:true});
fs.writeFileSync('outputs/index.html',html);fs.writeFileSync('outputs/Doppel-6-Fussballmanager.html',html);
