const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const durationMs=(Number(process.env.SOAK_SECONDS)||600)*1000,startWall=Date.now(),files=['game.js','manager-v11.js','identity-v12.js','season-v13.js'];
const aggregate={matches:0,seasons:0,worlds:0,homeGoals:0,awayGoals:0,homeShots:0,awayShots:0,draws:0,homeWins:0,awayWins:0,scoreless:0,maxTeamGoals:0,maxTotalGoals:0,maxShots:0,minPossession:100,maxPossession:0,minRating:10,maxRating:0,minPassRate:100,maxPassRate:0,minDuelRate:100,maxDuelRate:0,maxTopScorer:0,rankCounts:[0,0,0,0,0,0],anomalies:{playerCount:0,goalsOverShots:0,keeperMath:0,statBounds:0,table:0,scorerTotals:0,identity:0,extremeScore:0,extremePossession:0,zeroShots:0},samples:[]};
function sample(type,data){aggregate.anomalies[type]++;if(aggregate.samples.length<40)aggregate.samples.push({type,...data})}
function makeElement(){return{innerHTML:'',textContent:'',hidden:false,value:'',disabled:false,dataset:{},className:'',style:{setProperty(){}},classList:{toggle(){},remove(){}},setAttribute(){},addEventListener(){},append(){},before(){},prepend(){},focus(){},scrollIntoView(){},insertAdjacentElement(){},insertAdjacentHTML(){},querySelector(){return makeElement()},querySelectorAll(){return[]},closest(){return null}}}
function makeContext(){
 const elements=new Map(),storage=new Map(),scoreboard=[makeElement(),makeElement()];
 const document={documentElement:makeElement(),querySelector:s=>{if(!elements.has(s))elements.set(s,makeElement());return elements.get(s)},querySelectorAll:s=>s==='.scoreboard span'?scoreboard:[],createElement:makeElement,createTextNode:t=>t};
 elements.set('#club-name',Object.assign(makeElement(),{value:`FC Test ${aggregate.worlds+1}`}));elements.set('#club-primary',Object.assign(makeElement(),{value:'#2244aa'}));elements.set('#club-secondary',Object.assign(makeElement(),{value:'#ffcc22'}));
 const context={document,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{scrollTo(){}},location:{protocol:'file:'},crypto,structuredClone,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},alert:m=>{throw Error(m)},confirm:()=>true,fetch:async()=>({ok:true}),console:{log(){},warn(){},error(){}},Math};vm.createContext(context);
 for(const file of files)vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);vm.runInContext(`$('#club-form').onsubmit({preventDefault(){}})`,context);aggregate.worlds++;
 const identity=vm.runInContext(`(()=>{const all=[activeSave.keeper,...activeSave.squad,...activeSave.world.teams.flatMap(team=>team.roster)];return{count:all.length,unique:new Set(all.map(player=>player.name)).size,valid:all.every(player=>nationData[player.nation])}})()`,context);
 if(identity.count!==54||identity.unique!==54||!identity.valid)sample('identity',identity);return context;
}
function playMatch(context){
 const setup=vm.runInContext(`(()=>{const shapes=['compact','balanced','bold'];formation=shapes[Math.floor(Math.random()*shapes.length)];press=Math.random()<.5?1:0;direct=Math.random()<.5?1:0;const choose=line=>activeSave.squad.filter(player=>player.line===line).sort((a,b)=>b.fresh-a.fresh||Math.random()-.5);activeSave.lineup=[...choose('def').slice(0,2),...choose('mid').slice(0,2),...choose('att').slice(0,1)].map(player=>player.n);syncLineupFromSquad();players.forEach((player,index)=>player.cell=formations[formation].cells[index]);start();return{total:match.people.length,home:match.people.filter(player=>player.t===0).length,away:match.people.filter(player=>player.t===1).length}})()`,context);
 if(setup.total!==12||setup.home!==6||setup.away!==6)sample('playerCount',{match:aggregate.matches+1,...setup});
 vm.runInContext(`for(let tick=0;tick<4000&&running;tick++)step(.08,.08);if(running)throw Error('Match hängt')`,context);
 const result=vm.runInContext(`(()=>{const pass=match.people.filter(player=>player.stats.passes>=3).map(player=>player.stats.passComplete/player.stats.passes*100),duel=match.people.filter(player=>player.stats.duels>=2).map(player=>player.stats.duelsWon/player.stats.duels*100),ratings=match.people.map(player=>player.stats.rating),keepers=match.people.filter(player=>player.keeper).map(player=>({faced:player.stats.faced,saves:player.stats.saves,conceded:player.stats.conceded})),bounds=match.people.some(player=>player.stats.passComplete>player.stats.passes||player.stats.duelsWon>player.stats.duels||player.stats.rating<3.5||player.stats.rating>9.5);return{score:[...match.score],shots:[...match.shots],possession:[...match.possession],pass,duel,ratings,keepers,bounds}})()`,context);
 aggregate.matches++;const[h,a]=result.score,[hs,as]=result.shots,totalPoss=result.possession[0]+result.possession[1],pos=totalPoss?result.possession[0]/totalPoss*100:50;
 aggregate.homeGoals+=h;aggregate.awayGoals+=a;aggregate.homeShots+=hs;aggregate.awayShots+=as;aggregate.maxTeamGoals=Math.max(aggregate.maxTeamGoals,h,a);aggregate.maxTotalGoals=Math.max(aggregate.maxTotalGoals,h+a);aggregate.maxShots=Math.max(aggregate.maxShots,hs,as);aggregate.minPossession=Math.min(aggregate.minPossession,pos);aggregate.maxPossession=Math.max(aggregate.maxPossession,pos);aggregate.minRating=Math.min(aggregate.minRating,...result.ratings);aggregate.maxRating=Math.max(aggregate.maxRating,...result.ratings);
 if(result.pass.length){aggregate.minPassRate=Math.min(aggregate.minPassRate,...result.pass);aggregate.maxPassRate=Math.max(aggregate.maxPassRate,...result.pass)}if(result.duel.length){aggregate.minDuelRate=Math.min(aggregate.minDuelRate,...result.duel);aggregate.maxDuelRate=Math.max(aggregate.maxDuelRate,...result.duel)}
 if(h===a)aggregate.draws++;else if(h>a)aggregate.homeWins++;else aggregate.awayWins++;if(h+a===0)aggregate.scoreless++;
 if(h>hs||a>as)sample('goalsOverShots',{score:result.score,shots:result.shots});if(result.keepers.some(keeper=>keeper.saves+keeper.conceded!==keeper.faced))sample('keeperMath',{score:result.score,keepers:result.keepers});if(result.bounds)sample('statBounds',{score:result.score});if(h>=6||a>=6)sample('extremeScore',{score:result.score,shots:result.shots});if(pos<15||pos>85)sample('extremePossession',{pos:+pos.toFixed(1),score:result.score});if(hs===0||as===0)sample('zeroShots',{score:result.score,shots:result.shots});
}
function finishSeason(context){
 const season=vm.runInContext(`(()=>{const totalGF=activeSave.table.reduce((sum,team)=>sum+team.gf,0),totalGA=activeSave.table.reduce((sum,team)=>sum+team.ga,0),playerGoals=[activeSave.keeper,...activeSave.squad,...activeSave.world.teams.flatMap(team=>team.roster)].reduce((sum,player)=>sum+(storedSeason(player,activeSave.seasonNumber).goals||0),0),top=leaguePlayerRows()[0],snapshot=activeSave.clubHistory.find(item=>item.number===activeSave.seasonNumber);return{number:activeSave.seasonNumber,played:activeSave.table.map(team=>team.played),totalGF,totalGA,playerGoals,points:activeSave.table.reduce((sum,team)=>sum+team.pts,0),top:top.goals,rank:snapshot.rank,history:activeSave.clubHistory.length}})()`,context);
 aggregate.seasons++;aggregate.maxTopScorer=Math.max(aggregate.maxTopScorer,season.top);aggregate.rankCounts[season.rank-1]++;
 if(!season.played.every(value=>value===10)||season.totalGF!==season.totalGA||season.points<60||season.points>90||season.history!==season.number)sample('table',season);if(season.playerGoals!==season.totalGF)sample('scorerTotals',season);
}
let nextProgress=startWall+60000;
while(Date.now()-startWall<durationMs){
 const context=makeContext();
 for(let season=0;season<3&&Date.now()-startWall<durationMs;season++){
  for(let round=0;round<10&&Date.now()-startWall<durationMs;round++)playMatch(context);
  if(vm.runInContext('activeSave.currentRound',context)===10){finishSeason(context);if(season<2)vm.runInContext('startNextSeason()',context)}
 }
 if(Date.now()>=nextProgress){console.log(JSON.stringify({progressSeconds:Math.round((Date.now()-startWall)/1000),matches:aggregate.matches,seasons:aggregate.seasons,anomalies:Object.values(aggregate.anomalies).reduce((a,b)=>a+b,0)}));nextProgress+=60000}
}
aggregate.elapsedSeconds=(Date.now()-startWall)/1000;aggregate.averages={goalsPerMatch:+((aggregate.homeGoals+aggregate.awayGoals)/aggregate.matches).toFixed(3),homeGoals:+(aggregate.homeGoals/aggregate.matches).toFixed(3),awayGoals:+(aggregate.awayGoals/aggregate.matches).toFixed(3),homeShots:+(aggregate.homeShots/aggregate.matches).toFixed(3),awayShots:+(aggregate.awayShots/aggregate.matches).toFixed(3),drawPercent:+(aggregate.draws/aggregate.matches*100).toFixed(2),scorelessPercent:+(aggregate.scoreless/aggregate.matches*100).toFixed(2)};
for(const key of['minPossession','maxPossession','minRating','maxRating','minPassRate','maxPassRate','minDuelRate','maxDuelRate'])aggregate[key]=+aggregate[key].toFixed(2);
console.log('SOAK_RESULT='+JSON.stringify(aggregate));
