const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const elements=new Map(),storage=new Map(),scoreboard=[];
function element(){return{innerHTML:'',textContent:'',hidden:false,value:'',disabled:false,dataset:{},className:'',style:{setProperty(){}},classList:{toggle(){},remove(){}},setAttribute(){},addEventListener(){},append(){},before(){},prepend(){},focus(){},scrollIntoView(){},insertAdjacentElement(){},insertAdjacentHTML(){},querySelector(){return element()},querySelectorAll(){return[]},closest(){return null}}}
scoreboard.push(element(),element());const document={documentElement:element(),querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll:s=>s==='.scoreboard span'?scoreboard:[],createElement:element,createTextNode:t=>t};
elements.set('#club-name',Object.assign(element(),{value:'FC Halbzeit'}));elements.set('#club-primary',Object.assign(element(),{value:'#2244aa'}));elements.set('#club-secondary',Object.assign(element(),{value:'#ffcc22'}));
const context={document,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{scrollTo(){}},location:{protocol:'file:'},crypto,structuredClone,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},alert:m=>{throw Error(m)},confirm:()=>true,fetch:async()=>({ok:true}),console,Math};vm.createContext(context);
for(const file of['game.js','manager-v11.js','identity-v12.js','season-v13.js','halftime-v14.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);vm.runInContext(`$('#club-form').onsubmit({preventDefault(){}});start();for(let tick=0;tick<3000&&!match.halftimeBreakDone;tick++)step(.08,.08)`,context);
let state=vm.runInContext(`({elapsed:match.elapsed,pause:match.halftimePause,label:$('#board-label').textContent,overlay:$('#overlay-title').textContent,clock:$('#clock').textContent,owner:match.owner,flight:match.flight})`,context);state=JSON.parse(JSON.stringify(state));assert.equal(state.elapsed,37.5);assert(state.pause>0&&state.pause<=2);assert.equal(state.label,'HALBZEIT');assert.equal(state.overlay,'HALBZEIT');assert.equal(state.clock,'45′');assert.equal(state.owner,null);assert.equal(state.flight,null);
vm.runInContext(`step(0,2.1)`,context);state=vm.runInContext(`({pause:match.halftimePause,label:$('#board-label').textContent,flightTeam:match.flight?.team,homeHalf:match.people.filter(p=>p.t===0&&!p.keeper).every(p=>p.y>=.54),awayHalf:match.people.filter(p=>p.t===1&&!p.keeper).every(p=>p.y<=.46)})`,context);assert.deepEqual(JSON.parse(JSON.stringify(state)),{pause:0,label:'LIVE',flightTeam:1,homeHalf:true,awayHalf:true});
vm.runInContext(`for(let tick=0;tick<3000&&running;tick++)step(.08,.08);if(running)throw Error('Match hängt')`,context);assert.equal(vm.runInContext('match.elapsed',context),75);assert.equal(vm.runInContext(`$('#clock').textContent`,context),'90′');assert.equal(vm.runInContext('match.halftimeBreakDone',context),true);
console.log('PASS: Halbzeitpfiff bei 45:00, Abpfiff bei 90:00, Zwei-Sekunden-Pause, eigene Hälften und Gegner-Anstoß');
