const fs=require('fs'),vm=require('vm'),assert=require('assert');
function node(extra={}){return Object.assign({textContent:'',innerHTML:'',className:'',classList:{add(){}},append(...items){this.items=items},querySelector(){return null},querySelectorAll(){return[]},insertAdjacentElement(){},remove(){}},extra)}
const style=node(),summary=node(),details=node(),grid=node({classList:{contains:value=>value==='market-grid'},querySelectorAll:selector=>selector==='.market-card'?[1,2,3,4,5]:[]}),heading=node({textContent:'Ablösefreie Spieler',nextElementSibling:grid}),panel=node({closest(){return null},querySelector:selector=>selector==='.free-agent-dropdown'?null:null,querySelectorAll:selector=>selector==='h3'?[heading]:[]});
let moved=null,inserted=null;const lead=node(),centerGrid=node({classList:{add(value){this.added=value}},querySelector:selector=>selector==='.center-lead'?lead:null}),finance=node({insertAdjacentElement:(where,item)=>{moved={where,item}}});panel.insertAdjacentElement=(where,item)=>{inserted={where,item}};
const clubCenter={querySelector(selector){return selector==='.finance-panel'?finance:selector==='.center-grid'?centerGrid:selector==='.qol-market'?panel:null},querySelectorAll(){return[]}};
const document={head:{append(){}},createElement(tag){if(tag==='style')return style;if(tag==='summary')return summary;if(tag==='details')return details;return node()},querySelectorAll(){return[]}};
const context={document,clubCenter,activeSave:{finance:{gameOver:false}},transferState:()=>({open:false}),renderCenter(){},drawSlots(){},console};vm.createContext(context);vm.runInContext(fs.readFileSync('dist/dashboard-layout-v32.js','utf8'),context);
assert.equal(vm.runInContext('v32PlaceNextMatch()',context),true);assert.equal(moved.where,'beforebegin');assert.equal(moved.item,centerGrid);assert.equal(centerGrid.classList.added,'v32-next-match');
assert.equal(vm.runInContext('v32CollapseFreeAgents()',context),true);assert.equal(inserted.where,'beforebegin');assert.equal(inserted.item,details);assert.equal(details.className,'free-agent-market-dropdown');assert.deepEqual(details.items,[summary,panel]);assert(summary.innerHTML.includes('5 Spieler anzeigen'));
console.log('PASS: Nächster Spieltag vor Finanzen und geschlossenes Transfermarkt-Dropdown für ablösefreie Spieler');
