const fs=require('fs'),vm=require('vm'),assert=require('assert');
const prelude=fs.readFileSync('work/test-v31.cjs','utf8').split('const context=makeContext();')[0];
const makeContext=new Function('require',prelude+'return makeContext')(require);
const context=makeContext();
vm.runInContext(fs.readFileSync('dist/youth-v33.js','utf8'),context);
const run=source=>vm.runInContext(source,context);
const snapshot=source=>JSON.parse(run('JSON.stringify('+source+')'));

run("beginSquadSetup();autoSelectSquad();confirmInitialSquad();selectSponsor('safe');for(const player of[activeSave.keeper,...activeSave.squad,homeKeeper,...players])player.age=18;for(let round=0;round<10;round++){start();match.score=[2,0];finishMatch()}v31SetStage('complete');selectSponsor('safe')");
assert.equal(run('activeSave.seasonNumber'),2);
assert.equal(run('transferState().open'),true);
assert.equal(run('ensureYouth().candidates.length'),12);
assert.equal(run('ensureYouth().candidates.filter(item=>item.scouted).length'),0);
const ids=snapshot('ensureYouth().candidates.map(item=>item.id)');
run('renderCenter()');
assert.deepEqual(snapshot('ensureYouth().candidates.map(item=>item.id)'),ids,'Neuladen darf den Jugendpool nicht neu würfeln');
assert(!run('youthCandidateHTML(ensureYouth().candidates[0])').includes('Potenzial:'),'ungescoutete Werte bleiben verborgen');

run('ensureYouth().candidates[0].player.age=18');
const before=run('ensureFinance(activeSave).balance');
assert.equal(run("scoutYouth('"+ids[0]+"')"),true);
assert.equal(run("scoutYouth('"+ids[0]+"')"),false);
assert.equal(run('ensureFinance(activeSave).balance'),before-40);
assert(run('youthCandidateHTML(ensureYouth().candidates[0])').includes('Potenzial:'));
assert.equal(run("signYouth('"+ids[0]+"')"),true);
assert.equal(run("signYouth('"+ids[0]+"')"),false);
assert.equal(run('ensureFinance(activeSave).balance'),before-140);
assert.equal(run('activeRosterSize()'),10);
assert.equal(run('activeSave.squad.filter(player=>player.youthPotential).length'),1);
assert.equal(run('ensureFinance(activeSave).ledger.filter(entry=>entry.type.startsWith("youth-")).length'),2);

for(let i=1;i<4;i++){run("scoutYouth('"+ids[i]+"')");if(i<3)assert.equal(run("signYouth('"+ids[i]+"')"),true)}
assert.equal(run('activeRosterSize()'),12);
assert.equal(run("signYouth('"+ids[3]+"')"),false,'Kaderlimit gilt auch für die Jugend');
const pid=run('activeSave.squad.find(player=>player.youthPotential).pid');
const youth=snapshot('activeSave.squad.find(player=>player.pid==="'+pid+'")');
assert(youth.youthPotential.pas>=youth.pas);
assert.equal(run('ageAdjustment(activeSave.squad.find(player=>player.pid==="'+pid+'"),"pos")'),0,'kein zweiter Jugendabzug');
run('activeSave.lineup[0]=activeSave.squad.find(player=>player.pid==="'+pid+'").n;syncLineupFromSquad();forceTransferDeadline();saveCurrent()');
run('for(let round=0;round<2;round++){start();match.score=[1,0];finishMatch()}');
const grown=snapshot('activeSave.squad.find(player=>player.pid==="'+pid+'")');
assert.equal(grown.youthGrowth[2].awards,1);
assert.equal(grown.youthGrowth[2].points,2);
assert.equal(grown.seasons.find(item=>item.number===2).games,2);
assert.equal(run('finishMatch()'),undefined);
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").youthGrowth[2].awards'),1,'Abpfiff darf keine zweite Entwicklung buchen');
for(const key of Object.keys(grown.youthPotential))assert(grown[key]<=grown.youthPotential[key]);
run('openSlot(readSlots().find(item=>item.id===activeSave.id))');
assert.deepEqual(snapshot('ensureYouth().candidates.map(item=>item.id)'),ids,'Kandidaten bleiben nach Neuladen gleich');
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").youthGrowth[2].awards'),1,'Entwicklung bleibt gespeichert');
run('for(let round=2;round<10;round++){start();match.score=[1,0];finishMatch()}');
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").youthGrowth[2].awards'),5);
run("v31SetStage('complete');selectSponsor('safe');forceTransferDeadline();saveCurrent();for(let round=0;round<10;round++){start();match.score=[1,0];finishMatch()}");
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").age'),19);
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").youthGrowth[3].awards'),5);
run("v31SetStage('complete');selectSponsor('safe');forceTransferDeadline();saveCurrent();for(let round=0;round<10;round++){start();match.score=[1,0];finishMatch()}");
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").age'),20);
assert.equal(run('activeSave.squad.find(player=>player.pid==="'+pid+'").youthGrowth[4].awards'),3);
assert.equal(run('youthGrowthInterval(24)'),Infinity);
const mature=snapshot('activeSave.squad.find(player=>player.pid==="'+pid+'")');
for(const key of Object.keys(mature.youthPotential))assert(mature[key]<=mature.youthPotential[key]);
console.log('PASS: 12 unbekannte Talente, bezahltes Scouting, mehrere Verpflichtungen, Kaderlimit, gespeicherte Entwicklung über drei Saisonen');
