const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
function makeContext(){const elements=new Map(),storage=new Map(),scoreboard=[];function element(){return{innerHTML:'',textContent:'',hidden:false,value:'',checked:false,disabled:false,dataset:{},className:'',files:[],style:{setProperty(){}},classList:{toggle(){},remove(){},add(){}},firstChild:null,setAttribute(){},addEventListener(){},append(){},before(){},prepend(){},remove(){},focus(){},click(){},scrollIntoView(){},insertAdjacentElement(){},insertAdjacentHTML(){},querySelector(){return element()},querySelectorAll(){return[]},closest(){return null},getContext(){return{clearRect(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},ellipse(){},save(){},clip(){},restore(){},fillText(){}}}}}scoreboard.push(element(),element());const body=element(),document={documentElement:element(),querySelector(selector){if(selector==='body')return body;if(!elements.has(selector))elements.set(selector,element());return elements.get(selector)},querySelectorAll(selector){return selector==='.scoreboard span'?scoreboard:[]},createElement:element,createTextNode:text=>text};elements.set('#club-name',Object.assign(element(),{value:'FC Neustart'}));elements.set('#club-primary',Object.assign(element(),{value:'#2244aa'}));elements.set('#club-secondary',Object.assign(element(),{value:'#ffcc22'}));const customMath=Object.create(Math);customMath.random=Math.random;const context={document,localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},window:{scrollY:0,pageYOffset:0,scrollTo(x,y){this.scrollY=y;this.pageYOffset=y}},location:{protocol:'file:'},crypto,structuredClone,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},alert:message=>{throw Error(message)},confirm:()=>true,fetch:async()=>({ok:true}),console,Math:customMath,Date,Blob:global.Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}}};vm.createContext(context);for(const file of['game.js','manager-v11.js','identity-v12.js','season-v13.js','halftime-v14.js','finance-v15.js','transfer-v16.js','qol-v17.js','player-card-v18.js','dashboard-v19.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);return context}
const context=makeContext();
vm.runInContext('beginSquadSetup();confirmInitialSquad()',context);
assert.equal(vm.runInContext('v17ShowErrors',context),true,'ungültige Gründung zeigt die Vorgabenfehler');
assert.match(vm.runInContext('onboarding.innerHTML',context),/id="setup-errors"[^>]*role="alert"/,'Fehler erscheint oben in der Vorgabenübersicht');
assert.match(vm.runInContext('onboarding.innerHTML',context),/class="setup-criterion-error">Spieler/,'unerfüllte Vorgaben werden markiert');
assert.doesNotMatch(vm.runInContext('onboarding.innerHTML',context),/id="setup-confirm"[^>]*disabled/,'Gründungsknopf bleibt für Fehlermeldungen bedienbar');
assert.equal(vm.runInContext('activeSave',context),null,'ungültiger Kader gründet keinen Verein');
vm.runInContext(`beginSquadSetup();window.scrollY=640;window.pageYOffset=640;toggleCandidate(v17Draft.candidates[0].pid);if(window.scrollY!==640)throw Error('Kaderwahl darf die Scrollposition nicht verändern');autoSelectSquad()`,context);
assert.doesNotMatch(vm.runInContext('onboarding.innerHTML',context),/id="setup-errors"/,'gültige Auswahl entfernt den Fehler');
let state=vm.runInContext(`(()=>{const s=selectionStatus();return{valid:s.valid,count:s.count,older:s.older,avg:s.avg,payroll:s.payroll,candidates:v17Draft.candidates.length,young:v17Draft.candidates.filter(p=>p.age<24).length}})()`,context);state=JSON.parse(JSON.stringify(state));
assert.equal(state.valid,true);assert.deepEqual(state.count,{gk:1,def:3,mid:3,att:2});assert(state.older>=3);assert(state.avg>=28);assert.equal(state.candidates,16);assert(state.young<=2);assert(state.payroll>0);
vm.runInContext(`confirmInitialSquad()`,context);
state=vm.runInContext(`(()=>{const roster=[activeSave.keeper,...activeSave.squad],world=[...roster,...activeSave.world.teams.flatMap(t=>t.roster)],surname=p=>p.name.split(' ').slice(-1)[0],counts={};for(const p of world)counts[surname(p)]=(counts[surname(p)]||0)+1;return{club:activeSave.club,roster:roster.length,avg:roster.reduce((s,p)=>s+p.age,0)/roster.length,older:roster.filter(p=>p.age>=31).length,profile:activeSave.world.nationalityProfile,maxSurname:Math.max(...Object.values(counts)),clubUnique:new Set(roster.map(surname)).size}})()`,context);state=JSON.parse(JSON.stringify(state));
assert.equal(state.club,'FC Neustart');assert.equal(state.roster,9);assert(state.avg>=28);assert(state.older>=3);assert(state.profile.world>=8&&state.profile.world<=12);assert(state.maxSurname<=2);assert.equal(state.clubUnique,9);
assert(vm.runInContext(`flagSVG('ES').startsWith('<svg')&&flagSVG('FR').startsWith('<svg')`,context),'Spanische und französische Flaggen müssen als SVG erscheinen');
assert(vm.runInContext(`(()=>{const html=playerCardHTML(activeSave.squad[0]);return html.includes('Fähigkeiten')&&html.includes('Aktuelle Saison')&&html.includes('Karriere')&&html.includes('Jahre')})()`,context),'Spielerkarte muss Profil, Fähigkeiten und Statistiken enthalten');
assert(!vm.runInContext(`warningsHTML().includes('Beste Elf')`,context),'Beste Aufstellung darf nicht im Kadercheck stehen');
assert(vm.runInContext(`sponsorChoiceHTML().includes('Hauptsponsor')&&sponsorChoiceHTML().includes('Fixum')&&sponsorChoiceHTML().includes('Variabel')`,context),'Sponsorwahl muss Fixum und variable Prämie ausweisen');
assert(vm.runInContext(`typeof centerPrimaryAction==='function'&&typeof removeRedundantCenterPanels==='function'`,context),'Das Vereinszentrum braucht die phasenabhängige Hauptaktion');
state=vm.runInContext(`(()=>{const outgoing=activeSave.lineup[0],incoming=activeSave.squad.find(player=>!activeSave.lineup.includes(player.n)).n,cell=activeSave.squad.find(player=>player.n===outgoing).cell;preMatchReplaceNumber=outgoing;const changed=swapPreMatchPlayer(incoming),inherited=activeSave.squad.find(player=>player.n===incoming).cell===cell;preMatchReplaceNumber=incoming;const restored=swapPreMatchPlayer(outgoing);return{changed,inherited,restored,lineup:activeSave.lineup.length,unique:new Set(activeSave.lineup).size}})()`,context);state=JSON.parse(JSON.stringify(state));assert.deepEqual(state,{changed:true,inherited:true,restored:true,lineup:5,unique:5});

vm.runInContext(`selectSponsor('safe');for(let round=0;round<10;round++){start();if(round===0){const frozen=JSON.stringify(match.kits),current=activeSave.currentRound;activeSave.currentRound=current+1;if(JSON.stringify(match.kits)!==frozen||JSON.stringify(matchKit(0))!==JSON.stringify(match.kits.user))throw Error('Trikotfarben dürfen sich beim Rundenwechsel nicht ändern');activeSave.currentRound=current}match.score=[2,0];finishMatch()}for(const p of[activeSave.keeper,...activeSave.squad])p.age=25;activeSave.squad[0].age=38;syncLineupFromSquad();startNextSeason();selectSponsor('safe');activeSave.finance.balance=5000`,context);
state=vm.runInContext(`({open:activeSave.transfer.open,day:activeSave.transfer.day,max:activeSave.transfer.maxDays,retirements:activeSave.transfer.retirements.length,offers:activeSave.transfer.offers.filter(o=>o.kind==='regular'&&o.status==='active').length,news:activeSave.news.length})`,context);state=JSON.parse(JSON.stringify(state));
assert.equal(state.open,true);assert.equal(state.day,1);assert.equal(state.max,5);assert.equal(state.retirements,1);assert(state.offers>=6);assert(state.news>=2);

const ids=vm.runInContext(`activeSave.transfer.offers.filter(o=>o.kind==='regular'&&o.status==='active'&&!o.player.keeper).slice(0,3).map(o=>o.id)`,context);const offerIds=JSON.parse(JSON.stringify(ids));
assert.equal(vm.runInContext(`submitBid('${offerIds[0]}',1)`,context),true);assert.equal(vm.runInContext(`submitBid('${offerIds[1]}',1.15)`,context),true);assert.equal(vm.runInContext(`submitBid('${offerIds[2]}',1)`,context),false,'Mehr als zwei parallele Gebote müssen gesperrt sein');assert.equal(vm.runInContext(`activeSave.transfer.bids.filter(b=>b.status==='pending').length`,context),2);assert(vm.runInContext('activeSave.transfer.reserved',context)>0);
vm.runInContext(`Math.random=()=>0;advanceTransferDay()`,context);
state=vm.runInContext(`({day:activeSave.transfer.day,accepted:activeSave.transfer.bids.filter(b=>b.status==='accepted').length,reserved:activeSave.transfer.reserved,buys:activeSave.transfer.history.filter(h=>h.type==='buy').length})`,context);state=JSON.parse(JSON.stringify(state));assert.equal(state.day,2);assert.equal(state.accepted,2);assert.equal(state.reserved,0);assert.equal(state.buys,2);

const counterOffer=vm.runInContext(`activeSave.transfer.offers.find(o=>o.kind==='regular'&&o.status==='active'&&!o.player.keeper&&!pendingBidFor(o.id)).id`,context);assert.equal(vm.runInContext(`submitBid('${counterOffer}',.85)`,context),true);vm.runInContext(`{let values=[.9,.1];Math.random=()=>values.shift()??0;advanceTransferDay()}`,context);const counterBid=vm.runInContext(`activeSave.transfer.bids.find(b=>b.offerId==='${counterOffer}'&&b.status==='counter')?.id`,context);assert(counterBid);assert.equal(vm.runInContext(`acceptCounter('${counterBid}')`,context),true);
const saleOffer=vm.runInContext(`activeSave.transfer.salesOffers.find(o=>o.status==='active')?.id`,context);if(saleOffer){const saleBalance=vm.runInContext('activeSave.finance.balance',context);assert.equal(vm.runInContext(`acceptSaleOffer('${saleOffer}')`,context),true);assert(vm.runInContext('activeSave.finance.balance',context)>saleBalance)}

const watchId=vm.runInContext(`activeSave.transfer.offers.find(o=>o.kind==='regular'&&o.status==='active').id`,context);assert.equal(vm.runInContext(`toggleWatch('${watchId}');activeSave.transfer.watchlist.includes('${watchId}')`,context),true);vm.runInContext(`toggleCompare('${watchId}')`,context);assert.equal(vm.runInContext('activeSave.transfer.compare.length',context),1);vm.runInContext(`setMarketFilter('position','def')`,context);assert.equal(vm.runInContext(`activeSave.transfer.filters.position`,context),'def');

vm.runInContext(`advanceTransferDay();advanceTransferDay();advanceTransferDay();advanceTransferDay()`,context);assert.equal(vm.runInContext('activeSave.transfer.open',context),false);assert.equal(vm.runInContext('activeSave.transfer.day',context),5);const freeId=vm.runInContext(`activeSave.transfer.offers.find(o=>o.kind==='free'&&o.status==='active'&&!o.player.keeper).id`,context),balance=vm.runInContext('activeSave.finance.balance',context);assert.equal(vm.runInContext(`signFreeAgent('${freeId}')`,context),true);assert.equal(vm.runInContext('activeSave.finance.balance',context),balance);

const beforeLineup=vm.runInContext('activeSave.lineup.slice()',context);vm.runInContext(`applyQuickLineup('defensive')`,context);assert.equal(vm.runInContext('activeSave.lineup.length',context),5);assert.equal(vm.runInContext(`applyQuickLineup('restore')`,context),true);assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('activeSave.lineup',context))),JSON.parse(JSON.stringify(beforeLineup)));
const slotsBefore=vm.runInContext('readSlots().length',context);assert.equal(vm.runInContext(`importSaveObject({save:structuredClone(activeSave)})`,context),true);assert.equal(vm.runInContext('readSlots().length',context),slotsBefore+1);
assert(vm.runInContext('activeSave.news.length',context)>=5);
console.log('PASS: Startassistent, ältere Kader, SVG-Flaggen, Spielerkarten, Aufstellungswechsel, Hauptsponsor, feste Matchtrikots, fünf Transfertage, Gebote, Reserven, Filter, Vergleich, Nachrichten, Schnellaufstellung und Import');
