const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {makeContext}=require('./test-v41.cjs');

const context=makeContext();
for(const file of ['youth-v33.js','penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','match-report-v47.js','next-match-v49.js','set-pieces-v50.js','status-icons-v51.js','player-status-v51.js','strength-v55.js','opponent-profile-v54.js'])
 vm.runInContext(fs.readFileSync(`dist/${file}`,'utf8'),context,{filename:file});
vm.runInContext('var v24Validation=()=>[];var v25RoleBar=()=>{};var v24Remember=()=>{};var v24FatigueText=()=>"frisch";var v24TopSkills=()=>"Passspiel gut";',context);
vm.runInContext(fs.readFileSync('dist/pitch-v55.js','utf8'),context,{filename:'pitch-v55.js'});
vm.runInContext('beginSquadSetup();openCandidateProfile(v17Draft.candidates[0].pid)',context);
const draftProfile=vm.runInContext('playerCardDialog.innerHTML',context);
assert.match(draftProfile,/STARTKADER/,'draft profile opens before a save exists');
const draftSkills=draftProfile.match(/<section><h3>Fähigkeiten<\/h3>(.*?)<\/section>/s)?.[1]||'';
assert.equal((draftSkills.match(/class="v55-skill-row"/g)||[]).length,9,'draft goalkeeper profile shows all nine skills');
assert.doesNotMatch(draftSkills,/von 20|<b[^>]*>\d+<\/b>/,'draft profile does not reveal exact skills');
assert.equal(vm.runInContext('v17Draft.selected.length',context),0,'opening the profile does not select the candidate');
vm.runInContext("autoSelectSquad();confirmInitialSquad();selectSponsor('safe');",context);

const data=JSON.parse(vm.runInContext("JSON.stringify({schema:activeSave.schema,players:[activeSave.keeper,...activeSave.squad,...activeSave.world.teams.flatMap(team=>team.roster)],slots:readSlots().length})",context));
assert.equal(data.schema,5);
assert.equal(data.slots,1);
assert(data.players.length>50);
assert.match(vm.runInContext('playerCardHTML(activeSave.squad[0])',context),/Luftspiel/);
assert.match(vm.runInContext('playerCardHTML(activeSave.squad[0])',context),/Hohe Pässe/);
const marketCard=vm.runInContext("qolOfferCardHTML({...makeOffer('regular','att',72,25),expiresDay:5})",context);
assert.match(marketCard,/<span class="v55-skill-list"/,'transfer cards use the compact skill list');
assert.equal((marketCard.match(/role="listitem"/g)||[]).length,3,'transfer cards show exactly three skills');
const compact=vm.runInContext("scoutingTextHTML({name:'Test',tec:5,pas:20,fin:10,tak:9,pos:18,spd:8,sta:17,air:7})",context);
assert.match(compact,/Passspiel<\/span>.*Stellungsspiel<\/span>.*Kondition<\/span>/,'the best skills appear in descending order');
assert.doesNotMatch(compact.replace(/<[^>]+>/g,''),/ausbaufähig|stark|gut/,'visible compact text has no scouting adjectives');
assert.match(vm.runInContext("v55ColorSkills('Luftspiel stark',activeSave.squad[0])",context),/style="color:#[0-9a-fA-F]{6}"/);
assert.equal(vm.runInContext('[7,8,11,14,17].map(v55SkillColor).join(",")',context),'#A398B8,#91AEC4,#E9CF59,#F3A14A,#F26BB5');
const grouped=vm.runInContext("scoutingSkillsHTML({...activeSave.squad[0],line:'att',fin:7,tec:8,spd:11,air:17})",context);
for(const label of ['Offensiv','Defensiv','Körperlich','Luftspiel'])assert(grouped.includes(label),`player profile is missing ${label}`);
for(const color of ['#A398B8','#91AEC4','#E9CF59','#F26BB5'])assert(grouped.includes(`color:${color}`),`grouped skills are missing ${color}`);
assert.doesNotMatch(grouped,/Geistig/,'the profile does not invent a mental attribute');
const keeperSkills=vm.runInContext('scoutingSkillsHTML(activeSave.keeper)',context);
for(const label of ['Torwartspiel','Technik','Passspiel','Abschluss','Zweikampf','Stellungsspiel','Geschwindigkeit','Kondition','Luftspiel'])assert(keeperSkills.includes(label),`goalkeeper profile is missing ${label}`);
assert.equal((keeperSkills.match(/class="v55-skill-row"/g)||[]).length,9,'goalkeeper profile shows all nine abilities');
assert.equal((grouped.match(/class="v55-skill-row"/g)||[]).length,8,'outfield profile shows all eight abilities');
assert.doesNotMatch(keeperSkills,/von 20|<b[^>]*>\d+<\/b>/,'goalkeeper profile hides exact skills visually and accessibly');
assert.doesNotMatch(grouped,/von 20|<b[^>]*>\d+<\/b>/,'outfield profile hides exact skills visually and accessibly');
assert.match(keeperSkills,/Torwartspiel: (?:sehr schwach|schwach|durchschnittlich|gut|sehr gut)/,'profile exposes the skill band to screen readers');
const keeperRosterSkills=vm.runInContext('v55AllSkillsHTML(activeSave.keeper)',context);
const outfieldRosterSkills=vm.runInContext('v55AllSkillsHTML(activeSave.squad[0])',context);
assert.equal((keeperRosterSkills.match(/role="listitem"/g)||[]).length,9,'squad card shows all goalkeeper abilities');
assert.equal((outfieldRosterSkills.match(/role="listitem"/g)||[]).length,8,'squad card shows all outfield abilities');
for(const html of [keeperRosterSkills,outfieldRosterSkills])assert.doesNotMatch(html,/von 20|<b[^>]*>\d+<\/b>|aria-label="[^"]+: \d+"/,'squad overview hides exact skills visually and accessibly');
assert.match(keeperRosterSkills,/Torwartspiel: (?:sehr schwach|schwach|durchschnittlich|gut|sehr gut)/,'squad overview exposes skill bands to screen readers');
const legacyKeeper=JSON.parse(vm.runInContext("JSON.stringify((()=>{const save=structuredClone(activeSave);for(const key of ['tec','fin','tak','air'])delete save.keeper[key];for(const team of save.world.teams)for(const player of team.roster)if(player.keeper)for(const key of ['tec','fin','tak','air'])delete player[key];const oldGoalkeeping=save.keeper.gk;const loaded=ensureChampionship(save);return {keeper:loaded.keeper,world:loaded.world.teams[0].roster.find(player=>player.keeper),oldGoalkeeping}})())",context));
assert.equal(legacyKeeper.keeper.tec,legacyKeeper.oldGoalkeeping,'saved goalkeepers keep their previous technique fallback');
for(const key of ['fin','tak','air'])assert.equal(legacyKeeper.keeper[key],10,`legacy goalkeeper ${key} keeps the old match fallback`);
for(const key of ['tec','fin','tak','air'])assert(Number.isInteger(legacyKeeper.world[key]),`opponent goalkeeper is missing ${key}`);
const lineupSkills=vm.runInContext("v51LineupCardContent(activeSave.squad[0],'MF',4)",context);
assert.equal((lineupSkills.match(/role="listitem"/g)||[]).length,3,'lineup cards show three compact skill rows');
assert.match(vm.runInContext("youthPotentialHTML({player:{line:'att'},target:{fin:14,tec:14,air:14}})",context),/color:#F3A14A/);
assert.match(vm.runInContext('v42LevelHTML(17)',context),/color:#F26BB5/);
assert.match(vm.runInContext("v51LineupCardContent(activeSave.squad[0],'MF',4)",context),/data-v51-select="4"/,'starter card keeps its selection control');
assert.match(vm.runInContext("v51LineupCardContent(activeSave.squad[0],'MF',4)",context),/data-open-player=/,'starter card keeps its profile link');
for(const player of data.players){
 const keys=player.keeper?['gk','tec','pas','fin','tak','pos','spd','sta','air']:['tec','pas','fin','tak','pos','spd','sta','air'];
 for(const key of keys)assert(Number.isInteger(player[key])&&player[key]>=1&&player[key]<=20,`${player.name}: ${key}=${player[key]}`);
}
assert.equal(vm.runInContext("importSaveObject({save:{schema:4,world:{},squad:[1,2,3,4,5]}})",context),false);
assert.equal(vm.runInContext("readSlots().length",context),1);
assert.equal(vm.runInContext("importSaveObject({save:structuredClone(activeSave)})",context),true);
assert.equal(vm.runInContext("readSlots().length",context),2);

vm.runInContext("const positionProbe=players.find(player=>player.line==='mid');positionProbe.cell=27;saveCurrent();document.querySelector('#canvas').parentElement={append(){}};start()",context);
assert.equal(vm.runInContext('match.defenseLines[0]',context),0);
assert.equal(vm.runInContext("match.people.some(player=>player.t===0&&player.cell===27&&player.line==='mid'&&player.assignedLine==='def')",context),true,'die Abwehrzone muss als Einsatzposition ins Match übernommen werden');
assert.equal(vm.runInContext("(()=>{const player=match.people.find(item=>item.t===0&&item.cell===27),assigned=player.assignedLine;player.assignedLine=player.line;const native=ability(player,'pas');player.assignedLine=assigned;return Math.round((native-ability(player,'pas'))*100)/100})()",context),.45,'positionsfremdes Passspiel erhält den Match-Malus');
vm.runInContext("match.defenseLines[0]=1;const reshuffled=match.people.find(player=>player.t===0&&player.line==='mid');reshuffled.assignedLine='def';v55PrepareMovement()",context);
assert.equal(vm.runInContext('reshuffled.by',context),.63,'a midfielder assigned to defense follows the high line');
assert.equal(vm.runInContext("(()=>{const player={...reshuffled,stats:{...emptyStats(),cleanSheet:1}},assigned=player.assignedLine;player.assignedLine=player.line;const native=performanceRating(player);player.assignedLine=assigned;return Math.round((performanceRating(player)-native)*100)/100})()",context),.35,'die Spielnote bewertet die Einsatzposition als Verteidiger');
assert.equal(vm.runInContext("(()=>{const attacker=match.people.find(player=>player.t===0&&player.line==='att'),midfielder=match.people.find(player=>player.t===0&&player.line==='mid'),attackerLine=attacker.assignedLine,midfielderLine=midfielder.assignedLine;attacker.assignedLine='def';midfielder.assignedLine='att';kickoff(0);const correct=match.kickoff.kicker===midfielder;attacker.assignedLine=attackerLine;midfielder.assignedLine=midfielderLine;kickoff(0);return correct})()",context),true,'der Anstoß folgt der Einsatzposition');
assert.match(vm.runInContext('v47ReportHTML(v47Snapshot())',context),/Hohe Pässe/);
assert.match(vm.runInContext('v47PlayerStatsHTML(v47Snapshot().players.find(player=>!player.keeper),"Team")',context),/Luftduelle gewonnen/);
assert.equal(vm.runInContext("v55Exit({x:.5,y:.5},{x:-.1,y:.5}).edge",context),'left');
assert.equal(vm.runInContext("v55Exit({x:.5,y:.5},{x:.5,y:-.1}).edge",context),'top');
vm.runInContext("v55BeginThrow({edge:'left',x:v55Field.left,y:.5},0)",context);
assert.equal(vm.runInContext('match.throwIn.team',context),1);
assert.equal(vm.runInContext('match.ball.x',context),.02);
assert.equal(vm.runInContext('match.setPiece',context),null);
const previous=vm.runInContext('match.elapsed',context);
vm.runInContext('step(.5,.05)',context);
assert(vm.runInContext('match.elapsed',context)-previous<.2,'throw-in slows the clock');
vm.runInContext('for(let tick=0;tick<300&&match.throwIn;tick++)step(.1,.05)',context);
assert.equal(vm.runInContext('match.throwIn',context),null,'thrower eventually reaches the ball');
assert.equal(vm.runInContext('Boolean(match.flight)',context),true,'ball is visibly thrown back in');
vm.runInContext("(()=>{const receiver=match.people.find(player=>player.interceptTarget===match.flight.target);if(!receiver)throw Error('throw receiver does not chase the ball');receiver.x=.9;receiver.y=.9;match.flight.done();if(match.owner||!match.rebound)throw Error('missed throw must leave a loose ball');if(receiver.interceptTarget)throw Error('throw chase target was not cleared')})()",context);
vm.runInContext("match.flight=null;match.owner=match.people.find(player=>player.t===0&&!player.keeper);match.ball={x:.5,y:.5};const attacker=match.people.find(player=>player.t===0&&!player.keeper&&player!==match.owner);attacker.y=.2;const defenders=match.people.filter(player=>player.t===1);defenders.forEach((player,index)=>player.y=.3+index*.02);const snapshot=v55OffsideSnapshot(match.owner);if(!snapshot.offside.has(attacker))throw Error('offside snapshot failed');v55WhistleOffside(snapshot,attacker)",context);
assert.equal(vm.runInContext('match.setPiece.type',context),'offside');
assert.equal(vm.runInContext('Boolean(match.offsideVisual)',context),true);
assert.equal(vm.runInContext('match.ball.y',context),.5,'offside pause shows the pass-time ball');
assert.equal(vm.runInContext('attacker.y',context),.2,'offside pause keeps the pass-time offender');
const shotsBefore=vm.runInContext('match.shots.join(",")',context);
vm.runInContext('v50TakeFreeKick(match.setPiece)',context);
assert.equal(vm.runInContext('match.shots.join(",")',context),shotsBefore,'offside free kick is a short pass');
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;match.rebound=null;Math.random=()=>.5;const own=match.people.filter(player=>player.t===0&&!player.keeper),taker=own[0],receiver=own[1];for(const player of match.people){player.x=.9;player.y=.9}taker.x=.5;taker.y=.6;receiver.x=.5;receiver.y=.2;for(const rival of match.people.filter(player=>player.t===1&&!player.keeper))rival.y=.3;match.ball={x:.5,y:.6};v50TakeFreeKick({type:'freeKick',team:0,spot:{x:.5,y:.6},taker});if(!match.flight||match.flight.target.y>.3)throw Error('regular free kick did not use ground pass');match.flight.done();if(match.setPiece?.type!=='offside')throw Error('regular free-kick pass missed offside')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;match.rebound=null;Math.random=()=>.5;const own=match.people.filter(player=>player.t===0&&!player.keeper),taker=own[0],receiver=own[1];for(const player of match.people){player.x=.9;player.y=.9}taker.x=.5;taker.y=.6;receiver.x=.5;receiver.y=.53;match.ball={x:.5,y:.6};const completed=taker.stats.passComplete;v50TakeFreeKick({type:'freeKick',team:0,spot:{x:.5,y:.6},taker});receiver.x=.9;receiver.y=.9;match.flight.done();if(match.owner||!match.rebound||taker.stats.passComplete!==completed)throw Error('missed regular free kick awarded possession')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;Math.random=()=>.5;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1];for(const player of match.people)if(player!==receiver){player.x=.9;player.y=.9}receiver.x=.5;receiver.y=.5;receiver.air=10;receiver.tec=1;v55ResolveAir({passer,receiver,end:{x:.5,y:.5},snapshot:{offside:new Set()},cross:false});if(!match.rebound)throw Error('poor trap must release the ball');match.rebound=null;receiver.tec=20;v55ResolveAir({passer,receiver,end:{x:.5,y:.5},snapshot:{offside:new Set()},cross:false});if(match.owner!==receiver)throw Error('good trap must retain possession')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;Math.random=()=>0;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1];for(const player of match.people)if(player!==receiver){player.x=.9;player.y=.9}receiver.x=.5;receiver.y=.2;receiver.air=20;receiver.tec=1;match.ball={x:.5,y:.2};v55ResolveAir({passer,receiver,end:{x:.5,y:.2},snapshot:{offside:new Set()},cross:true});if(receiver.stats.headers!==1)throw Error('header shot missing')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;Math.random=()=>0;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1],defender=match.people.find(player=>player.t===1&&!player.keeper);for(const player of match.people){player.x=.9;player.y=.9}passer.x=.5;passer.y=.6;receiver.x=.5;receiver.y=.27;defender.x=.5;defender.y=.31;match.ball={x:.5,y:.6};const snapshot=v55OffsideSnapshot(passer),won=receiver.stats.aerialWon;if(!snapshot.offside.has(receiver))throw Error('aerial offside setup failed');v55ResolveAir({passer,receiver,end:{x:.5,y:.32},snapshot,cross:false});if(match.setPiece?.type!=='offside'||receiver.stats.aerialWon!==won)throw Error('offside duel winner must be whistled before possession or duel credit')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;match.rebound=null;Math.random=()=>0;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1];for(const player of match.people){player.x=.9;player.y=.9}receiver.x=.5;receiver.y=.2;match.owner=null;v55ResolveAir({passer,receiver,end:{x:.5,y:.32},snapshot:{offside:new Set()},cross:false});if(match.owner||!match.rebound||Math.abs(match.ball.y-.32)>.001)throw Error('distant player touched aerial ball without reaching its landing point')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;Math.random=()=>0;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1],rivals=match.people.filter(player=>player.t===1&&!player.keeper);for(const player of match.people){player.x=.9;player.y=.9}passer.x=.5;passer.y=.5;passer.pas=20;receiver.x=.5;receiver.y=.2;rivals[0].x=.56;rivals[0].y=.46;match.owner=passer;match.ball={x:.5,y:.5};v55GroundPass(passer,receiver);if(match.flight.target.y>.3)throw Error('unreachable defender intercepted ground pass')})()",context);
vm.runInContext("(()=>{match.setPiece=null;match.flight=null;match.rebound=null;Math.random=()=>.5;const own=match.people.filter(player=>player.t===0&&!player.keeper),passer=own[0],receiver=own[1];for(const player of match.people){player.x=.9;player.y=.9}passer.x=.5;passer.y=.5;receiver.x=.5;receiver.y=.2;match.owner=passer;match.ball={x:.5,y:.5};const completed=passer.stats.passComplete;v55GroundPass(passer,receiver);if(!receiver.interceptTarget)throw Error('pass receiver does not chase the ball');receiver.x=.9;receiver.y=.9;match.flight.done();if(match.owner||!match.rebound||passer.stats.passComplete!==completed)throw Error('missed pass must not award possession or a completion');if(receiver.interceptTarget)throw Error('pass chase target was not cleared')})()",context);
console.log('PASS: native 1–20 squads, new saves, assigned positions, touchline stop and running throw-in');

const fullMatch=makeContext();
for(const file of ['youth-v33.js','penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','match-report-v47.js','next-match-v49.js','set-pieces-v50.js','status-icons-v51.js','player-status-v51.js','strength-v55.js','opponent-profile-v54.js'])
 vm.runInContext(fs.readFileSync(`dist/${file}`,'utf8'),fullMatch,{filename:file});
vm.runInContext('var v24Validation=()=>[];var v25RoleBar=()=>{};var v24Remember=()=>{};var v24FatigueText=()=>"frisch";var v24TopSkills=()=>"Passspiel gut";',fullMatch);
vm.runInContext(fs.readFileSync('dist/pitch-v55.js','utf8'),fullMatch,{filename:'pitch-v55.js'});
vm.runInContext("beginSquadSetup();autoSelectSquad();confirmInitialSquad();selectSponsor('safe');document.querySelector('#canvas').parentElement={append(){}};start();for(let tick=0;running&&tick<6000;tick++)step(.05,.05);if(running)throw Error(`match did not end: elapsed=${match.elapsed} throw=${Boolean(match.throwIn)} flight=${Boolean(match.flight)} rebound=${Boolean(match.rebound)} piece=${Boolean(match.setPiece)}`)",fullMatch);
assert.equal(vm.runInContext('match.finished',fullMatch),true);
assert.equal(vm.runInContext('activeSave.currentRound',fullMatch),1);
assert(vm.runInContext('match.people.some(player=>player.stats.highPasses>0)',fullMatch));
console.log('PASS: complete v55 match and career progression');
