const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const elements=new Map(),storage=new Map(),scoreboard=[];
function element(){return{innerHTML:'',textContent:'',hidden:false,value:'',disabled:false,dataset:{},className:'',style:{setProperty(){}},classList:{toggle(){},remove(){}},setAttribute(){},addEventListener(){},append(){},before(){},prepend(){},focus(){},scrollIntoView(){},insertAdjacentElement(){},insertAdjacentHTML(){},querySelector(){return element()},querySelectorAll(){return[]},closest(){return null}}}
scoreboard.push(element(),element());
const document={documentElement:element(),querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll:s=>s==='.scoreboard span'?scoreboard:[],createElement:element,createTextNode:t=>t};
elements.set('#club-name',Object.assign(element(),{value:'FC Chronik'}));elements.set('#club-primary',Object.assign(element(),{value:'#2244aa'}));elements.set('#club-secondary',Object.assign(element(),{value:'#ffcc22'}));
const context={document,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{scrollTo(){}},location:{protocol:'file:'},crypto,structuredClone,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},alert:m=>{throw Error(m)},confirm:()=>true,fetch:async()=>({ok:true}),console,Math};vm.createContext(context);
for(const file of['game.js','manager-v11.js','identity-v12.js','season-v13.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);
vm.runInContext(`$('#club-form').onsubmit({preventDefault(){}})`,context);
assert(vm.runInContext(`historyHTML().includes('Vereinshistorie')&&historyHTML().includes('Saison 1')&&historyHTML().includes('Saisonstart')`,context),'Saison 1 muss vom ersten Tag an in der Vereinshistorie stehen');
vm.runInContext(`start();if(match.people.length!==12)throw Error('Kein 6 gegen 6');for(let i=0;i<10000&&running;i++)step(.05,.05);if(running)throw Error('Match hängt')`,context);
assert(vm.runInContext(`(()=>{const user=activeSave.table.find(team=>team.id==='user'),html=historyHTML();return html.includes('Saison 1')&&html.includes('1 Sp.')&&html.includes(user.w+'S')&&html.includes(user.gf+':'+user.ga)})()`,context),'Siege und Tore müssen nach jedem Spieltag live aktualisiert werden');
vm.runInContext(`for(let game=1;game<10;game++){start();if(match.people.length!==12||match.people.filter(p=>p.t===0).length!==6||match.people.filter(p=>p.t===1).length!==6)throw Error('Kein 6 gegen 6');for(let i=0;i<10000&&running;i++)step(.05,.05);if(running)throw Error('Match hängt')}`,context);
let state=vm.runInContext(`(()=>{const scorers=leaguePlayerRows(),snapshot=activeSave.clubHistory[0],leagueGoals=activeSave.table.reduce((sum,team)=>sum+team.gf,0),playerGoals=[activeSave.keeper,...activeSave.squad,...activeSave.world.teams.flatMap(team=>team.roster)].reduce((sum,player)=>sum+(storedSeason(player,1).goals||0),0);return{round:activeSave.currentRound,played:activeSave.table.every(team=>team.played===10),history:activeSave.clubHistory.length,rank:snapshot.rank,summaryGames:snapshot.played,top:snapshot.topScorer.goals,topLive:scorers[0].goals,leagueGoals,playerGoals,aiGames:activeSave.world.teams.every(team=>aiLineup(team).every(player=>storedSeason(player,1).games===10)),finale:finaleHTML(snapshot).includes('TORSCHÜTZENKÖNIG'),club:historyHTML().includes('Vereinshistorie')}})()`,context);
state=JSON.parse(JSON.stringify(state));assert.equal(state.round,10);assert(state.played);assert.equal(state.history,1);assert(state.rank>=1&&state.rank<=6);assert.equal(state.summaryGames,10);assert.equal(state.top,state.topLive);assert.equal(state.playerGoals,state.leagueGoals);assert(state.aiGames);assert(state.finale);assert(state.club);
state=vm.runInContext(`(()=>{const age=activeSave.world.teams[0].roster[0].age;startNextSeason();return{season:activeSave.seasonNumber,round:activeSave.currentRound,history:activeSave.clubHistory.length,aged:activeSave.world.teams[0].roster[0].age===age+1}})()`,context);
assert.deepEqual(JSON.parse(JSON.stringify(state)),{season:2,round:0,history:1,aged:true});
console.log('PASS: Saisonabschluss, Liga-Torschützen, Torschützenkönig, Vereinsgeschichte, Alterung und 6 gegen 6');
