const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {makeContext}=require('./test-v41.cjs');
const context=makeContext();
for(const file of['penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','match-report-v47.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);
assert.equal(vm.runInContext("teamShortCode('Athletik 06')",context),'ATH');
vm.runInContext("beginSquadSetup();autoSelectSquad();confirmInitialSquad();selectSponsor('safe');start()",context);
assert(vm.runInContext('Boolean(match)',context));
vm.runInContext("match.people[0].stats.assists=1;match.people[1].stats.goals=1;match.score=[1,0];finishMatch()",context);
const html=vm.runInContext('v47Dialog.innerHTML',context);
for(const label of['Spielbericht','Teamstatistik','Aufs Tor','Ballbesitz','Passquote','Note','Vorlagen'])assert(html.includes(label),label);
assert(html.includes('FC Dauertest'));
assert(html.includes('>1</b>'));
assert(html.includes('v47-winner')&&html.includes('class="primary v47-menu">Weiter →</button>')&&!html.includes('v47-done'));
const leagueOverview=vm.runInContext("v47CompetitionHTML(v47Snapshot('Athletik 06'))",context);
for(const label of['Weitere Ergebnisse','Ligatabelle','Torschützen','Vorlagen','Spieltag 1'])assert(leagueOverview.includes(label),label);
assert(leagueOverview.includes('class="winner"'),'league winners are highlighted');
assert(leagueOverview.includes('FC Dauertest'),'own club appears in table');
assert(html.includes('data-report-player="0"')&&html.includes('data-report-player="6"'),'both teams have clickable player rows');
assert.equal(vm.runInContext("v47OpenPlayerStats(v47Snapshot('Athletik 06'),0)",context),true);
assert(vm.runInContext('v47PlayerDialog.innerHTML',context).includes('Statistik dieses Spiels'));
assert.equal(vm.runInContext("v47OpenPlayerStats(v47Snapshot('Athletik 06'),6)",context),true);
assert(vm.runInContext('v47PlayerDialog.innerHTML',context).includes('Athletik 06'));
assert(!vm.runInContext("v47ReportHTML({...v47Snapshot('Athletik 06'),score:[0,0]},null).includes('class=\"v47-winner\"')",context));
assert(vm.runInContext("v47ReportHTML({...v47Snapshot('Athletik 06'),score:[0,0]},{score:[3,2],winner:0}).includes('class=\"v47-winner\"')",context));

const cupContext=makeContext();
for(const file of['penalties-v42.js','club-records-v43.js','club-identity-v44.js','keeper-logo-v45.js','match-report-v47.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),cupContext);
vm.runInContext("beginSquadSetup();autoSelectSquad();confirmInitialSquad();selectSponsor('safe');v41CupEnsure()",cupContext);
let count=0;
while(!vm.runInContext('Boolean(v41CupGameForUser())',cupContext)){
 vm.runInContext('start();match.score=[2,0];finishMatch();renderCenter()',cupContext);
 if(++count>10)throw Error('Cup game did not arrive');
}
vm.runInContext('start();match.score=[1,1];finishMatch()',cupContext);
assert.equal(vm.runInContext('activeSave.cup.pending.phase',cupContext),'choose');
assert.equal(vm.runInContext('activeSave.cup.pending.report.players.length',cupContext),12);
assert.equal(vm.runInContext('activeSave.cup.pending.report.score.join(":")',cupContext),'1:1');
const cupOverview=vm.runInContext('v47CompetitionHTML(activeSave.cup.pending.report)',cupContext);
for(const label of['Pokal','Alle Ergebnisse','Turnierbaum','Torschützen','Vorlagen'])assert(cupOverview.includes(label),label);
assert(!cupOverview.includes('Ligatabelle'));
vm.runInContext("activeSave.cup.rounds[0]=[{home:'user',away:'team-1',result:[2,1],winner:'user'},{home:'team-2',away:'team-3',result:[0,1],winner:'team-3'}]",cupContext);
const completedCupRound=vm.runInContext("v47CompetitionHTML({...activeSave.cup.pending.report,competition:{type:'cup',stage:0}})",cupContext);
assert.equal((completedCupRound.match(/class="v47-result"/g)||[]).length,2,'cup round overview shows every completed game, including the user match');
const cupResult=vm.runInContext("v47OtherResultHTML({home:'team-1',away:'team-2',result:[1,1],winner:'team-2',penalties:[2,3]},'cup')",cupContext);
assert(cupResult.includes('class="winner"')&&cupResult.includes('Elfmeterschießen 2 : 3'));
console.log('PASS: compact team codes, both post-match squads, assists and persisted cup report');
