const fs=require('fs'),vm=require('vm'),assert=require('assert');
const prelude=fs.readFileSync('work/test-v31.cjs','utf8').split('const context=makeContext();')[0];
const makeContext=new Function('require',prelude+'return makeContext')(require),context=makeContext();
let signingResults=0;context.v28ShowSigningResult=()=>{signingResults++;return true};
for(const file of['youth-v33.js','season-roster-v34.js','transfer-sections-v35.js','youth-direct-v36.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);
const run=source=>vm.runInContext(source,context);

run("beginSquadSetup();autoSelectSquad();confirmInitialSquad();selectSponsor('safe');for(const player of[activeSave.keeper,...activeSave.squad,homeKeeper,...players])player.age=18;for(let round=0;round<10;round++){start();match.score=[2,0];finishMatch()}v31SetStage('complete');selectSponsor('safe')");
const first=run('ensureYouth().candidates[0].id'),second=run('ensureYouth().candidates[1].id');
const initialBalance=run('ensureFinance(activeSave).balance');
const unknown=run('youthCandidateHTML(ensureYouth().candidates[0])');
assert(unknown.includes(`data-youth-scout="${first}"`));
assert(unknown.includes(`data-youth-sign="${first}"`));
assert(!unknown.includes('Potenzial:'));
assert.equal(run(`signYouth('${first}')`),true,'Verpflichtung ohne Scouting gelingt');
assert.equal(run(`signYouth('${first}')`),false,'keine doppelte Verpflichtung');
assert.equal(run('ensureYouth().candidates[0].scouted'),false,'Verpflichtung schaltet Scouting nicht frei');
assert.equal(run('ensureYouth().candidates[0].signed'),true);
assert.equal(run('ensureFinance(activeSave).balance'),initialBalance-100);
assert.equal(run("ensureFinance(activeSave).ledger.filter(entry=>entry.type==='youth-scout').length"),0);
assert.equal(run("ensureFinance(activeSave).ledger.filter(entry=>entry.type==='youth-sign').length"),1);
assert.equal(run('activeSave.squad.filter(player=>player.youthPotential).length'),1);
run('openSlot(readSlots().find(item=>item.id===activeSave.id))');
assert.equal(run('ensureYouth().candidates[0].signed'),true,'Direktverpflichtung bleibt gespeichert');
assert.equal(run('ensureYouth().candidates[0].scouted'),false);
assert.equal(run(`scoutYouth('${second}')`),true);
assert.equal(run(`signYouth('${second}')`),true,'gescouteter Spieler bleibt verpflichtbar');
assert.equal(run('ensureFinance(activeSave).balance'),initialBalance-240);
assert.equal(run("ensureFinance(activeSave).ledger.filter(entry=>entry.type==='youth-scout').length"),1);
assert.equal(run("ensureFinance(activeSave).ledger.filter(entry=>entry.type==='youth-sign').length"),2);
assert.equal(signingResults,2,'beide Jugendverpflichtungen zeigen eine Bestätigung');
console.log('PASS: Jugendspieler direkt oder nach Scouting verpflichten, Werte verborgen, Kosten einmalig, Speicherung');
