const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {makeContext}=require('./test-v41.cjs');
const context=makeContext();
for(const file of['penalties-v42.js','club-records-v43.js','club-identity-v44.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),context);

vm.runInContext("v44Choice.home='hoops';v44Choice.away='diagonal';v44Choice.shape='circle';v44Choice.decoration='chevron';var v44TestWorld=makeWorld('#000000','#ffffff',true)",context);
const kits=JSON.parse(JSON.stringify(vm.runInContext('v44TestWorld.kits',context)));
assert.equal(kits.home.style,'hoops');
assert.equal(kits.away.style,'diagonal');
assert.equal(kits.tertiary,'#f0d889');
assert.equal(kits.home.main,'#000000');
assert.equal(kits.home.trim,'#ffffff');
assert.equal(kits.home.accent,kits.tertiary);
assert.equal(kits.away.main,'#ffffff');
assert.equal(kits.away.trim,kits.tertiary);
assert.equal(kits.away.accent,'#000000');
assert.deepEqual(kits.crest,{shape:'circle',decoration:'chevron'});
assert(vm.runInContext("luminance(v44Accent('#000000'))>=.24",context));
assert(vm.runInContext("crestHTML('FC Test',v44TestWorld.kits)",context).includes('Vereinswappen FC Test'));
assert(vm.runInContext("v44ShirtSVG({n:9},v44TestWorld.kits.home)",context).includes('>9</text>'));
assert(vm.runInContext("v44ShirtSVG(null,v44TestWorld.kits.home)",context).includes('fill="#f0d889"'),'home shirt displays tertiary accents');
assert(vm.runInContext("v44ShirtSVG(null,v44TestWorld.kits.away)",context).includes('fill="#000000"'),'away shirt displays primary accents');
vm.runInContext("beginSquadSetup();autoSelectSquad();confirmInitialSquad();applyClubTheme()",context);
assert.equal(vm.runInContext('activeSave.world.kits.home.style',context),'hoops');
assert.equal(vm.runInContext('activeSave.world.kits.away.style',context),'diagonal');
assert.equal(vm.runInContext('activeSave.world.kits.crest.shape',context),'circle');
vm.runInContext("selectSponsor('safe');start();var v44Canvas=document.querySelector('#canvas'),v44GetContext=v44Canvas.getContext;v44Canvas.getContext=()=>({...v44GetContext(),strokeText(){}});match.people[0].x=.5;match.people[0].y=.5;match.people[1].x=.5;match.people[1].y=.5;var v44BeforeDraw=JSON.stringify(match.people.map(player=>[player.x,player.y]));draw()",context);
assert.equal(vm.runInContext('JSON.stringify(match.people.map(player=>[player.x,player.y]))',context),vm.runInContext('v44BeforeDraw',context),'visual separation must not change match positions');
vm.runInContext("var v44OldSave=structuredClone(activeSave);delete v44OldSave.world.kits.tertiary;delete v44OldSave.world.kits.home.accent;delete v44OldSave.world.kits.away.accent;var v44Restored=ensureChampionship(v44OldSave)",context);
assert.equal(vm.runInContext('v44Restored.world.kits.tertiary',context),undefined,'older saves remain valid without a third color');
assert.equal(vm.runInContext('v44Restored.world.kits.away.main===v44OldSave.world.kits.away.main',context),true,'older away colors are not rewritten');
const visual=JSON.parse(vm.runInContext('JSON.stringify(v44VisualPositions([{x:.5,y:.5},{x:.5,y:.5},{x:.51,y:.5},{x:.5,y:.5}]))',context));
for(let i=0;i<visual.length;i++)for(let j=i+1;j<visual.length;j++)
 assert(Math.hypot(visual[i].x-visual[j].x,visual[i].y-visual[j].y)>=49.9,'overlapping player markers separate while drawn');

vm.runInContext(`var v44TeamA=v42Teams[0],v44TeamB=v42Teams[2];var v44SessionTest={mode:'demo',ownName:v44TeamA.name,opponentName:v44TeamB.name,ownColour:v42Colour(v44TeamA.id),opponentColour:v42Colour(v44TeamB.id),own:v42DemoRoster(v44TeamA),opponent:v42DemoRoster(v44TeamB),order:[1,2,4,6,7,9],opponentOrder:[2,4,6,7,9,1],score:[0,0],kicks:[],phase:'shooting'};`,context);
const scene=vm.runInContext('v42SceneHTML(v44SessionTest)',context);
assert(scene.includes('v44-keeper-shirt'));
assert(scene.includes('Torwarttrikot'));
assert(scene.includes('v42-shooter'));
assert.equal((scene.match(/aria-label="Torwarttrikot"/g)||[]).length,2);
console.log('PASS: six kit patterns, crest selection, dark colour contrast and penalty keeper shirt');
