'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{createServer}=require('../../serve.cjs');
const base=path.resolve(__dirname,'../../../..'),owned=['dist/ui-flutlicht/navigation.js','dist/ui-flutlicht/navigation.css'];
const hashes=()=>Object.fromEntries(owned.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex')]));
const out=path.join(base,'outputs/ui-redesign/I00-navigation',new Date().toISOString().replace(/[:.]/g,'-'));
const routes={squad:['roster','contracts','youth'],transfers:['search','listed','own','offers','balance'],competition:['league','cup','europe','countries','archive']};
(async()=>{
 const before=hashes();fs.mkdirSync(out,{recursive:true});const server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const errors=[],checks=[];
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${server.address().port}/source/index.html`);
  if(!await page.evaluate(()=>D6Flutlicht.registry.ids().includes('navigation'))){await page.addScriptTag({content:fs.readFileSync(path.join(base,owned[0]),'utf8')});await page.addStyleTag({content:fs.readFileSync(path.join(base,owned[1]),'utf8')});}
  await page.evaluate(async()=>{
   v61CurrentCareer=await v61StoreNewCareer(v61CreateCareer('GER-2','fl-navigation-check','Navigation Fixture'));v61RenderCareer(v61CurrentCareer);v61SetCareerTab('squad',false);D6Flutlicht.adapter.refresh();
   window.originals={contract:document.querySelector('.v66-contracts'),youth:document.querySelector('.v67-youth'),search:document.querySelector('#v66-country'),listed:document.querySelector('#v72-max-price'),league:document.querySelector('[data-v46-view=competition] [data-fl-section-panel=league] details'),country:document.querySelector('[data-v62-country-choice]'),calendar:document.querySelector('[data-v46-view=calendar] .v62-calendar-list li'),stats:document.querySelector('[data-v46-view=statistics] .v46-stat-category')};
   window.nativeClicks=0;const button=document.createElement('button');button.textContent='Native view-only listener fixture';button.dataset.navigationFixtureAction='true';button.addEventListener('click',()=>nativeClicks++);originals.contract.append(button);
   window.snapshot=JSON.stringify(v61CurrentCareer);
  });
  const view=route=>page.locator(`[data-v46-view="${route}"]`),choose=async(route,section,layoutOnly=false)=>{await page.evaluate(route=>{v61SetCareerTab(route,false);D6Flutlicht.adapter.refresh()},route);const tab=view(route).locator(`[data-fl-section-tab=${section}]`);if(layoutOnly)await tab.evaluate(button=>button.click());else await tab.click();};
  for(const [route,sections] of Object.entries(routes))assert.equal(await view(route).locator('.fl-section-tabs [role=tab]').count(),sections.length);
  await choose('squad','contracts');await page.locator('[data-navigation-fixture-action]').click();assert.equal(await page.evaluate(()=>nativeClicks),1);
  await choose('squad','roster');await view('squad').locator('[data-fl-squad-search]').fill('Unmöglicher Fixture Name');await choose('squad','youth');await choose('squad','roster');assert.equal(await view('squad').locator('[data-fl-squad-search]').inputValue(),'Unmöglicher Fixture Name');
  await choose('transfers','listed');await page.locator('#v72-max-price').evaluate(node=>node.value='1230');await choose('transfers','search');await choose('transfers','listed');assert.equal(await page.locator('#v72-max-price').inputValue(),'1230');
  await choose('competition','countries');const country=await page.locator('[data-v62-country-choice] option').nth(1).getAttribute('value');await page.locator('[data-v62-country-choice]').selectOption(country);await choose('competition','cup');await choose('competition','countries');assert.equal(await page.locator('[data-v62-country-choice]').inputValue(),country);assert.equal(await page.locator('[data-v62-country-panel]:visible').getAttribute('data-v62-country-panel'),country);
  assert.equal(await page.evaluate(()=>originals.contract===document.querySelector('.v66-contracts')&&originals.youth===document.querySelector('.v67-youth')&&originals.search===document.querySelector('#v66-country')&&originals.listed===document.querySelector('#v72-max-price')&&originals.country===document.querySelector('[data-v62-country-choice]')&&originals.calendar===document.querySelector('[data-v46-view=calendar] .v62-calendar-list li')&&originals.stats===document.querySelector('[data-v46-view=statistics] .v46-stat-category')),true,'tab and local filter interactions must retain controller nodes');
  // Native market filtering deliberately rebuilds the controller DOM; the selected subsection survives that rebuild.
  await choose('transfers','listed');await page.locator('#v72-max-price').dispatchEvent('change');await page.waitForFunction(()=>document.querySelector('[data-v46-view=transfers]').dataset.flSection==='listed');assert.equal(await page.locator('#v72-max-price').inputValue(),'1230');
  await choose('squad','roster');await view('squad').locator('[data-fl-section-tab=roster]').focus();await page.keyboard.press('ArrowLeft');assert.equal(await view('squad').getAttribute('data-fl-section'),'youth');assert.equal(await page.evaluate(()=>document.activeElement.dataset.flSectionTab),'youth');await page.keyboard.press('Home');assert.equal(await view('squad').getAttribute('data-fl-section'),'roster');await page.keyboard.press('End');assert.equal(await view('squad').getAttribute('data-fl-section'),'youth');
  await page.evaluate(()=>{v61SetCareerTab('calendar',false);D6Flutlicht.adapter.refresh()});await view('calendar').locator('[data-fl-filter=competition]').selectOption('cup');await view('calendar').locator('[data-fl-filter=time]').selectOption('upcoming');assert.equal(await view('calendar').locator('.v62-calendar-list li:visible').evaluateAll(rows=>rows.every(row=>row.dataset.flCalendarType==='cup'&&row.classList.contains('upcoming'))),true);await view('calendar').locator('[data-fl-filter=time]').selectOption('played');assert.equal(await view('calendar').locator('.v62-calendar-list li:visible').count(),0);assert.equal(await view('calendar').locator('.fl-navigation-empty').isVisible(),true);
  await page.evaluate(()=>{v61SetCareerTab('statistics',false);D6Flutlicht.adapter.refresh()});await view('statistics').locator('[data-fl-filter=competition]').selectOption('cup');await view('statistics').locator('[data-fl-filter=category]').selectOption('assists');assert.equal(await view('statistics').locator('.v62-stat-board:visible').getAttribute('data-fl-stat-type'),'cup');assert.equal(await view('statistics').locator('.v62-stat-board:visible .v46-stat-category:visible').getAttribute('data-fl-stat-category'),'assists');
  await page.evaluate(()=>{v61SetCareerTab('squad',false);D6Flutlicht.adapter.refresh()});await view('squad').locator('[data-fl-section-tab=contracts]').click();await page.evaluate(()=>{window.focused=document.activeElement;D6Flutlicht.adapter.refresh()});assert.equal(await page.evaluate(()=>document.activeElement===focused),true,'refresh preserves focused tab');
  assert.equal(await page.evaluate(()=>JSON.stringify(v61CurrentCareer)),await page.evaluate(()=>snapshot),'presentation changed career data');
  // All native main menus remain available, while one bounded submenu panel is visible.
  for(const width of [320,390,768,1440])for(const theme of ['light','dark'])for(const language of ['de','en']){
   await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});await page.evaluate(language=>{doppel6Language.set(language);D6Flutlicht.adapter.refresh()},language);assert.equal(await page.locator('.fl-shell').getAttribute('data-fl-theme'),theme,'actual rendered colour scheme');
   for(const [route,sections] of Object.entries(routes))for(const section of sections){
    await choose(route,section,true);const result=await page.evaluate(route=>({overflow:document.documentElement.scrollWidth>innerWidth,visible:document.querySelector(`[data-v46-view="${route}"]`).querySelectorAll('.fl-section-panel:not([hidden])').length,minHeight:Math.min(...[...document.querySelector(`[data-v46-view="${route}"]`).querySelectorAll('.fl-section-tabs [role=tab]')].map(button=>button.getBoundingClientRect().height))}),route);assert.equal(result.overflow,false,`${width}/${theme}/${language}/${route}/${section}`);assert.equal(result.visible,1);assert.ok(result.minHeight>=44);checks.push({width,theme,language,route,section,...result});
   }
   for(const route of ['calendar','statistics','matchplan','settings']){await page.evaluate(route=>{v61SetCareerTab(route,false);if(route==='settings')v61CareerTab='settings';D6Flutlicht.adapter.refresh()},route);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}/${theme}/${language}/${route}`);checks.push({width,theme,language,route,overflow});}
   if([390,1440].includes(width)&&language==='de'){await choose('competition','cup');await page.screenshot({path:path.join(out,`competition-cup-${width}-${theme}.png`),fullPage:true});await choose('squad','contracts');await page.screenshot({path:path.join(out,`squad-contracts-${width}-${theme}.png`),fullPage:true});}
  }
  await page.evaluate(()=>{v61SetCareerTab('competition',false);D6Flutlicht.adapter.refresh();D6Flutlicht.navigation.select('competition','archive',{focus:true})});assert.equal(await view('competition').getAttribute('data-fl-section'),'archive');assert.equal(await page.evaluate(()=>document.activeElement.dataset.flSectionTab),'archive');
  assert.equal(await page.evaluate(()=>{const view=document.querySelector('[data-v46-view=squad]'),tab=view.querySelector('[data-fl-section-tab=roster]'),placeholder=document.createComment('detached navigation fixture'),before=JSON.stringify(history.state);view.before(placeholder);view.remove();tab.click();tab.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));const safe=before===JSON.stringify(history.state)&&D6Flutlicht.navigation.select('squad','roster')===false;placeholder.replaceWith(view);return safe;}),true,'retained detached menu nodes cannot dispatch root navigation');
  assert.deepEqual(errors,[]);assert.deepEqual(hashes(),before);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed:true,checks,assertions:['real source three squad/five transfer/five competition sections','same native controller nodes and listeners','filter values remain on tab switching','native country action remains functional','keyboard wrap/Home/End/focus','local calendar filters use real type/status markers','statistics filters retain exact native recorded boards and category containers','tab refresh preserves focus','all main-menu layouts and 44px tabs','no career mutation from view actions'],limitations:['isolated test career; direct native filter rerender/save effects validated by root integration checks','no physical device/Safari/screen-reader verification'],hashes:before},null,2));console.log(out);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1});
