/* Sanitized display-only fixture. No real saves or internal ability values. */
(() => {
  const bands=['violetgray','bluegray','yellow','orange','pink'];
  const colors=['Violettgrau','Blaugrau','Gelb','Orange','Pink'];
  const names=['Technik','Passspiel','Abschluss','Zweikampf','Stellungsspiel','Geschwindigkeit','Kondition','Luftspiel'];
  const rows=[
    {id:'fixture-keeper',name:'Alexandria Sehrlangername von Beispielhausen',number:1,nationCode:'DE',nationLabel:'Deutschland',positionCode:'gk',positionLabel:'Torwart',age:37,skills:['Torwartspiel',...names].map((label,i)=>({key:`skill-${i}`,label,band:bands[i%5],colorLabel:colors[i%5]})),form:{band:'pink',label:'Sehr gut'},freshness:{percent:100,band:'pink',label:'Frische'},stats:{appearances:6,substitutions:null,substitutionCoverage:'missing',goals:0,assists:0,averageRating:null,ratedGames:0}},
    {id:'fixture-attacker',name:'Élodie Beispiel',number:11,nationCode:'FR',nationLabel:'Frankreich',positionCode:'att',positionLabel:'Angriff',age:18,skills:names.map((label,i)=>({key:`skill-${i}`,label,band:bands[i%5],colorLabel:colors[i%5]})),form:{band:'violetgray',label:'Sehr schwach'},freshness:{percent:20,band:'violetgray',label:'Frische'},stats:{appearances:6,substitutions:3,substitutionCoverage:'complete',goals:2,assists:1,averageRating:7.4,ratedGames:5}},
    {id:'fixture-defender',name:'Sam & Pat <Test>',number:4,nationCode:'AT',nationLabel:'Österreich',positionCode:'def',positionLabel:'Abwehr',age:28,skills:[{key:'unknown',label:'Passspiel',band:null,colorLabel:'Nicht bekannt'}],form:null,freshness:null,stats:{appearances:0,substitutions:null,substitutionCoverage:'partial',goals:0,assists:0,averageRating:null,ratedGames:0}}
  ];
  window.flSquadFixture={players:{season:2,ownClubId:'fixture-club',roster:rows,all:[...rows,{...rows[1],id:'fixture-former',name:'Frühere Spielerin'}]}};
  const E=value=>String(value).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));
  window.flSquadMarkup=`<section data-v46-view="squad"><section class="v61-roster-section"><h2>Profikader</h2><div class="v61-roster-table-wrap"><table class="v61-roster-table"><thead><tr>${[['number','#'],['name','Spieler'],['position','Position'],['age','Alter'],['games','Sp.'],['goals','T'],['assists','V'],['rating','Ø-Note']].map(([key,label])=>`<th><button data-v61-roster-sort="${key}">${label}<span></span></button></th>`).join('')}</tr></thead><tbody>${rows.map((p,i)=>`<tr data-v61-roster-row data-name="${E(p.name)}" data-number="${p.number}" data-age="${p.age}" data-position="${i}" data-games="${p.stats.appearances}" data-goals="${p.stats.goals}" data-assists="${p.stats.assists}" data-rating="${p.stats.averageRating||0}"><td><span class="v61-shirt">${p.number}</span></td><th scope="row"><button class="player-link" data-v61-player="${p.id}"><span class="flag-icon" aria-label="${p.nationLabel}">⚑</span>${E(p.name)}</button></th><td>${p.positionLabel}</td><td>${p.age}</td><td>${p.stats.appearances}</td><td>${p.stats.goals}</td><td>${p.stats.assists}</td><td>${p.stats.averageRating||'–'}</td></tr>`).join('')}</tbody></table></div></section><section class="v66-contracts"><h3>Native contracts</h3><button data-native-contract>Preserved action</button></section><section id="v67-youth"><h3>Native youth</h3><button data-v67-profile="fixture-youth">Youth profile</button></section></section>`;
  window.flSquadProfileMarkup='<div class="player-card-head"><h2>Frühere Spielerin</h2><button data-v61-close>×</button></div><nav class="v74-profile-tabs"><button data-v74-profile-tab="overview">Übersicht</button><button data-v74-profile-tab="career">Karriere</button></nav><div data-v74-profile-panel="overview"><div class="player-card-facts"><span>Marktwert<b>400 Credits</b></span><span>Vertrag bis<b>Saison 3</b></span></div><section><h3>Fähigkeiten</h3><div class="v55-skill-groups">Native qualitative skills</div><div class="v55-skill-legend">Native legend</div></section><section data-v127-season-stats><h3>Native full season statistics</h3><p>6 Einsätze · 540 Minuten · Tacklingquote nur aus erfassten Partien.</p></section><section class="v72-profile-offer"><button data-native-transfer>Native offer</button></section></div><div data-v74-profile-panel="career" hidden><div class="v64-player-seasons"><p><strong>Saison 1 · Beispielverein</strong><span>10 Einsätze · 900 Minuten · 5 Tore · 3 Vorlagen</span></p></div><div class="v74-honour-sections"><section>Mannschaftstitel</section><section>Persönliche Awards · Man of the Match 3×</section></div></div>';
})();
